src/objects/Account_Fund__c.object
<CustomObject>
    <description>Junction object between Account and Fund objects. 
This object will be used to maintain the Account to Fund relationships.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Funds</relationshipLabel>
        <relationshipName>Related_Funds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Fund__c</fullName>
        <label>Fund</label>
        <referenceTo>Fund__c</referenceTo>
        <relationshipLabel>Related Accounts</relationshipLabel>
        <relationshipName>Related_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Primary_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Flag</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Fund</label>
    <nameField>
        <displayFormat>AFN-{0000}</displayFormat>
        <label>Account Fund Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Fund</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Fund__c.object
<CustomObject>
    <description>Object will track information related to Funded Patients.</description>
    <fields>
        <fullName>Amount_Limit__c</fullName>
        <description>Amount limit enforced in PO</description>
        <label>Amount Limit</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Auth_End_Date__c</fullName>
        <description>Date when the authorization ends</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Auth End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Auth_Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>Date when the authorization starts</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Auth Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Limit_Type__c</fullName>
        <description>Type of limit enforce in PO</description>
        <label>Limit Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Quantity</fullName>
                </value>
                <value>
                    <fullName>Amount</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PO_Reference_Number__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Tracks the PO Number</description>
        <encryptionScheme>None</encryptionScheme>
        <label>PO Reference Number</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Payor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Fund associated with the Payor.</description>
        <label>Payor</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Fund Payor should be of Payor type if using GBP or EUR. Otherwise Fund Currency should be in USD.</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>contains</operation>
                <value>Payor</value>
            </filterItems>
            <filterItems>
                <field>$Source.CurrencyIsoCode</field>
                <operation>equals</operation>
                <value>USD</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fund (Payor)</relationshipLabel>
        <relationshipName>Payor_Fund</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Receiver_Qty_Limit__c</fullName>
        <description>Qty of Receivers that can be used within the Authorized period</description>
        <label>Receiver Qty Limit</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sensor_Limit__c</fullName>
        <description>Qty of Sensors that can be used within the Authorized period</description>
        <label>Sensor Qty Limit</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transmitter_Qty_Limit__c</fullName>
        <description>Qty of Transmitters that can be used within the Authorized period</description>
        <label>Transmitter Qty Limit</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Fund</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>Fund Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fund</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClsAccountFundTriggerHandler_Test.cls
/*******************************************************************************************
@Author        : 	P Saini
@Date Created    :  Mar 06, 2019
@Description    : 	Test class for ClsAccountFundTriggerHandler
*********************************************************************************************/
@isTest
private class ClsAccountFundTriggerHandler_Test {
    @isTest static void TestAccountFundTriggerHandler(){
    	List<Account> lstGBAcc = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'GB Consumer', 'United Kingdom');
        Account payorAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'GB Payor', 'United Kingdom')[0];
        
        Fund__c Fd = new Fund__c();
        Fd.PO_Reference_Number__c ='87666787';
        Fd.Limit_Type__c ='Quantity';        
        Fd.Payor__c = payorAccount.Id;
        Fd.Amount_Limit__c = 100000;
        Fd.Auth_End_Date__c = Date.today().addDays(100);
        Fd.Auth_Start_Date__c = Date.today();
        Fd.Receiver_Qty_Limit__c = 100; 
        Fd.Sensor_Limit__c = 100; 
        Fd.Transmitter_Qty_Limit__c = 100 ;        
        insert Fd ;
        
        Fund__c Fd1 = new Fund__c();
        Fd1.PO_Reference_Number__c ='87666711';
        Fd1.Limit_Type__c ='Quantity';        
        Fd1.Payor__c = payorAccount.Id;
        Fd1.Amount_Limit__c = 100000;
        Fd1.Auth_End_Date__c = Date.today().addDays(100);
        Fd1.Auth_Start_Date__c = Date.today();
        Fd1.Receiver_Qty_Limit__c = 100; 
        Fd1.Sensor_Limit__c = 100; 
        Fd1.Transmitter_Qty_Limit__c = 100 ;        
        insert Fd1 ;
        
        Account_Fund__c af= new Account_Fund__c(Account__c=lstGBAcc[0].Id, Fund__c=fd.Id, Primary_Flag__c=false);        
        insert af;
        af.Primary_Flag__c=true; update af;
        
        Account_Fund__c af1= new Account_Fund__c(Account__c=lstGBAcc[0].Id, Fund__c=fd1.Id, Primary_Flag__c=true);
        insert af1;
    }
}