src/objects/Account_Token__c.object
<CustomObject>
    <description>This Object will help to store the token and 6-digits code to authenticate Customer and create Account Linkage.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Tokens</relationshipLabel>
        <relationshipName>Account_Tokens</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expiration_Time__c</fullName>
        <description>This field will determine the validity of the Token or Verification Code submitted by customer.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Expiration Time</label>
        <type>DateTime</type>
    </fields>
    <label>Account Token</label>
    <nameField>
        <displayFormat>Token-{00000}</displayFormat>
        <label>AccountToken</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Tokens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BClsDeleteExpiredAccountTokens.cls
/*******************************************************
@Author        : Priyanka Kajawe 
@Date Created    : 5/08/2018
@Description    : Delete Expired Account Tokens
*******************************************************/
global class BClsDeleteExpiredAccountTokens implements Database.Batchable<sObject> {
    DateTime twentyFourHoursAgo = System.now().addHours(-24);
    
    global Database.QueryLocator start(Database.BatchableContext info) {
        return Database.getQueryLocator([SELECT Id, Account__c from Account_Token__c where Expiration_Time__c <= :twentyFourHoursAgo]);      
    }
    //Method to execute the batch  
    global void execute(Database.BatchableContext info, List<Account_Token__c> scope) {
        Database.delete(scope);
    }
    
    //Finish Method
    global void finish(Database.BatchableContext BC)
    {
        
    }    
}