src/objects/Account_Fund__c.object
<CustomObject>
    <description>Junction object between Account and Fund objects. 
This object will be used to maintain the Account to Fund relationships.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Funds</relationshipLabel>
        <relationshipName>Related_Funds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Fund__c</fullName>
        <label>Fund</label>
        <referenceTo>Fund__c</referenceTo>
        <relationshipLabel>Related Accounts</relationshipLabel>
        <relationshipName>Related_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Primary_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Flag</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Fund</label>
    <nameField>
        <displayFormat>AFN-{0000}</displayFormat>
        <label>Account Fund Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Fund</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Fund__c.object
<CustomObject>
    <description>Object will track information related to Funded Patients.</description>
    <fields>
        <fullName>Payor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Fund associated with the Payor.</description>
        <label>Payor</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Fund Payor should be of Payor type if using GBP or EUR. Otherwise Fund Currency should be in USD.</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>contains</operation>
                <value>Payor</value>
            </filterItems>
            <filterItems>
                <field>$Source.CurrencyIsoCode</field>
                <operation>equals</operation>
                <value>USD</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fund (Payor)</relationshipLabel>
        <relationshipName>Payor_Fund</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fund</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>Fund Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fund</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClsJobUpdateAccountsWithFund.cls
public class ClsJobUpdateAccountsWithFund implements Queueable {
    private List<Account_Fund__c> lstAF= new List<Account_Fund__c>();
    public ClsJobUpdateAccountsWithFund(List<Account_Fund__c> lst) {
        this.lstAF= lst;       
    }
    public void execute(QueueableContext context) {
        if(!lstAF.isEmpty()){
            set<Id> setAccId= new set<Id>(); set<Id> setAFId= new set<Id>();
            for(Account_Fund__c sf:lstAF){
            		
                if(sf.Primary_Flag__c){
                    setAccId.Add(sf.Account__c);
                    setAFId.Add(sf.Fund__c);
                }
            }
            Map<Id, Account_Fund__c> mapAF= new Map<Id, Account_Fund__c>([Select Id, Fund__c, Fund__r.Payor__c,Account__c, Account__r.Fund__c, 
                Account__r.Payor__c From Account_Fund__c Where ID IN :setAFId]);
            List<Account> lstAccUpd= new List<Account>();
            for(Account_Fund__c af : mapAF.values()){
            	Account a = new Account(Id=af.Account__c, Fund__c=af.Fund__c, Payor__c=af.Fund__r.Payor__c);
                lstAccUpd.Add(a);
            }
            
            if(lstAccUpd.size()>0){
            	update lstAccUpd;    
        	}
        }
    }
}