src/objects/Address__c.object
<CustomObject>
    <description>Created this custom object to track Address information.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Straße, Hausnummer</inlineHelpText>
        <label>Address Line 1</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>City</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bill To</fullName>
                </value>
                <value>
                    <fullName>Ship To</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SSIP_Rule__c.object
<CustomObject>
    <description>Object stores all SSIP rule for the customers.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Master detail relationship to the account.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SSIP Rule</relationshipLabel>
        <relationshipName>SSIP_Rule</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country to which this rule is tied to</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>First Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>SSIP Rule</relationshipLabel>
        <relationshipName>SSIP_Rule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Repeat_Order_Lead_Days__c</fullName>
        <inlineHelpText>Lead days for the first shipment</inlineHelpText>
        <label>First Repeat Order Lead Days</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Frequency_In_Days__c</fullName>
        <description>Schedule interval between each shipments.</description>
        <label>Frequency (In Days)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Term__c</fullName>
        <defaultValue>IF( $RecordType.DeveloperName = &apos;CH_SSIP_Rule&apos;, &apos;net30&apos;, &apos;net30&apos;)</defaultValue>
        <description>Payment terms that will be used to track the payment. The default value will be based on the country&apos; preference</description>
        <label>Payment Term</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Payment_Term</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PriceBookEntryId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>PriceBookEntryId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Price book, which will filter out only SSIP Pricebooks</description>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>SSIP Rule</relationshipLabel>
        <relationshipName>SSIP_Rule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>SSIP Rule</relationshipLabel>
        <relationshipName>SSIP_Rule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Product quantity populated based on the product that is chosen. Information is recorded in the pricebook entry level.</description>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rule_End_Date__c</fullName>
        <description>Date when the rule will end.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Date should be greater than or equal to today&apos;s date. Setting this date will delete any open schedules past this date.</inlineHelpText>
        <label>Rule End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Rule_Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Date when the rule will start. Defaulted to current date.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Rule Start Date</label>
        <type>Date</type>
    </fields>
    <label>SSIP Rule</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SSIP Rule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Liechtenstein</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <customValue>
        <fullName>Ireland</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Chile</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Spain</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong</fullName>
    </customValue>
    <customValue>
        <fullName>Hungary</fullName>
    </customValue>
    <customValue>
        <fullName>Israel</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Jordan</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <customValue>
        <fullName>Korea</fullName>
    </customValue>
    <customValue>
        <fullName>Kuwait</fullName>
    </customValue>
    <customValue>
        <fullName>Lebanon</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>Norway</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>Oman</fullName>
    </customValue>
    <customValue>
        <fullName>Poland</fullName>
    </customValue>
    <description>Global picklist will be used in various places</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

src/globalValueSets/Payment_Term.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>net30</fullName>
        <label>30 NET</label>
    </customValue>
    <customValue>
        <fullName>45 NET</fullName>
    </customValue>
    <customValue>
        <fullName>Check(Net 10)</fullName>
    </customValue>
    <customValue>
        <fullName>Credit Card</fullName>
        <label>0 NET</label>
    </customValue>
    <customValue>
        <fullName>Insurance 30</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance 45</fullName>
    </customValue>
    <customValue>
        <fullName>No Charge</fullName>
    </customValue>
    <customValue>
        <fullName>net0</fullName>
        <label>Credit Card</label>
    </customValue>
    <customValue>
        <fullName>net60</fullName>
        <label>60 NET</label>
    </customValue>
    <customValue>
        <fullName>net90</fullName>
        <label>90 NET</label>
    </customValue>
    <customValue>
        <fullName>net-1</fullName>
        <label>Prepaid</label>
    </customValue>
    <masterLabel>Payment Term</masterLabel>
</GlobalValueSet>

src/classes/ClsCHOpportunityTriggerHandler.cls
/*******************************************************************************************************************************************
@Author        : Kumar Navneet
@Date Created    : 20/09/2019
@Description    : Class used to process Opportunity records to create Schedule Shipment and its line item entries as per the product schedule
********************************************************************************************************************************************/
public class ClsCHOpportunityTriggerHandler
{
    static Set<Id> opptyIdsToProcess = new Set<Id>();//Set of Opportunities Ids to be processed
    
    //Method checks if the Opportunity product has a schedule and then it will record the schedule shipments relating to Opportunity
    public static String processOpportunityForScheduleShipments(Map<Id, Opportunity> newTriggerOpportunities, Map<Id, Opportunity> oldTriggerOpportunities)
    {
        
        String returnMsg = 'OK';
        // Avoid Recursion - If this logic was executed during the same context 
        if(ClsOpportunityTriggerStaticClass.isExecuting)
            return returnMsg;
        ClsOpportunityTriggerStaticClass.isExecuting = true;
        
        system.debug('----Entering Process to find Opportunity for processing');
        for(Opportunity newOppty : newTriggerOpportunities.values())
        {
            Opportunity oldOppty = oldTriggerOpportunities.get(newOppty.Id);
            if(((oldOppty.StageName != newOppty.StageName) && newOppty.StageName == 'Order Fulfillment'))
            {
                opptyIdsToProcess.add(newOppty.Id);
            }
        }       
        //Process opportunity records for scheduled shipments
        if(opptyIdsToProcess != null) returnMsg = processOpportunityRecords();
        return returnMsg;
    }
    
    public static String processOpportunityRecords()
    {
        system.debug('----Entering Process to Process Opportunity records');
        Map<Id, Opportunity> opptyMap = new Map<Id, Opportunity>();//Create a map between Opportunity Id and Opportunity record
        Map<Id, List<OpportunityLineItem>> oppToLinesMap = new Map<Id, List<OpportunityLineItem>>();//Map holds the reference between an Opp Id to its lines
        List<Order> ordersToAdd = new List<Order>();//Order records to be added
        List<OrderItem> orderItemsToAdd = new List<OrderItem>();//Order item records to be added
        List<SSIP_Rule__c> ssipRuleList = new List<SSIP_Rule__c>();//SSIP Rules List will be used to create the SSIP Rule
        Set<Id> accountIdSet = new Set<Id>();//Set of account ids to get the bill to and ship to addr information
        
        Id orderRecTypeId = Schema.SObjectType.Order.getRecordTypeInfosByName().get('CH Sales Order').getRecordTypeId();
        Id ssipRuleRecTypeId = Schema.SObjectType.SSIP_Rule__c.getRecordTypeInfosByName().get('CH SSIP Rule').getRecordTypeId();
        
        //Get the Opportunity and line details to process further
        for(Opportunity oppty : [SELECT Id, AccountId, Pricebook2Id, Type, Payment_Terms__c, (Select OpportunityId, PricebookEntryId, PriceBookEntry.PriceBook2Id, PriceBookEntry.Product2Id, PriceBookEntry.Product2.Name, Quantity, 
                                                                            UnitPrice, Repeat_after_in_Days__c, Repeat_Quantity__c, Repeat_End_Date__c, First_Repeat_Order_Lead_Days__c FROM OpportunityLineItems) FROM Opportunity WHERE Id IN : opptyIdsToProcess])
        {
            opptyMap.put(oppty.Id, oppty);
            oppToLinesMap.put(oppty.Id, oppty.OpportunityLineItems);
            accountIdSet.add(oppty.AccountId);
        }
        
        //Create a map between Account Id and Address (BillTo and ShipTo) objects
        Map<Id, Address__c> accntIdToBillToAddressMap = new Map<Id, Address__c>();
        Map<Id, Address__c> accntIdToShipToAddressMap = new Map<Id, Address__c>();
        if(opptyMap.size() > 0)
        {
            for(Address__c addr : [SELECT Id, Account__c, Address_Line_1__c, City__c, State__c, Postal_Code__c, Country__c, Type__c FROM Address__c WHERE Primary_Flag__c = TRUE AND Account__c IN : accountIdSet]) 
            {
                if(addr.Type__c == 'Bill To')
                    accntIdToBillToAddressMap.put(addr.Account__c, addr);
                else if(addr.Type__c == 'Ship To')
                    accntIdToShipToAddressMap.put(addr.Account__c, addr);
            }
        }
        
        //For each opportunity create entries for Order 
        for(Opportunity currOppty : opptyMap.values())
        {
            List<OpportunityLineItem> oppLinesList = oppToLinesMap.get(currOppty.Id);//Get all the opportnity lines tied to the current Opportunity
            String externalIdValue = currOppty.Id + '|' + system.today();
            String accountId = currOppty.AccountId;                
            Address__c billToAddress = accountId != null ? accntIdToBillToAddressMap.get(accountId) : null;
            Address__c shipToAddress = accountId != null ? accntIdToShipToAddressMap.get(accountId) : null;
            //Prepare Order Header record entry
            Order orderToBeCreated = new Order();
            orderToBeCreated.AccountId = accountId;               
            orderToBeCreated.Customer_Bill_To_Address__c = billToAddress.Id;
            orderToBeCreated.Customer_Ship_To_Address__c = shipToAddress.Id; 
            orderToBeCreated.BillingStreet = billToAddress.Address_Line_1__c;
            orderToBeCreated.BillingCity = billToAddress.City__c;
            orderToBeCreated.BillingState = billToAddress.State__c;
            orderToBeCreated.BillingPostalCode = billToAddress.Postal_Code__c;
            orderToBeCreated.BillingCountry = billToAddress.Country__c;
            orderToBeCreated.ShippingStreet = shipToAddress.Address_Line_1__c;
            orderToBeCreated.ShippingCity = shipToAddress.City__c;
            orderToBeCreated.ShippingState = shipToAddress.State__c;
            orderToBeCreated.ShippingPostalCode = shipToAddress.Postal_Code__c;
            orderToBeCreated.ShippingCountry = shipToAddress.Country__c;
            orderToBeCreated.OpportunityId = currOppty.Id;
            if(currOppty.Payment_Terms__c != null)
            orderToBeCreated.Payment_Terms__c = currOppty.Payment_Terms__c ;
            orderToBeCreated.Status = 'Draft';
            orderToBeCreated.Price_Book__c = currOppty.Pricebook2Id;
            orderToBeCreated.EffectiveDate = system.today(); 
            orderToBeCreated.External_Id__c = externalIdValue;
            orderToBeCreated.Type = 'CH STANDARD';
            orderToBeCreated.CurrencyIsoCode = 'CHF';
            orderToBeCreated.RecordTypeId = orderRecTypeId;
            //Add the order to the list that will be used to create the Orders
            ordersToAdd.add(orderToBeCreated);
            //Prepare the order reference
            Order orderRef = new Order(External_Id__c = externalIdValue);
            //Associate the Order referece to the Opportunity		
            currOppty.Associated_Order__r = orderRef;
            //Create the Order lines corresponding to the Opportunity lines
            for(OpportunityLineItem oli : oppLinesList)
            {
                //Make entries based on what is there on the Opportunity and not overwrite with book entries
                OrderItem orderItemToBeCreated = new OrderItem ();
                orderItemToBeCreated.Order = orderRef;
                orderItemToBeCreated.PricebookEntryId = oli.PricebookEntryId;
                orderItemToBeCreated.Quantity = oli.Quantity;
                orderItemToBeCreated.UnitPrice = oli.UnitPrice;
                orderItemsToAdd.add(orderItemToBeCreated);
                //If the Opp lines have the SSIP details filled in then the SSIP Rules should be created for each Opportunity lines
                if((oli.Repeat_Quantity__c != null && oli.Repeat_Quantity__c > 0 && oli.Repeat_after_in_Days__c != null && oli.Repeat_after_in_Days__c > 0))
                {
                    //Make entries to SSIP Rule when the Repeat fields are filled in
                    SSIP_Rule__c ssipRuleToBeCreated = new SSIP_Rule__c();
                    ssipRuleToBeCreated.Account__c = accountId;
                    ssipRuleToBeCreated.Country__c = 'Switzerland';
                    ssipRuleToBeCreated.CurrencyIsoCode = 'CHF';
                    ssipRuleToBeCreated.Frequency_In_Days__c = oli.Repeat_after_in_Days__c;
                    ssipRuleToBeCreated.Payment_Term__c = 'net30';
                    ssipRuleToBeCreated.Price_Book__c = oli.PriceBookEntry.PriceBook2Id;
                    ssipRuleToBeCreated.Product__c = oli.PriceBookEntry.Product2Id;
                    ssipRuleToBeCreated.Product_Name__c = oli.PriceBookEntry.Product2.Name;                    
                    ssipRuleToBeCreated.First_Order__r = orderRef;
                    ssipRuleToBeCreated.Quantity__c = oli.Repeat_Quantity__c;
                    ssipRuleToBeCreated.RecordTypeId = ssipRuleRecTypeId;
                    ssipRuleToBeCreated.Rule_Start_Date__c = system.date.today();
                    ssipRuleToBeCreated.Rule_End_Date__c = oli.Repeat_End_Date__c;
                    ssipRuleToBeCreated.PriceBookEntryId__c = oli.PricebookEntryId;
                    ssipRuleToBeCreated.First_Repeat_Order_Lead_Days__c = oli.First_Repeat_Order_Lead_Days__c;
                    ssipRuleList.add(ssipRuleToBeCreated);
                }
            }
            
        }
        //Insert Order Records
        if (ordersToAdd.size() > 0) {
            string result;
            try { 
                result= 'success';
                insert ordersToAdd;
            } catch (DmlException de) {
                if(de.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION')) result = de.getMessage().substringAfter('FIELD_CUSTOM_VALIDATION_EXCEPTION,').substringBefore('[');
                return result;
            }
        }
        
        //Insert Order lines Records
        if (orderItemsToAdd.size() > 0) {
            string result;
            try { 
                result= 'success';
                insert orderItemsToAdd;
            } catch (DmlException de) {
                if(de.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION')) result = de.getMessage().substringAfter('FIELD_CUSTOM_VALIDATION_EXCEPTION,').substringBefore('[');
                return result;
            }
        }
        
        //Update Opportunity records with Order reference
        if (ordersToAdd.size() > 0) {
            string result;
            try { update opptyMap.values();
                } catch (DmlException de) {
                    if(de.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION')) result = de.getMessage().substringAfter('FIELD_CUSTOM_VALIDATION_EXCEPTION,').substringBefore('[');
                    return result;
                }
        }
        //Insert SSIP Rule Records
        if (ssipRuleList.size() > 0) {
            string result;
            try { insert ssipRuleList;
                } catch (DmlException de) {
                    if(de.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION')) result = de.getMessage().substringAfter('FIELD_CUSTOM_VALIDATION_EXCEPTION,').substringBefore('[');
                    if(de.getMessage().contains('DUPLICATES_DETECTED')) result = 'SSIP Rule for the same Product already exist, only one rule can be active for a Product.';
                    return result;
                }
        }
        
        /* if(ssipRuleList.size() > 0){
string result;
System.debug('*****Entered ssip processing');
Database.SaveResult[] srList = Database.insert(ssipRuleList, false);
for (Database.SaveResult sr : srList) {
if (!sr.isSuccess()){
System.debug('*****Entered ssip processing - Failure');
// Insertion failed due to duplicate detected
for(Database.Error duplicateError : sr.getErrors()){
if (duplicateError instanceof Database.DuplicateError) {
System.debug('*****Entered ssip processing - Duplicate error');
Datacloud.DuplicateResult duplicateResult = 
((Database.DuplicateError)duplicateError).getDuplicateResult();
System.debug('*****Entered ssip processing - duplicateResult.getErrorMessage()');
System.debug('*****Duplicate records have been detected by ' + 
duplicateResult.getDuplicateRule());
System.debug(duplicateResult.getErrorMessage());
result = duplicateResult.getErrorMessage();
}
}
}
}
return result;
}*/
        return 'OK';
    }
    
    //This method will add in the SSIP Opportunity Products upon Subscription Opportunity Insert
    public static void processSubscriptionOpportunityProductCreation(List<Opportunity> newOppList){
        //Instantiating the collections
        List<Opportunity> subscriptionOppList = new List<Opportunity>();
        List<OpportunityLineitem> oppItemsToInsertList = new List<OpportunityLineitem>();
        List<Id> chPricebookList = new List<Id>();
        Map<Id, List<PricebookEntry>> chPBEMap = new Map<Id, List<PricebookEntry>>();
        List<PricebookEntry> chPricebookEntList = new List<PricebookEntry>();
        
        //Gather the Opps that are part of the Subscription
        for(Opportunity op :newOppList){
            if(op.Type == 'Subscription'){
                subscriptionOppList.add(op); 
                chPricebookList.add(op.Pricebook2Id);  
            }				
        }
        //Proceed if there are any subscription opps to be processed
        if(!subscriptionOppList.isEmpty()){
                        
            //Prepare the map between the Subscription Pricebook and the Pricebook entries	
            for(PricebookEntry pbe : [SELECT ID, Pricebook2Id, SSIP_Periodic_Order_Quantity__c, SSIP_Next_Order_In_Days__c, UnitPrice, First_Repeat_Order_Lead_Days__c FROM PricebookEntry WHERE Pricebook2Id In :chPricebookList AND IsActive = True AND Productcode != 'DEX-SHIP-01'])
            {
                if(chPBEMap.containsKey(pbe.Pricebook2Id)){
                    List<PricebookEntry> pbeList = chPBEMap.get(pbe.Pricebook2Id);
                    pbeList.add(pbe);
                    chPBEMap.put(pbe.Pricebook2Id, pbeList);
                }
                else
                    chPBEMap.put(pbe.Pricebook2Id, new List<PricebookEntry> {pbe});
            }
            //If there are PBEs then go ahead and create the lines
            if(!chPBEMap.isEmpty())
            {
                //For every Subscription Opp insert the Subscription SKUs based on the Pricelistentry tied to the Subscription Pricebook
                for(Opportunity opo :subscriptionOppList){     
                    List<PricebookEntry> oppPBEs = chPBEMap.get(opo.Pricebook2Id);
                    for(PricebookEntry insertPBE : oppPBEs)
                    {
                        OpportunityLineitem ol = new OpportunityLineitem();
                        ol.opportunityID = opo.Id;
                        ol.PricebookEntryId = insertPBE.Id;
                        ol.Quantity = insertPBE.SSIP_Periodic_Order_Quantity__c;
                        ol.UnitPrice = insertPBE.UnitPrice;
                        ol.Repeat_after_in_Days__c = insertPBE.SSIP_Next_Order_In_Days__c;
                        ol.Repeat_Quantity__c = insertPBE.SSIP_Periodic_Order_Quantity__c;
                        ol.First_Repeat_Order_Lead_Days__c = insertPBE.First_Repeat_Order_Lead_Days__c;
                        ol.Product_Added_By_Admin__c = true;
                        oppItemsToInsertList.add(Ol);
                    }
                }
            }
            //Insert Opp Lines
            if(!oppItemsToInsertList.isEmpty())
                insert oppItemsToInsertList;
        }
    }
}