src/objects/Address__c.object
<CustomObject>
    <description>Created this custom object to track Address information.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Straße, Hausnummer</inlineHelpText>
        <label>Address Line 1</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>City</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>System_Of_Origin_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>System Of Origin ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Of_Origin__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>System Of Origin</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bill To</fullName>
                </value>
                <value>
                    <fullName>Ship To</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CRM_Order_Event_V1__e.object
<CustomObject>
    <description>Platform event invoked from Kafka to Salesforce upon Order inserts and updates</description>
    <fields>
        <fullName>accountID__c</fullName>
        <label>accountID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>action__c</fullName>
        <label>action</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>author__c</fullName>
        <label>author</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>bankID__c</fullName>
        <label>bankID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>billingAddress1__c</fullName>
        <label>billingAddress1</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>billingAddress2__c</fullName>
        <label>billingAddress2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>billingAddress3__c</fullName>
        <label>billingAddress3</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>billingAddressAccountID__c</fullName>
        <label>billingAddressAccountID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>billingAddressBusinessName__c</fullName>
        <label>billingAddressBusinessName</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>billingAddressCity__c</fullName>
        <label>billingAddressCity</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>billingAddressCountryCode__c</fullName>
        <label>billingAddressCountryCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>billingAddressCountry__c</fullName>
        <label>billingAddressCountry</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>billingAddressFirstName__c</fullName>
        <label>billingAddressFirstName</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>billingAddressID__c</fullName>
        <label>billingAddressID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>billingAddressIsLocked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>billingAddressIsLocked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>billingAddressIsPrimary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag tracks the billing address primary.</description>
        <label>billingAddressIsPrimary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>billingAddressLastName__c</fullName>
        <label>billingAddressLastName</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>billingAddressPostalCode__c</fullName>
        <label>billingAddressPostalCode</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>billingAddressPrimaryPhone__c</fullName>
        <label>billingAddressPrimaryPhone</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>billingAddressStateProvince__c</fullName>
        <label>billingAddressStateProvince</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>billingTaxExempt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>billingTaxExempt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>billingTaxRegistrationNumber__c</fullName>
        <label>billingTaxRegistrationNumber</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>creditCardAuthorizationCode__c</fullName>
        <label>creditCardAuthorizationCode</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>creditCardExpirationDate__c</fullName>
        <label>creditCardExpirationDate</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>creditCardID__c</fullName>
        <label>creditCardID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>creditCardToken__c</fullName>
        <label>creditCardToken</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>creditCardTransactionID__c</fullName>
        <label>creditCardTransactionID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>creditCardType__c</fullName>
        <label>creditCardType</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>entityType__c</fullName>
        <label>entityType</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eventDate__c</fullName>
        <label>eventDate</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eventSourceID__c</fullName>
        <label>eventSourceID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eventSource__c</fullName>
        <defaultValue>&apos;SFDC&apos;</defaultValue>
        <label>eventSource</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>invoiceDate__c</fullName>
        <label>invoiceDate</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>invoiceNumber__c</fullName>
        <label>invoiceNumber</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isSignatureRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isSignatureRequired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>metadata__c</fullName>
        <label>metadata</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>operation__c</fullName>
        <label>operation</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>orderNumber__c</fullName>
        <label>orderNumber</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>orderType__c</fullName>
        <label>orderType</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>parentSystemOfOriginID__c</fullName>
        <label>parentSystemOfOriginID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>paymentMethod__c</fullName>
        <label>paymentMethod</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>paymentTerm__c</fullName>
        <label>paymentTerm</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>poNumber__c</fullName>
        <label>poNumber</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>scheduledShipDate__c</fullName>
        <label>scheduledShipDate</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingAddress1__c</fullName>
        <label>shippingAddress1</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingAddress2__c</fullName>
        <label>shippingAddress2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingAddress3__c</fullName>
        <label>shippingAddress3</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingAddressAccountID__c</fullName>
        <label>shippingAddressAccountID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingAddressBusinessName__c</fullName>
        <label>shippingAddressBusinessName</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingAddressCity__c</fullName>
        <label>shippingAddressCity</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingAddressCountryCode__c</fullName>
        <label>shippingAddressCountryCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingAddressCountry__c</fullName>
        <label>shippingAddressCountry</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingAddressFirstName__c</fullName>
        <label>shippingAddressFirstName</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingAddressID__c</fullName>
        <label>shippingAddressID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingAddressIsLocked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>shippingAddressIsLocked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>shippingAddressIsPrimary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag tracks the shipping address primary</description>
        <label>shippingAddressIsPrimary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>shippingAddressLastName__c</fullName>
        <label>shippingAddressLastName</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingAddressPostalCode__c</fullName>
        <label>shippingAddressPostalCode</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingAddressPrimaryPhone__c</fullName>
        <label>shippingAddressPrimaryPhone</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingAddressStateProvince__c</fullName>
        <label>shippingAddressStateProvince</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingAmount__c</fullName>
        <label>shippingAmount</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>shippingEmail__c</fullName>
        <label>shippingEmail</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingMethod__c</fullName>
        <label>shippingMethod</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingNotes__c</fullName>
        <label>shippingNotes</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingTaxExempt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>shippingTaxExempt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>shippingTaxRegistrationNumber__c</fullName>
        <label>shippingTaxRegistrationNumber</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>stage__c</fullName>
        <label>stage</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>statusMessage__c</fullName>
        <label>statusMessage</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>systemOfOriginID__c</fullName>
        <label>systemOfOriginID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>systemOfOrigin__c</fullName>
        <label>systemOfOrigin</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>version__c</fullName>
        <label>version</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>CRM Order Event V1 - In</label>
    <pluralLabel>CRM_Order_Events_V1 - In</pluralLabel>
</CustomObject>

src/globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Liechtenstein</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <customValue>
        <fullName>Ireland</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Chile</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Spain</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong</fullName>
    </customValue>
    <customValue>
        <fullName>Hungary</fullName>
    </customValue>
    <customValue>
        <fullName>Israel</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Jordan</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <customValue>
        <fullName>Korea</fullName>
    </customValue>
    <customValue>
        <fullName>Kuwait</fullName>
    </customValue>
    <customValue>
        <fullName>Lebanon</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>Norway</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>Oman</fullName>
    </customValue>
    <customValue>
        <fullName>Poland</fullName>
    </customValue>
    <description>Global picklist will be used in various places</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

src/classes/PEClsHandleOrderEvents_V11_Test.cls
@isTest()
private class PEClsHandleOrderEvents_V11_Test {
	@testSetup static void setup() {
        Map<String, String> mapPriceBook = ClsTestDataFactory.createCPB(new List<String>{'DE Netto-Preis Cash', 'DE Return Replace', 'Barmer'}, 'CHF');
        Map<String, Id> mapProduct = ClsTestDataFactory.createProducts(new List<String>{'Product-01', 'Product-02', 'Product-03', 'DEX-SHIP-01'});
        Map<Id, Decimal> productIdToPriceMap = new Map<Id, Decimal>{mapProduct.values()[0] => 10, mapProduct.values()[1] => 10, mapProduct.values()[2] => 10 };
        Map<Id, Id> mapPBE = ClsTestDataFactory.CreateCPBEntries(productIdToPriceMap, mapPriceBook.get('DE Netto-Preis Cash'), 'CHF');
        Account objAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'DE Consumer', 'Germany')[0];
    }
    
    @isTest private static void test(){
		Id rtId = Schema.SObjectType.Order.getRecordTypeInfosByName().get('CH Sales Order').getRecordTypeId();        
        Account payorAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'DE Payor', 'Germany')[0];
        List<Account> lstAccount = [SELECT Id, Name FROM Account];
        List<PEClsHandleOrderEvents.OrderLineItem> lstOLI = new List<PEClsHandleOrderEvents.OrderLineItem>();
        for(Product2 product : [SELECT Id, Name FROM Product2]){
            lstOLI.add(new PEClsHandleOrderEvents.OrderLineItem(product.Id, 1, 10));
        }
        List<Product2> lstProduct = [SELECT Id, Name FROM Product2];
         //Query for the Address record types
        List<RecordType> rtypes = [Select Name, Id From RecordType 
                               where sObjectType='Address__c' and isActive=true];
    
        //Create a map between the Record Type Name and Id 
        Map<String,String> addRecordTypes = new Map<String,String>();
        for(RecordType rt: rtypes) {
        addRecordTypes.put(rt.Name,rt.Id);
        }     	
        String recordTypeId = addRecordTypes.get('DE Address');
        List<Address__c> lstAddress = new List<Address__c>{
                                                            new Address__c(Account__c = lstAccount[0].Id,RecordTypeId = recordTypeId,Type__c = 'Bill To', Country__c = 'Germany', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = lstAccount[0].Id,RecordTypeId = recordTypeId,Type__c = 'Ship To',Country__c = 'Germany', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = payorAccount.Id,RecordTypeId = recordTypeId,Type__c = 'Bill To', Country__c = 'Germany', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = payorAccount.Id,RecordTypeId = recordTypeId,Type__c = 'Ship To',Country__c = 'Germany', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                                                          };
        insert lstAddress;
        List<PricebookEntry> lstPBE = [SELECT Id, Pricebook2Id FROM PricebookEntry WHERE Pricebook2.Name = 'DE Netto-Preis Cash'];
        Order objOrder = new Order(AccountId = lstAccount[0].Id, EffectiveDate = Date.today(), Status = 'Draft', Type = 'CH STANDARD', Payor__c = payorAccount.Id, Pricebook2Id = lstPBE[0].Pricebook2Id,
                                   RecordTypeId = rtId, CurrencyISOCode = 'CHF', Tax_Exempt__c = true);
        insert objOrder;
        List<OrderItem> lstOrderItem = new List<OrderItem>();
        for(PricebookEntry pbe : lstPBE){
            lstOrderItem.add(new OrderItem(PricebookEntryId = pbe.Id, OrderId = objOrder.Id, Quantity = 1, UnitPrice = 10));
        }
        insert lstOrderItem;
        List<Order> lstOrder = [SELECT Id, OrderNumber FROM Order];
        
        update new Order(id=lstOrder[0].id, Status='Activated');
        
        CRM_Order_Event_V1__e oEvent = new CRM_Order_Event_V1__e(version__c = '3.0',orderType__c = 'Sales_Order', operation__c = 'update',stage__c = 'pending',eventSource__c = 'OMS',
                                                           		 systemOfOrigin__c = '12345', systemOfOriginID__c = 'abcdefg',entityType__c = 'order',
                                                           		 orderNumber__c = lstOrder[0].OrderNumber, Status__c = 'booked');
        System.debug('====oEvent===='+JSON.serialize(oEvent));
        Test.startTest();
        	ClsOrderHandlerStatic.executeOrderEventTriggerv11 = true;
            Database.SaveResult sr = EventBus.publish(oEvent);
        Test.stopTest();
    }
    @isTest private static void test1(){
		Id rtId = Schema.SObjectType.Order.getRecordTypeInfosByName().get('CH Sales Order').getRecordTypeId();        
        Account payorAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'DE Payor', 'Germany')[0]; 
        List<Account> lstAccount = [SELECT Id, Name FROM Account];
        List<PEClsHandleOrderEvents.OrderLineItem> lstOLI = new List<PEClsHandleOrderEvents.OrderLineItem>();
        for(Product2 product : [SELECT Id, Name FROM Product2]){
            lstOLI.add(new PEClsHandleOrderEvents.OrderLineItem(product.Id, 1, 10));
        }
        List<Product2> lstProduct = [SELECT Id, Name FROM Product2];
         //Query for the Address record types
        List<RecordType> rtypes = [Select Name, Id From RecordType 
                               where sObjectType='Address__c' and isActive=true];
    
        //Create a map between the Record Type Name and Id 
        Map<String,String> addRecordTypes = new Map<String,String>();
        for(RecordType rt: rtypes) {
        addRecordTypes.put(rt.Name,rt.Id);
        }     	
        String recordTypeId = addRecordTypes.get('DE Address');
        List<Address__c> lstAddress = new List<Address__c>{
                                                            new Address__c(Account__c = lstAccount[0].Id,RecordTypeId = recordTypeId,Type__c = 'Bill To', Country__c = 'Germany', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = lstAccount[0].Id,RecordTypeId = recordTypeId,Type__c = 'Ship To',Country__c = 'Germany', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = payorAccount.Id,RecordTypeId = recordTypeId,Type__c = 'Bill To', Country__c = 'Germany', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = payorAccount.Id,RecordTypeId = recordTypeId,Type__c = 'Ship To',Country__c = 'Germany', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                                                          };
        insert lstAddress;
        List<PricebookEntry> lstPBE = [SELECT Id, Pricebook2Id FROM PricebookEntry WHERE Pricebook2.Name = 'DE Netto-Preis Cash'];
        Order objOrder = new Order(AccountId = lstAccount[0].Id, EffectiveDate = Date.today(), Status = 'Draft', Type = 'CH STANDARD',
                                   Payor__c = payorAccount.Id, Pricebook2Id = lstPBE[0].Pricebook2Id,
                                   RecordTypeId = rtId, CurrencyISOCode = 'CHF');
        
        insert objOrder;
        List<OrderItem> lstOrderItem = new List<OrderItem>();
        for(PricebookEntry pbe : lstPBE){
            lstOrderItem.add(new OrderItem(PricebookEntryId = pbe.Id, OrderId = objOrder.Id, Quantity = 1, UnitPrice = 10));
        }
        insert lstOrderItem;
        List<Order> lstOrder = [SELECT Id, OrderNumber FROM Order];
        
        CRM_Order_Event_V1__e oEvent = new CRM_Order_Event_V1__e(version__c = '3.0',orderType__c = 'Sales_Order', operation__c = 'create',stage__c = 'confirmed',eventSource__c = 'OMS',
                                                           		 systemOfOrigin__c = 'crm', systemOfOriginID__c = 'abcdefg',entityType__c = 'order',
                                                           		 orderNumber__c = lstOrder[0].OrderNumber, Status__c = 'Activated');
        System.debug('====oEvent===='+JSON.serialize(oEvent));
        Test.startTest();
        	ClsOrderHandlerStatic.executeOrderEventTriggerv11 = true;
            Database.SaveResult sr = EventBus.publish(oEvent);
        Test.stopTest();
    }
    @isTest private static void createTest(){
        Map<String, String> mapPriceBook = ClsTestDataFactory.createCPB(new List<String>{'UK G6 SUBSCRIPTION 12MOS'}, 'GBP');
        Map<String, Id> mapProduct = ClsTestDataFactory.createProducts(new List<String>{'MTLYCHARGE', 'Transmitter', 'Sensor'});
        Map<Id, Decimal> productIdToPriceMap = new Map<Id, Decimal>{mapProduct.values()[0] => 159, mapProduct.values()[1] => 0, mapProduct.values()[2] => 0 };
        Map<Id, Id> mapPBE = ClsTestDataFactory.CreateCPBEntries(productIdToPriceMap, mapPriceBook.get('UK G6 SUBSCRIPTION 12MOS'), 'GBP');
        List<PriceBookEntry> pbes = [Select product2.Name, Id from PriceBookEntry where pricebook2.Name = 'UK G6 SUBSCRIPTION 12MOS'];
        for (PriceBookEntry pbe : pbes) {
            if (pbe.product2.name == 'MTLYCHARGE') {
                pbe.First_Order_Variation_Qty__c = 0;
                pbe.First_Repeat_Order_Lead_Days__c = 0;
                pbe.Number_of_Repeat_Orders__c = 0;
                pbe.SSIP_Next_Order_In_Days__c = 30;
                pbe.SSIP_Periodic_Order_Quantity__c = 1;
            }
            if (pbe.product2.name == 'Transmitter') {
                pbe.First_Order_Variation_Qty__c = 0;
                pbe.First_Repeat_Order_Lead_Days__c = 10;
                pbe.Number_of_Repeat_Orders__c = 0;
                pbe.SSIP_Next_Order_In_Days__c = 90;
                pbe.SSIP_Periodic_Order_Quantity__c = 1;
            }
            if (pbe.product2.name == 'Sensor') {
                pbe.First_Order_Variation_Qty__c = 0;
                pbe.First_Repeat_Order_Lead_Days__c = 10;
                pbe.Number_of_Repeat_Orders__c = 0;
                pbe.SSIP_Next_Order_In_Days__c = 90;
                pbe.SSIP_Periodic_Order_Quantity__c = 3;
            }
        }
        update pbes;    
            
        Account consumerAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'GB Consumer', 'United Kingdom')[0];
        CRM_Order_Event_V1__e oEvent = new CRM_Order_Event_V1__e (entityType__c='order',
            eventDate__c='2020-04-06T17:09:52.316Z',
            eventSource__c='ecom',
            eventSourceID__c='UK20000614',
            stage__c='pending',
            operation__c='create',
            systemOfOrigin__c='ecom',
            systemOfOriginID__c='UK20000614',
            parentSystemOfOriginID__c='UK00000613',
            version__c='3.0',
            author__c='null',
            metadata__c='null',
            accountID__c=consumerAccount.id,
            orderNumber__c='UK10000614',
            orderType__c='GBSTANDARD',
            status__c='booked',
            statusMessage__c='null',
            action__c='null',
            invoiceNumber__c='null',
            poNumber__c='null',
            invoiceDate__c='null',
            isSignatureRequired__c=null,
            scheduledShipDate__c='null',
            shippingAmount__c=0.0,
            shippingMethod__c='DPD Local|Ground|0|BS1',
            shippingNotes__c='null',
            shippingEmail__c='zSUBtestUK14@mailinator.com',
            shippingAddressID__c='null',
            shippingAddressAccountID__c=consumerAccount.id,
            shippingAddressIsLocked__c=false,
            shippingAddressIsPrimary__c=null,
            shippingAddressBusinessName__c='null',
            shippingAddressFirstName__c='SUB14',
            shippingAddressLastName__c='Test',
            shippingAddress1__c='451 Alexandra Avenue',
            shippingAddress2__c='null',
            shippingAddress3__c='null',
            shippingAddressCity__c='Harrow',
            shippingAddressStateProvince__c='null',
            shippingAddressPostalCode__c='HA2 9SE',
            shippingAddressCountryCode__c='GB',
            shippingAddressCountry__c='null',
            shippingAddressPrimaryPhone__c='22233334444',
            shippingTaxRegistrationNumber__c='null',
            shippingTaxExempt__c=false,
            billingAddressID__c='null',
            billingAddressAccountID__c=consumerAccount.id,
            billingAddressIsLocked__c=null,
            billingAddressIsPrimary__c=null,
            billingAddressBusinessName__c='null',
            billingAddressFirstName__c='SUB14',
            billingAddressLastName__c='Test',
            billingAddress1__c='451 Alexandra Avenue',
            billingAddress2__c='null',
            billingAddress3__c='null',
            billingAddressCity__c='Harrow',
            billingAddressStateProvince__c='null',
            billingAddressPostalCode__c='HA2 9SE',
            billingAddressCountryCode__c='GB',
            billingAddressCountry__c='null',
            billingAddressPrimaryPhone__c='22233334444',
            billingTaxRegistrationNumber__c='null',
            billingTaxExempt__c=false,
            paymentMethod__c='null',
            paymentTerm__c='net0',
            creditCardID__c='null',
            creditCardType__c='Visa',
            creditCardExpirationDate__c='07/2025',
            creditCardToken__c='7010000000055671111',
            creditCardAuthorizationCode__c='831000',
            creditCardTransactionID__c='5861928563596251804009',
            bankID__c='null',
            bankName__c='null',
            branchName__c='null',
            bic__c='null',
            iban__c='null',
            bankAccountName__c='null',
            bankAccountNumber__c='null',
            bankCurrencyCode__c='null',
            bankCountryCode__c='null',
            currencyCode__c='null',
            rgaNumber__c='null',
            warehouse__c='HLUK',
            pricebookName__c='UK G6 SUBSCRIPTION 12MOS',
            totalAmount__c=190.8,
            deliveryTerm__c='null',
            tax__c='null');
        Test.startTest();
        	ClsOrderHandlerStatic.executeOrderEventTriggerv11 = true;
        	EventBus.publish(oEvent);
        Test.stopTest();
            
    }
    @isTest private static void createTest2(){
        Map<String, String> mapPriceBook = ClsTestDataFactory.createCPB(new List<String>{'UK Cash List Price'}, 'GBP');
        Map<String, Id> mapProduct = ClsTestDataFactory.createProducts(new List<String>{'MT22754', 'DEX-SHIP-01-01'});
        Map<Id, Decimal> productIdToPriceMap = new Map<Id, Decimal>{mapProduct.values()[0] => 12.59, mapProduct.values()[1] => 1};
        Map<Id, Id> mapPBE = ClsTestDataFactory.CreateCPBEntries(productIdToPriceMap, mapPriceBook.get('UK Cash List Price'), 'GBP');
        Account consumerAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'GB Consumer', 'United Kingdom')[0];
        CRM_Order_Event_V1__e oEvent = new CRM_Order_Event_V1__e (  entityType__c='order',
           eventDate__c='2020-04-01T21:45:02.198Z',
           eventSource__c='OMS',
           eventSourceID__c='50001155', 
           stage__c='pending',
           operation__c='update',
           systemOfOrigin__c='OMS',
           systemOfOriginID__c='50001155',
           parentSystemOfOriginID__c=null,
           version__c='3.0',
           author__c='null',
           metadata__c='null',
           accountID__c=consumerAccount.id,
           orderNumber__c='D8UK00001155',
           orderType__c='GB STANDARD',
           status__c='booked',
           statusMessage__c='null',
           action__c='null',
           invoiceNumber__c='null',
           poNumber__c='null',
           invoiceDate__c='null',
           isSignatureRequired__c=true,
           scheduledShipDate__c='null',
           shippingAmount__c=11.38,
           shippingMethod__c='DPD Local|Ground|1138|BSN',
           shippingNotes__c='true',
           shippingEmail__c='false',
           shippingAddressID__c='null',
           shippingAddressAccountID__c=consumerAccount.id,
           shippingAddressIsLocked__c=false,
           shippingAddressIsPrimary__c=null,
           shippingAddressBusinessName__c='null',
           shippingAddressFirstName__c='Josh',
           shippingAddressLastName__c='George',
           shippingAddress1__c='2 Valleywood Dr',
           shippingAddress2__c='null',
           shippingAddress3__c='null',
           shippingAddressCity__c='Markham',
           shippingAddressStateProvince__c='null',
           shippingAddressPostalCode__c='A11 1AA',
           shippingAddressCountryCode__c='GB',
           shippingAddressCountry__c='null',
           shippingAddressPrimaryPhone__c='55555555555',
           shippingTaxRegistrationNumber__c='null',
           shippingTaxExempt__c=true,
           billingAddressID__c='null',
           billingAddressAccountID__c=consumerAccount.id,
           billingAddressIsLocked__c=null,
           billingAddressIsPrimary__c=null,
           billingAddressBusinessName__c='null',
           billingAddressFirstName__c='Josh',
           billingAddressLastName__c='George',
           billingAddress1__c='2 Valleywood Dr',
           billingAddress2__c='null',
           billingAddress3__c='null',
           billingAddressCity__c='Markham',
           billingAddressStateProvince__c='null',
           billingAddressPostalCode__c='A11 1AA',
           billingAddressCountryCode__c='GB',
           billingAddressCountry__c='null',
           billingAddressPrimaryPhone__c='55555555555',
           billingTaxRegistrationNumber__c='null',
           billingTaxExempt__c=true,
           paymentMethod__c='null',
           paymentTerm__c='net0',
           creditCardID__c='null',
           creditCardType__c='Visa',
           creditCardExpirationDate__c='08/2025',
           creditCardToken__c='7010000000055671111',
           creditCardAuthorizationCode__c='831000',
           creditCardTransactionID__c='5857775016956017804008',
           bankID__c='null',
           bankName__c='null',
           branchName__c='null',
           bic__c='null',
           iban__c='null',
           bankAccountName__c='null',
           bankAccountNumber__c='null',
           bankCurrencyCode__c='null',
           bankCountryCode__c='null',
           currencyCode__c='null',
           rgaNumber__c='null',
           warehouse__c='HLUK',
           pricebookName__c='UK Cash List Price',
           totalAmount__c=23.97,
		   Line_Items__c='[{\"itemID\":\"MT22754\",\"sku\":\"MT22754\",\"quantity\":1.0,\"price\":12.59,\"isBundle\":false,\"isBundleItem\":false,\"skuBundle\":null,\"total\":null,\"tax\":{\"source\":\"ecom\",\"type\":\"VAT\",\"amount\":0.0,\"rate\":0.0}},{\"itemID\":\"DEX-SHIP-01\",\"sku\":\"DEX-SHIP-01\",\"quantity\":11.38,\"price\":1.0,\"isBundle\":null,\"isBundleItem\":null,\"skuBundle\":null,\"total\":11.38,\"tax\":{\"source\":\"ecom\",\"type\":\"VAT\",\"amount\":0.0,\"rate\":0.0}}]',           
           tax__c='null'  
        );
        Test.startTest();
        	ClsOrderHandlerStatic.executeOrderEventTriggerv11 = true;
        	EventBus.publish(oEvent);
        Test.stopTest();
    }
    @isTest private static void createTestForConfirmed(){
        Map<String, String> mapPriceBook = ClsTestDataFactory.createCPB(new List<String>{'UK Cash List Price'}, 'GBP');
        Map<String, Id> mapProduct = ClsTestDataFactory.createProducts(new List<String>{'MT22754', 'DEX-SHIP-01-01'});
        Map<Id, Decimal> productIdToPriceMap = new Map<Id, Decimal>{mapProduct.values()[0] => 12.59, mapProduct.values()[1] => 1};
        Map<Id, Id> mapPBE = ClsTestDataFactory.CreateCPBEntries(productIdToPriceMap, mapPriceBook.get('UK Cash List Price'), 'GBP');
        Account consumerAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'GB Consumer', 'United Kingdom')[0];
        CRM_Order_Event_V1__e oEvent = new CRM_Order_Event_V1__e (  entityType__c='order',
           eventDate__c='2020-04-01T21:45:02.198Z',
           eventSource__c='OMS',
           eventSourceID__c='50001155', 
           stage__c='confirmed',
           operation__c='create',
           systemOfOrigin__c='crm',
           systemOfOriginID__c='50001155',
           parentSystemOfOriginID__c=null,
           version__c='3.0',
           author__c='null',
           metadata__c='null',
           accountID__c=consumerAccount.id,
           orderNumber__c='D8UK00001155',
           orderType__c='GB STANDARD',
           status__c='booked',
           statusMessage__c='null',
           action__c='null',
           invoiceNumber__c='null',
           poNumber__c='null',
           invoiceDate__c='null',
           isSignatureRequired__c=true,
           scheduledShipDate__c='null',
           shippingAmount__c=11.38,
           shippingMethod__c='DPD Local|Ground|1138|BSN',
           shippingNotes__c='true',
           shippingEmail__c='false',
           shippingAddressID__c='null',
           shippingAddressAccountID__c=consumerAccount.id,
           shippingAddressIsLocked__c=false,
           shippingAddressIsPrimary__c=null,
           shippingAddressBusinessName__c='null',
           shippingAddressFirstName__c='Josh',
           shippingAddressLastName__c='George',
           shippingAddress1__c='2 Valleywood Dr',
           shippingAddress2__c='null',
           shippingAddress3__c='null',
           shippingAddressCity__c='Markham',
           shippingAddressStateProvince__c='null',
           shippingAddressPostalCode__c='A11 1AA',
           shippingAddressCountryCode__c='GB',
           shippingAddressCountry__c='null',
           shippingAddressPrimaryPhone__c='55555555555',
           shippingTaxRegistrationNumber__c='null',
           shippingTaxExempt__c=true,
           billingAddressID__c='null',
           billingAddressAccountID__c=consumerAccount.id,
           billingAddressIsLocked__c=null,
           billingAddressIsPrimary__c=null,
           billingAddressBusinessName__c='null',
           billingAddressFirstName__c='Josh',
           billingAddressLastName__c='George',
           billingAddress1__c='2 Valleywood Dr',
           billingAddress2__c='null',
           billingAddress3__c='null',
           billingAddressCity__c='Markham',
           billingAddressStateProvince__c='null',
           billingAddressPostalCode__c='A11 1AA',
           billingAddressCountryCode__c='GB',
           billingAddressCountry__c='null',
           billingAddressPrimaryPhone__c='55555555555',
           billingTaxRegistrationNumber__c='null',
           billingTaxExempt__c=true,
           paymentMethod__c='null',
           paymentTerm__c='net0',
           creditCardID__c='null',
           creditCardType__c='Visa',
           creditCardExpirationDate__c='08/2025',
           creditCardToken__c='7010000000055671111',
           creditCardAuthorizationCode__c='831000',
           creditCardTransactionID__c='5857775016956017804008',
           bankID__c='null',
           bankName__c='null',
           branchName__c='null',
           bic__c='null',
           iban__c='null',
           bankAccountName__c='null',
           bankAccountNumber__c='null',
           bankCurrencyCode__c='null',
           bankCountryCode__c='null',
           currencyCode__c='null',
           rgaNumber__c='null',
           warehouse__c='HLUK',
           pricebookName__c='UK Cash List Price',
           totalAmount__c=23.97,
		   Line_Items__c='[{\"itemID\":\"MT22754\",\"sku\":\"MT22754\",\"quantity\":1.0,\"price\":12.59,\"isBundle\":false,\"isBundleItem\":false,\"skuBundle\":null,\"total\":null,\"tax\":{\"source\":\"ecom\",\"type\":\"VAT\",\"amount\":0.0,\"rate\":0.0}},{\"itemID\":\"DEX-SHIP-01\",\"sku\":\"DEX-SHIP-01\",\"quantity\":11.38,\"price\":1.0,\"isBundle\":null,\"isBundleItem\":null,\"skuBundle\":null,\"total\":11.38,\"tax\":{\"source\":\"ecom\",\"type\":\"VAT\",\"amount\":0.0,\"rate\":0.0}}]',           
           tax__c='null'  
        );
        Test.startTest();
        	ClsOrderHandlerStatic.executeOrderEventTriggerv11 = true;
        	EventBus.publish(oEvent);
        Test.stopTest();
    }
    @isTest private static void createTestForInvalidVersion(){
        Map<String, String> mapPriceBook = ClsTestDataFactory.createCPB(new List<String>{'UK Cash List Price'}, 'GBP');
        Map<String, Id> mapProduct = ClsTestDataFactory.createProducts(new List<String>{'MT22754', 'DEX-SHIP-01-01'});
        Map<Id, Decimal> productIdToPriceMap = new Map<Id, Decimal>{mapProduct.values()[0] => 12.59, mapProduct.values()[1] => 1};
        Map<Id, Id> mapPBE = ClsTestDataFactory.CreateCPBEntries(productIdToPriceMap, mapPriceBook.get('UK Cash List Price'), 'GBP');
        Account consumerAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'GB Consumer', 'United Kingdom')[0];
        CRM_Order_Event_V1__e oEvent = new CRM_Order_Event_V1__e (  entityType__c='',
           eventDate__c='2020-04-01T21:45:02.198Z',
           eventSource__c='OMS',
           eventSourceID__c='50001155', 
           stage__c='confirmed',
           operation__c='create',
           systemOfOrigin__c='crm',
           systemOfOriginID__c='50001155',
           parentSystemOfOriginID__c=null,
           version__c='33.0',
           author__c='null',
           metadata__c='null',
           accountID__c=consumerAccount.id,
           orderNumber__c='D8UK00001155',
           orderType__c='GB STANDARD',
           status__c='booked',
           statusMessage__c='null',
           action__c='null',
           invoiceNumber__c='null',
           poNumber__c='null',
           invoiceDate__c='null',
           isSignatureRequired__c=true,
           scheduledShipDate__c='null',
           shippingAmount__c=11.38,
           shippingMethod__c='DPD Local|Ground|1138|BSN',
           shippingNotes__c='true',
           shippingEmail__c='false',
           shippingAddressID__c='null',
           shippingAddressAccountID__c=consumerAccount.id,
           shippingAddressIsLocked__c=false,
           shippingAddressIsPrimary__c=null,
           shippingAddressBusinessName__c='null',
           shippingAddressFirstName__c='Josh',
           shippingAddressLastName__c='George',
           shippingAddress1__c='2 Valleywood Dr',
           shippingAddress2__c='null',
           shippingAddress3__c='null',
           shippingAddressCity__c='Markham',
           shippingAddressStateProvince__c='null',
           shippingAddressPostalCode__c='A11 1AA',
           shippingAddressCountryCode__c='GB',
           shippingAddressCountry__c='null',
           shippingAddressPrimaryPhone__c='55555555555',
           shippingTaxRegistrationNumber__c='null',
           shippingTaxExempt__c=true,
           billingAddressID__c='null',
           billingAddressAccountID__c=consumerAccount.id,
           billingAddressIsLocked__c=null,
           billingAddressIsPrimary__c=null,
           billingAddressBusinessName__c='null',
           billingAddressFirstName__c='Josh',
           billingAddressLastName__c='George',
           billingAddress1__c='2 Valleywood Dr',
           billingAddress2__c='null',
           billingAddress3__c='null',
           billingAddressCity__c='Markham',
           billingAddressStateProvince__c='null',
           billingAddressPostalCode__c='A11 1AA',
           billingAddressCountryCode__c='GB',
           billingAddressCountry__c='null',
           billingAddressPrimaryPhone__c='55555555555',
           billingTaxRegistrationNumber__c='null',
           billingTaxExempt__c=true,
           paymentMethod__c='null',
           paymentTerm__c='net0',
           creditCardID__c='null',
           creditCardType__c='Visa',
           creditCardExpirationDate__c='08/2025',
           creditCardToken__c='7010000000055671111',
           creditCardAuthorizationCode__c='831000',
           creditCardTransactionID__c='5857775016956017804008',
           bankID__c='null',
           bankName__c='null',
           branchName__c='null',
           bic__c='null',
           iban__c='null',
           bankAccountName__c='null',
           bankAccountNumber__c='null',
           bankCurrencyCode__c='null',
           bankCountryCode__c='null',
           currencyCode__c='null',
           rgaNumber__c='null',
           warehouse__c='HLUK',
           pricebookName__c='UK Cash List Price',
           totalAmount__c=23.97,
		   Line_Items__c='[{\"itemID\":\"MT22754\",\"sku\":\"MT22754\",\"quantity\":1.0,\"price\":12.59,\"isBundle\":false,\"isBundleItem\":false,\"skuBundle\":null,\"total\":null,\"tax\":{\"source\":\"ecom\",\"type\":\"VAT\",\"amount\":0.0,\"rate\":0.0}},{\"itemID\":\"DEX-SHIP-01\",\"sku\":\"DEX-SHIP-01\",\"quantity\":11.38,\"price\":1.0,\"isBundle\":null,\"isBundleItem\":null,\"skuBundle\":null,\"total\":11.38,\"tax\":{\"source\":\"ecom\",\"type\":\"VAT\",\"amount\":0.0,\"rate\":0.0}}]',           
           tax__c='null'  
        );
        Test.startTest();
        	ClsOrderHandlerStatic.executeOrderEventTriggerv11 = true;
        	EventBus.publish(oEvent);
        Test.stopTest();
    }
   
    
}