src/objects/Address__c.object
<CustomObject>
    <description>Created this custom object to track Address information.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Straße, Hausnummer</inlineHelpText>
        <label>Address Line 1</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>City</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsLocked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Address needs to be locked when an Order is activated so that it is not updated.</description>
        <label>Locked?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SOS_Unique_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>SOS Unique ID</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>System_Of_Origin_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>System Of Origin ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Of_Origin__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>System Of Origin</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bill To</fullName>
                </value>
                <value>
                    <fullName>Ship To</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <recordTypes>
        <fullName>CA_Address</fullName>
        <active>true</active>
        <description>Canadian Address</description>
        <label>CA Address</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CRM_Address_Event__e.object
<CustomObject>
    <description>Platform event invoked from Kafka to Salesforce upon Address inserts and updates</description>
    <fields>
        <fullName>accountID__c</fullName>
        <label>accountID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>address1__c</fullName>
        <label>address1</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>addressID__c</fullName>
        <label>addressID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>addressType__c</fullName>
        <label>addressType</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>city__c</fullName>
        <label>city</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>countryCode__c</fullName>
        <label>countryCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>country__c</fullName>
        <label>country</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>entityType__c</fullName>
        <label>entityType</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eventDate__c</fullName>
        <label>eventDate</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eventSourceID__c</fullName>
        <label>eventSourceID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eventSource__c</fullName>
        <defaultValue>&apos;SFDC&apos;</defaultValue>
        <label>eventSource</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isLocked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isLocked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>operation__c</fullName>
        <label>operation</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>parentSystemOfOriginID__c</fullName>
        <label>parentSystemOfOriginID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>postalCode__c</fullName>
        <label>postalCode</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>stage__c</fullName>
        <label>stage</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>stateProvince__c</fullName>
        <label>stateProvince</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>systemOfOriginID__c</fullName>
        <label>systemOfOriginID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>systemOfOrigin__c</fullName>
        <label>systemOfOrigin</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>version__c</fullName>
        <label>version</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>CRM Address Event - In</label>
    <pluralLabel>CRM Address Events - In</pluralLabel>
</CustomObject>

src/globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Liechtenstein</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <customValue>
        <fullName>Ireland</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Chile</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Spain</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong</fullName>
    </customValue>
    <customValue>
        <fullName>Hungary</fullName>
    </customValue>
    <customValue>
        <fullName>Israel</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Jordan</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <customValue>
        <fullName>Korea</fullName>
    </customValue>
    <customValue>
        <fullName>Kuwait</fullName>
    </customValue>
    <customValue>
        <fullName>Lebanon</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>Norway</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>Oman</fullName>
    </customValue>
    <customValue>
        <fullName>Poland</fullName>
    </customValue>
    <description>Global picklist will be used in various places</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

src/classes/PEClsHandleAddressEvents_Test.cls
@isTest
public class PEClsHandleAddressEvents_Test {

    @isTest static void sfdcAddressCreateAndUpdate() {
        id recId = [Select id from recordType where DeveloperName = 'CA_Consumer' AND isActive = true].id;
        id caAddRecId = [Select id from recordType where DeveloperName = 'CA_Address' AND isActive = true].id;
        Account a = new Account(firstname = 'New',
                                lastname = 'test', recordtypeId = recId);
        
        insert a;
        
        Address__c add = new Address__c(Account__c = a.id, Address_Line_1__c = '7511 Lucas Rd', city__c = 'Richmond', Country__c = 'Canada', RecordTypeId = caAddRecId,
                                       State__C = 'British Columbia', Postal_Code__c = 'V6Y 1G1', Type__c = 'Bill To', Primary_Flag__c = true);
        
        insert add;
        //This should automatically publish an address and should exercise the publishing code
        
        Address__c addUpd = new Address__c(id = add.id, Primary_Flag__c = false);
        
        update addUpd;
    }
    
    @isTest static void sfccCreateAddress() {
        id recId = [Select id from recordType where DeveloperName = 'CA_Consumer' AND isActive = true].id;
        id caAddRecId = [Select id from recordType where DeveloperName = 'CA_Address' AND isActive = true].id;
        Account a = new Account(firstname = 'New',
                                lastname = 'test', recordtypeId = recId);
        
        insert a;
        
         CRM_Address_Event__e  inkEvent = new CRM_Address_Event__e(version__c = '1.0',   eventDate__c = String.valueOf(System.now()), entityType__c = 'address', eventSource__c = 'ts', eventSourceID__c = 'MN-123', 
                                 operation__c = 'create', stage__c = 'pending', systemOfOrigin__c = 'ts', systemOfOriginID__c = 'MN-123', parentSystemOfOriginID__c = null, 
                                                                   accountID__c=a.id, addressID__c = null, isActive__c = true, isLocked__c = false, addressType__c = 'shipping', address1__c = '2322 Main St.',
                                                                  city__c = 'San Diego', stateProvince__c = 'CA', postalCode__c = '92121', country__c ='CA'); 
        
        Test.startTest();
        
        // Publish test event
        Database.SaveResult sr = EventBus.publish(inkEvent);
            
        Test.stopTest();
    }
    
     @isTest static void sfccCreateAddress_v1() {       
        
        Id recId = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('CA_Consumer').getRecordTypeId();
         Id caAddRecId = SObjectType.Address__c.getRecordTypeInfosByDeveloperName().get('CA_Address').getRecordTypeId();
        Account acc = new Account(firstname = 'New',
                                lastname = 'test', recordtypeId = recId);
        
        insert acc;
         
         List<Address__c> lstAddress = new List<Address__c>{
                                                            new Address__c(Account__c = acc.Id,RecordTypeId=caAddRecId,SOS_Unique_ID__c='tsMN-1233',Type__c = 'Bill To', Country__c = 'Canada', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = acc.Id,RecordTypeId=caAddRecId,Type__c = 'Ship To',Country__c = 'Canada', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                                                          };
        insert lstAddress;
        
         
         
        CRM_Address_Event__e  inkEvent = new CRM_Address_Event__e(version__c = '1.0',   eventDate__c = String.valueOf(System.now()), entityType__c = 'address', eventSource__c = 'ts', eventSourceID__c = 'MN-123', 
                                 operation__c = 'create', stage__c = 'pending', systemOfOrigin__c = 'ts', systemOfOriginID__c = 'MN-123', parentSystemOfOriginID__c = 'testt', 
                                                                   accountID__c=acc.Id, addressID__c = lstAddress[0].Id, isActive__c = true, isLocked__c = false, addressType__c = 'shipping', address1__c = '2322 Main St.',
                                                                  city__c = 'San Diego', stateProvince__c = 'CA', postalCode__c = '92121', countryCode__c ='CA'); 
        
        Test.startTest();        
        // Publish test event
        Database.SaveResult sr = EventBus.publish(inkEvent);            
        Test.stopTest();
    }
    @isTest static void sfccCreateAddress_Exception() {
        
        Id recId = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('CA_Consumer').getRecordTypeId();
         Id caAddRecId = SObjectType.Address__c.getRecordTypeInfosByDeveloperName().get('CA_Address').getRecordTypeId();
        Account acc = new Account(firstname = 'New',
                                lastname = 'test', recordtypeId = recId);
        
        insert acc;
         
         List<Address__c> lstAddress = new List<Address__c>{
                                                            new Address__c(Account__c = acc.Id,RecordTypeId=caAddRecId,SOS_Unique_ID__c='tsMN-1233',Type__c = 'Bill To', Country__c = 'Canada', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = acc.Id,RecordTypeId=caAddRecId,Type__c = 'Ship To',Country__c = 'Canada', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                                                          };
        insert lstAddress;
        
         
         
        CRM_Address_Event__e  inkEvent = new CRM_Address_Event__e(version__c = '1.0',   eventDate__c = String.valueOf(System.now()), entityType__c = 'address', eventSource__c = 'ts', eventSourceID__c = 'MN-123', 
                                 operation__c = 'create', stage__c = 'pending', systemOfOrigin__c = 'ts', systemOfOriginID__c = 'MN-123', parentSystemOfOriginID__c = 'null', 
                                                                   accountID__c='', addressID__c = lstAddress[0].Id, isActive__c = true, isLocked__c = false, addressType__c = 'shipping', address1__c = '2322 Main St.',
                                                                  city__c = 'San Diego', stateProvince__c = 'CA', postalCode__c = '92121', countryCode__c ='CA'); 
        
        Test.startTest();        
        // Publish test event
        Database.SaveResult sr = EventBus.publish(inkEvent);            
        Test.stopTest();
    }
     @isTest static void sfccCreateAddress_ExceptionV1() {
        
        Id recId = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('CA_Consumer').getRecordTypeId();
         Id caAddRecId = SObjectType.Address__c.getRecordTypeInfosByDeveloperName().get('CA_Address').getRecordTypeId();
        Account acc = new Account(firstname = 'New',
                                lastname = 'test', recordtypeId = recId);
        
        insert acc;
         
         List<Address__c> lstAddress = new List<Address__c>{
                                                            new Address__c(Account__c = acc.Id,RecordTypeId=caAddRecId,SOS_Unique_ID__c='tsMN-123',Type__c = 'Bill To', Country__c = 'Canada', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = acc.Id,RecordTypeId=caAddRecId,Type__c = 'Ship To',Country__c = 'Canada', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                                                          };
        insert lstAddress;
        
         
         
        CRM_Address_Event__e  inkEvent = new CRM_Address_Event__e(version__c = '1.0',   eventDate__c = String.valueOf(System.now()), entityType__c = 'address', eventSource__c = 'ts', eventSourceID__c = 'MN-123', 
                                 operation__c = 'create', stage__c = 'pending', systemOfOrigin__c = 'ts', systemOfOriginID__c = 'MN-123', parentSystemOfOriginID__c = 'tesgssv', 
                                                                   accountID__c=acc.Id, addressID__c = lstAddress[0].Id, isActive__c = true, isLocked__c = false, addressType__c = 'shipping', address1__c = '2322 Main St.',
                                                                  city__c = 'San Diego', stateProvince__c = 'CA', postalCode__c = '92121', countryCode__c ='CA'); 
        
        Test.startTest();        
        // Publish test event
        Database.SaveResult sr = EventBus.publish(inkEvent);            
        Test.stopTest();
    }
    @isTest static void sfccCreateAddress_v2() {       
        
        Id recId = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('CA_Consumer').getRecordTypeId();
         Id caAddRecId = SObjectType.Address__c.getRecordTypeInfosByDeveloperName().get('CA_Address').getRecordTypeId();
        Account acc = new Account(firstname = 'New',
                                lastname = 'test', recordtypeId = recId);
        
        insert acc;
         
         List<Address__c> lstAddress = new List<Address__c>{
                                                            new Address__c(Account__c = acc.Id,RecordTypeId=caAddRecId,SOS_Unique_ID__c='tsMN-1233',Type__c = 'Bill To', Country__c = 'Canada', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = acc.Id,RecordTypeId=caAddRecId,Type__c = 'Ship To',Country__c = 'Canada', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                                                          };
        insert lstAddress;
        
         
         
        CRM_Address_Event__e  inkEvent = new CRM_Address_Event__e(version__c = '1.0',   eventDate__c = String.valueOf(System.now()), entityType__c = 'address', eventSource__c = 'ts', eventSourceID__c = 'MN-123', 
                                 operation__c = 'create', stage__c = 'pending', systemOfOrigin__c = 'ts', systemOfOriginID__c = '', parentSystemOfOriginID__c = '', 
                                                                   accountID__c='', addressID__c = lstAddress[0].Id, isActive__c = true, isLocked__c = false, addressType__c = 'shipping', address1__c = '2322 Main St.',
                                                                  city__c = 'San Diego', stateProvince__c = 'CA', postalCode__c = '92121', countryCode__c ='CA'); 
        
        Test.startTest();        
        // Publish test event
        Database.SaveResult sr = EventBus.publish(inkEvent);            
        Test.stopTest();
    }
     @isTest static void sfccCreateAddress_v3() {       
        
        Id recId = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('CA_Consumer').getRecordTypeId();
         Id caAddRecId = SObjectType.Address__c.getRecordTypeInfosByDeveloperName().get('CA_Address').getRecordTypeId();
        Account acc = new Account(firstname = 'New',
                                lastname = 'test', recordtypeId = recId);
        
        insert acc;
         
         List<Address__c> lstAddress = new List<Address__c>{
                                                            new Address__c(Account__c = acc.Id,RecordTypeId=caAddRecId,SOS_Unique_ID__c='tsMN-1233',Type__c = 'Bill To', Country__c = 'Canada', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = acc.Id,RecordTypeId=caAddRecId,Type__c = 'Ship To',Country__c = 'Canada', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                                                          };
        insert lstAddress;
        
         
         
        CRM_Address_Event__e  inkEvent = new CRM_Address_Event__e(version__c = '1.0',   eventDate__c = String.valueOf(System.now()), entityType__c = 'address', eventSource__c = 'ts', eventSourceID__c = 'MN-123', 
                                 operation__c = 'create', stage__c = 'pending', systemOfOrigin__c = 'ts', systemOfOriginID__c = 'MN-123', parentSystemOfOriginID__c = 'test', 
                                                                   accountID__c=acc.Id, addressID__c = lstAddress[0].Id, isActive__c = true, isLocked__c = false, addressType__c = '', address1__c = '2322 Main St.',
                                                                  city__c = 'San Diego', stateProvince__c = 'CA', postalCode__c = '92121', countryCode__c ='CA'); 
        
        Test.startTest();        
        // Publish test event
        Database.SaveResult sr = EventBus.publish(inkEvent);            
        Test.stopTest();
    }
     @isTest static void sfccCreateAddress_v4() {       
        
        Id recId = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('CA_Consumer').getRecordTypeId();
         Id caAddRecId = SObjectType.Address__c.getRecordTypeInfosByDeveloperName().get('CA_Address').getRecordTypeId();
        Account acc = new Account(firstname = 'New',
                                lastname = 'test', recordtypeId = recId);
        
        insert acc;
         
         List<Address__c> lstAddress = new List<Address__c>{
                                                            new Address__c(Account__c = acc.Id,RecordTypeId=caAddRecId,SOS_Unique_ID__c='tsMN-1233',Type__c = 'Bill To', Country__c = 'Canada', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = acc.Id,RecordTypeId=caAddRecId,Type__c = 'Ship To',Country__c = 'Canada', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                                                          };
        insert lstAddress;
        
         
         
        CRM_Address_Event__e  inkEvent = new CRM_Address_Event__e(version__c = '1.0',   eventDate__c = String.valueOf(System.now()), entityType__c = 'address', eventSource__c = 'ts', eventSourceID__c = 'MN-123', 
                                 operation__c = 'create', stage__c = 'pending', systemOfOrigin__c = 'ts', systemOfOriginID__c = 'MN-123', parentSystemOfOriginID__c = 'test', 
                                                                   accountID__c=acc.Id, addressID__c = lstAddress[0].Id, isActive__c = true, isLocked__c = false, addressType__c = 'shipping', address1__c = '2322 Main St.',
                                                                  city__c = 'San Diego', stateProvince__c = 'CA', postalCode__c = '92121', countryCode__c ='',country__c=''); 
        
        Test.startTest();        
        // Publish test event
        Database.SaveResult sr = EventBus.publish(inkEvent);            
        Test.stopTest();
    }
    @isTest static void sfccCreateAddress_v5() {       
        
        Id recId = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('CA_Consumer').getRecordTypeId();
         Id caAddRecId = SObjectType.Address__c.getRecordTypeInfosByDeveloperName().get('CA_Address').getRecordTypeId();
        Account acc = new Account(firstname = 'New',
                                lastname = 'test', recordtypeId = recId);
        
        insert acc;
         
         List<Address__c> lstAddress = new List<Address__c>{
                                                            new Address__c(Account__c = acc.Id,RecordTypeId=caAddRecId,SOS_Unique_ID__c='tsMN-1233',Type__c = 'Bill To', Country__c = 'Canada', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = acc.Id,RecordTypeId=caAddRecId,Type__c = 'Ship To',Country__c = 'Canada', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                                                          };
        insert lstAddress;
        
         
         
        CRM_Address_Event__e  inkEvent = new CRM_Address_Event__e(version__c = '1.0',   eventDate__c = String.valueOf(System.now()), entityType__c = 'address', eventSource__c = 'ts', eventSourceID__c = 'MN-123', 
                                 operation__c = 'create', stage__c = 'pending', systemOfOrigin__c = 'ts', systemOfOriginID__c = 'MN-123', parentSystemOfOriginID__c = 'test', 
                                                                   accountID__c=acc.Id, addressID__c = lstAddress[0].Id, isActive__c = true, isLocked__c = false, addressType__c = 'shipping', address1__c = '2322 Main St.',
                                                                  city__c = 'San Diego', stateProvince__c = 'CA', postalCode__c = '92121', countryCode__c ='ASDGH'); 
        
        Test.startTest();        
        // Publish test event
        Database.SaveResult sr = EventBus.publish(inkEvent);            
        Test.stopTest();
    }
    
     @isTest static void sfccUpdateAddress() {
        id recId = [Select id from recordType where DeveloperName = 'CA_Consumer' AND isActive = true].id;
        id caAddRecId = [Select id from recordType where DeveloperName = 'CA_Address' AND isActive = true].id;
        Account a = new Account(firstname = 'New',
                                lastname = 'test', recordtypeId = recId);
        
        insert a;
         
        Address__c add = new Address__c(Account__c = a.id, Address_Line_1__c = '7511 Lucas Rd', city__c = 'Richmond', Country__c = 'Canada', RecordTypeId = caAddRecId,
                                       State__C = 'British Columbia', Postal_Code__c = 'V6Y 1G1', Type__c = 'Ship To', Primary_Flag__c = true);
        
        insert add;
        CRM_Address_Event__e  inkEvent = new CRM_Address_Event__e(version__c = '1.0',   eventDate__c = String.valueOf(System.now()), entityType__c = 'address', eventSource__c = 'ts', eventSourceID__c = 'MN-123', 
                                 operation__c = 'update', stage__c = 'pending', systemOfOrigin__c = 'ts', systemOfOriginID__c = 'MN-123', parentSystemOfOriginID__c = null, 
                                                                  accountID__c=a.id, addressID__c = add.Id, isActive__c = true, isLocked__c = false, addressType__c = 'shipping', address1__c = '2322 Main St.',
                                                                  city__c = 'San Diego', stateProvince__c = 'CA', postalCode__c = '92121', countryCode__c ='CA'); 
        add.Primary_Flag__c= true;
        add.Postal_Code__c= 'V6Y 1G2';
         update add;
        add.Primary_Flag__c= true;
        add.Postal_Code__c= 'V6Y 1G3';
         update add;
        Test.startTest();
        
        // Publish test event
        Database.SaveResult sr = EventBus.publish(inkEvent);
            
        Test.stopTest(); 
     }
    @isTest static void sfccUpdateAddress_v1() {
        id recId = [Select id from recordType where DeveloperName = 'CA_Consumer' AND isActive = true].id;
        id caAddRecId = [Select id from recordType where DeveloperName = 'CA_Address' AND isActive = true].id;
        Account a = new Account(firstname = 'New',
                                lastname = 'test', recordtypeId = recId);
        
        insert a;
         
        Address__c add = new Address__c(Account__c = a.id, Address_Line_1__c = '7511 Lucas Rd', city__c = 'Richmond', Country__c = 'Canada', RecordTypeId = caAddRecId,
                                       State__C = 'British Columbia', Postal_Code__c = 'V6Y 1G1', Type__c = 'Ship To', Primary_Flag__c = true);
        
        insert add;
        CRM_Address_Event__e  inkEvent = new CRM_Address_Event__e(version__c = '1.0',   eventDate__c = String.valueOf(System.now()), entityType__c = 'address', eventSource__c = 'ts', eventSourceID__c = 'MN-123', 
                                 operation__c = 'update', stage__c = 'pending', systemOfOrigin__c = 'ts', systemOfOriginID__c = 'MN-123', parentSystemOfOriginID__c = 'Tests', 
                                                                  accountID__c=a.id, addressID__c = add.Id, isActive__c = true, isLocked__c = false, addressType__c = 'shipping', address1__c = '2322 Main St.',
                                                                  city__c = 'San Diego', stateProvince__c = 'CA', postalCode__c = '92121', countryCode__c ='CSDFA',country__c='null'); 
        add.Primary_Flag__c= true;
        add.Postal_Code__c= 'V6Y 1G2';
         update add;
        add.Primary_Flag__c= true;
        add.Postal_Code__c= 'V6Y 1G3';
         update add;
        Test.startTest();
        
        // Publish test event
        Database.SaveResult sr = EventBus.publish(inkEvent);
            
        Test.stopTest(); 
     }
    @isTest static void sfccCreateAddressWithPsoo() {
        id recId = [Select id from recordType where DeveloperName = 'CA_Consumer' AND isActive = true].id;
        id caAddRecId = [Select id from recordType where DeveloperName = 'CA_Address' AND isActive = true].id;
        Account a = new Account(firstname = 'New',
                                lastname = 'test', recordtypeId = recId, system_of_Origin__c = 'crm', system_of_Origin_Id__c='10423343');
        
        insert a;
        
         CRM_Address_Event__e  inkEvent = new CRM_Address_Event__e(version__c = '1.0',   eventDate__c = String.valueOf(System.now()), entityType__c = 'address', eventSource__c = 'ts', eventSourceID__c = 'MN-123', 
                                 operation__c = 'create', stage__c = 'pending', systemOfOrigin__c = 'ts', systemOfOriginID__c = 'MN-123', parentSystemOfOriginID__c = '10423343', 
                                                                  addressID__c = null, isActive__c = true, isLocked__c = false, addressType__c = 'shipping', address1__c = '2322 Main St.',
                                                                  city__c = 'San Diego', stateProvince__c = 'CA', postalCode__c = '92121', countryCode__c ='CA'); 
        
        Test.startTest();
        
        // Publish test event
        Database.SaveResult sr = EventBus.publish(inkEvent);
            
        Test.stopTest();
    }

}