src/objects/Address__c.object
<CustomObject>
    <description>Created this custom object to track Address information.</description>
    <fields>
        <fullName>Integration_Error_Message__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Integration Error Message</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CRM_Error_Event__e.object
<CustomObject>
    <fields>
        <fullName>code__c</fullName>
        <description>For now 500 as the fixed value</description>
        <label>code</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>entityType__c</fullName>
        <description>Same as entityType</description>
        <label>entityType</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eventDate__c</fullName>
        <label>eventDate</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eventSource__c</fullName>
        <label>eventSource</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>key__c</fullName>
        <label>key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>message__c</fullName>
        <label>message</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>payload__c</fullName>
        <label>payload</label>
        <length>100000</length>
        <type>LongTextArea</type>
    </fields>
    <label>CRM Error Event</label>
    <pluralLabel>CRM Error Events</pluralLabel>
</CustomObject>

src/objects/CRM_Error_Event_In__e.object
<CustomObject>
    <fields>
        <fullName>code__c</fullName>
        <label>code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>entityType__c</fullName>
        <label>entityType</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eventDate__c</fullName>
        <label>eventDate</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eventSource__c</fullName>
        <label>eventSource</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>key__c</fullName>
        <label>key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>message__c</fullName>
        <label>message</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>payload__c</fullName>
        <label>payload</label>
        <length>100000</length>
        <type>LongTextArea</type>
    </fields>
    <label>CRM Error Event In</label>
    <pluralLabel>CRM Error Events In</pluralLabel>
</CustomObject>

src/objects/Platform_Event_Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <description>What was the Action when this error occurred.</description>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Publish</fullName>
                </value>
                <value>
                    <fullName>Consume</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Class_And_Method__c</fullName>
        <description>Class and method that is writing the Error.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Class and method that is writing the Error.</inlineHelpText>
        <label>Class And Method</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Handling_Status__c</fullName>
        <label>Error Handling Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Ignored</fullName>
                </value>
                <value>
                    <fullName>Assigned to Source System</fullName>
                </value>
                <value>
                    <fullName>Fixing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>Short error message. Typically from the program making this entry.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Error message from the program that caught the exception.</inlineHelpText>
        <label>Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EventSource__c</fullName>
        <description>Source of the Event. In Publish scenario, it is SELF.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>SELF or some external system that created the source event.</inlineHelpText>
        <label>EventSource</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_String__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Event String</label>
        <length>100000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>The name of the event that was being processed when this error occurred.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Name of the Event when this error happened.</inlineHelpText>
        <label>Object</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Error__c</fullName>
        <description>Full exception error message.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Full exception error message.</inlineHelpText>
        <label>Event</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <description>Error severity.</description>
        <label>Severity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fatal Error - Bailing out</fullName>
                </value>
                <value>
                    <fullName>Recoverable Error - Published/Consumed</fullName>
                </value>
                <value>
                    <fullName>Error Ignored</fullName>
                </value>
                <value>
                    <fullName>Informational</fullName>
                </value>
                <value>
                    <fullName>Success Log</fullName>
                </value>
                <value>
                    <fullName>Error-In</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Platform Event Error Log</label>
    <nameField>
        <displayFormat>PEEL-{0000000}</displayFormat>
        <label>Error</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Platform Event Error Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClsPlatformEventErrorLogHandler.cls
public class ClsPlatformEventErrorLogHandler {
    public static void handleInsert(List<Platform_Event_Error_Log__c> errors) {
        List<CRM_Error_Event__e> errEventsList = new List<CRM_Error_Event__e>();
        CRM_Error_Event__e  event;
        string str;
        for(Platform_Event_Error_Log__c error : errors) {
            if (error.Severity__c == 'Success Log' || error.Severity__c == 'Error-in') continue;    // Don't publish these events as it is not an error.
            event = new CRM_Error_Event__e();
            event.code__c = '400';
            event.eventDate__c = String.valueOf(error.LastModifiedDate.formatGmt('yyyy-MM-dd\'T\'HH:mm:ss.SSSZ'));
            event.eventSource__c = error.EventSource__c ;
            event.entityType__c= error.Event__c;
            //event.keyName__c = 'systemOfOriginID';
            event.key__c = error.EventSource__c;
            str = error.Error_Message__c + ' ' + error.Exception_Error__c;  
            event.message__c = str.left(255);
            event.payload__c = error.Event_String__c;
            errEventsList.add(event);
        }
        if (errEventsList.size() > 0) {
            List<Database.SaveResult> svrs = EventBus.publish(errEventsList);
            for (Database.SaveResult svr : svrs) {
                if (!svr.isSuccess()) {
                  system.debug('Error in publishing Account Event. Error: ' + svr.getErrors());
                }
            }
        }
    }
    public static void handleInboundErrors(List<CRM_Error_Event_In__e> errors) {
        List<Platform_Event_Error_Log__c> pees = new List<Platform_Event_Error_Log__c>();
        Platform_Event_Error_Log__c pee;
        List<Address__c> ListAddresses = new List<Address__c>();
        List<Account> ListAccounts = new List<Account>();
        List<Order> ListOrders = new List<Order>();
        Map<String, String> MapOrderErrors = new Map<String, String>();
        for (CRM_Error_Event_In__e inev : errors) {
            //SFDC publishes only the following 3 Event types. So, need to ignore other reported errors.
            if (!(inev.entityType__c.startsWithIgnoreCase('address') || inev.entityType__c.startsWithIgnoreCase('account') || inev.entityType__c.startsWithIgnoreCase('order'))) continue;
            pee = new Platform_Event_Error_Log__c();
            pee.Event__c = inev.entityType__c.left(40);   // Label Object
            pee.EventSource__c = inev.key__c.left(40);    // Label EventSource
            pee.Error_Message__c = inev.message__c.left(255);  // Label Message 
            pee.Action__c = 'consume'; // Label Action
            pee.Error_Handling_Status__c = 'New';  // Not displayed
            pee.Severity__c = 'Error-In';
            pee.Class_And_Method__c = 'Incoming Error';
            pee.Exception_Error__c = inev.code__c.left(100);
            pee.Event_String__c = inev.payload__c;
            pees.add(pee);
            //Logic to write data into the actual events
            if(inev.entityType__c.startsWithIgnoreCase('address')) {
                ListAddresses.add(new Address__c(id = inev.key__c, Integration_Error_Message__c=inev.message__c.left(500)));
            }
            if(inev.entityType__c.startsWithIgnoreCase('account')) {
                ListAccounts.add(new Account(id = inev.key__c, Integration_Error_Message__c=inev.message__c.left(500)));//
            }
            if(inev.entityType__c.startsWithIgnoreCase('order')) {
                MapOrderErrors.put(inev.key__c, inev.message__c.left(500));
                //ListOrders.add(new Order(id = inev.key__c, Integration_Error_Message__c=inev.message__c.left(500)));
            }
        }
        insert pees;
        if (ListAddresses.size() > 0) update ListAddresses;
        if (ListAccounts.size() > 0) update ListAccounts;
        if (MapOrderErrors.size() > 0) {
            Map<String, ID> MapOrderNumberToId = new Map<String, Id>();
            for(Order o : [Select Id, OrderNumber from Order where OrderNumber in :MapOrderErrors.keySet()]) MapOrderNumberToId.put(o.OrderNumber, o.Id);
            for(String onum : MapOrderErrors.keyset()) {
                ListOrders.add(new Order(id = MapOrderNumberToId.get(onum), Integration_Error_Message__c=MapOrderErrors.get(onum)));
            }
            if (ListOrders.size() > 0) update ListOrders;
        }
    }
}