src/objects/Address__c.object
<CustomObject>
    <description>Created this custom object to track Address information.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Straße, Hausnummer</inlineHelpText>
        <label>Address Line 1</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>City</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Phone__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Primary Phone</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Of_Origin_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>System Of Origin ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Of_Origin__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>System Of Origin</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bill To</fullName>
                </value>
                <value>
                    <fullName>Ship To</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CRM_Order_Event__e.object
<CustomObject>
    <description>Platform event invoked from Kafka to Salesforce upon Order inserts and updates</description>
    <fields>
        <fullName>Line_Items__c</fullName>
        <label>Line Items</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>accountId__c</fullName>
        <label>accountId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>billingAddress1__c</fullName>
        <label>billingAddress1</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>billingAddress2__c</fullName>
        <label>billingAddress2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>billingAddress3__c</fullName>
        <label>billingAddress3</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>billingAddressAccountID__c</fullName>
        <label>billingAddressAccountID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>billingAddressBusinessName__c</fullName>
        <label>billingAddressBusinessName</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>billingAddressCity__c</fullName>
        <label>billingAddressCity</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>billingAddressCountryCode__c</fullName>
        <label>billingAddressCountryCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>billingAddressCountry__c</fullName>
        <label>billingAddressCountry</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>billingAddressFirstName__c</fullName>
        <label>billingAddressFirstName</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>billingAddressId__c</fullName>
        <label>billingAddressId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>billingAddressIsLocked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>billingAddressIsLocked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>billingAddressLastName__c</fullName>
        <label>billingAddressLastName</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>billingAddressPostalCode__c</fullName>
        <label>billingAddressPostalCode</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>billingAddressPrimaryPhone__c</fullName>
        <label>billingAddressPrimaryPhone</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>billingAddressStateProvince__c</fullName>
        <label>billingAddressStateProvince</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>creditCardAuthorizationCode__c</fullName>
        <label>creditCardAuthorizationCode</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>creditCardExpirationDate__c</fullName>
        <label>creditCardExpirationDate</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>creditCardId__c</fullName>
        <label>creditCardId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>creditCardToken__c</fullName>
        <label>creditCardToken</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>creditCardType__c</fullName>
        <label>creditCardType</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>entityType__c</fullName>
        <label>entityType</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eventDate__c</fullName>
        <label>eventDate</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eventSourceID__c</fullName>
        <label>eventSourceID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eventSource__c</fullName>
        <defaultValue>&apos;SFDC&apos;</defaultValue>
        <label>eventSource</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>invoiceDate__c</fullName>
        <label>invoiceDate</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>invoiceNumber__c</fullName>
        <label>invoiceNumber</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isSignatureRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isSignatureRequired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>operation__c</fullName>
        <label>operation</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>orderNumber__c</fullName>
        <label>orderNumber</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>orderType__c</fullName>
        <label>orderType</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>paymentTerm__c</fullName>
        <label>paymentTerm</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pricebookName__c</fullName>
        <label>pricebookName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>rgaNumber__c</fullName>
        <label>rgaNumber</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>scheduledShipDate__c</fullName>
        <label>scheduledShipDate</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingAddress1__c</fullName>
        <label>shippingAddress1</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingAddress2__c</fullName>
        <label>shippingAddress2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingAddress3__c</fullName>
        <label>shippingAddress3</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingAddressAccountId__c</fullName>
        <label>shippingAddressAccountId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingAddressBusinessName__c</fullName>
        <label>shippingAddressBusinessName</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingAddressCity__c</fullName>
        <label>shippingAddressCity</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingAddressCountryCode__c</fullName>
        <label>shippingAddressCountryCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingAddressCountry__c</fullName>
        <label>shippingAddressCountry</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingAddressFirstName__c</fullName>
        <label>shippingAddressFirstName</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingAddressId__c</fullName>
        <label>shippingAddressId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingAddressIsLocked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>shippingAddressIsLocked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>shippingAddressLastName__c</fullName>
        <label>shippingAddressLastName</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingAddressPostalCode__c</fullName>
        <label>shippingAddressPostalCode</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingAddressPrimaryPhone__c</fullName>
        <label>shippingAddressPrimaryPhone</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingAddressStateProvince__c</fullName>
        <label>shippingAddressStateProvince</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingMethod__c</fullName>
        <label>shippingMethod</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>shippingNotes__c</fullName>
        <label>shippingNotes</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>stage__c</fullName>
        <label>stage</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>statusMessage__c</fullName>
        <label>statusMessage</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>systemOfOriginID__c</fullName>
        <label>systemOfOriginID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>systemOfOrigin__c</fullName>
        <label>systemOfOrigin</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>version__c</fullName>
        <label>version</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>CRM Order Event - In</label>
    <pluralLabel>CRM_Order_Events - In</pluralLabel>
</CustomObject>

src/globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Liechtenstein</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <customValue>
        <fullName>Ireland</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Chile</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Spain</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong</fullName>
    </customValue>
    <customValue>
        <fullName>Hungary</fullName>
    </customValue>
    <customValue>
        <fullName>Israel</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Jordan</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <customValue>
        <fullName>Korea</fullName>
    </customValue>
    <customValue>
        <fullName>Kuwait</fullName>
    </customValue>
    <customValue>
        <fullName>Lebanon</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>Norway</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>Oman</fullName>
    </customValue>
    <customValue>
        <fullName>Poland</fullName>
    </customValue>
    <description>Global picklist will be used in various places</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

src/classes/PEClsHandleOrderEvents_Test.cls
@isTest()
private class PEClsHandleOrderEvents_Test {
 
    @testSetup static void setup() {
        Map<String, String> mapPriceBook = ClsTestDataFactory.createCustomPricebook(new List<String>{'DE Netto-Preis Cash', 'DE Return Replace', 'Barmer'});
        Map<String, Id> mapProduct = ClsTestDataFactory.createProducts(new List<String>{'Product-01', 'Product-02', 'Product-03', 'DEX-SHIP-01'});
        Map<Id, Decimal> productIdToPriceMap = new Map<Id, Decimal>{mapProduct.values()[0] => 10, mapProduct.values()[1] => 10, mapProduct.values()[2] => 10,mapProduct.values()[3] => 10 };
        Map<Id, Id> mapPBE = ClsTestDataFactory.createCustomPricebookEntries(productIdToPriceMap, mapPriceBook.get('DE Netto-Preis Cash'));
        Account objAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'DE Consumer', 'Germany')[0];
        System.debug('mapProduct---'+mapProduct.values()); 
    }
    
    @isTest private static void testCreateECOM(){
        List<PEClsHandleOrderEvents.OrderLineItem> lstOLI = new List<PEClsHandleOrderEvents.OrderLineItem>();
        for(Product2 product : [SELECT Id, Name FROM Product2]){
            lstOLI.add(new PEClsHandleOrderEvents.OrderLineItem(product.Name, 1, 10));
        }
        List<Product2> lstProduct = [SELECT Id, Name FROM Product2];
        List<Account> lstAccount = [SELECT Id, Name FROM Account];
        
         //Query for the Address record types
        List<RecordType> rtypes = [Select Name, Id From RecordType 
                               where sObjectType='Address__c' and isActive=true];
    
        //Create a map between the Record Type Name and Id 
        Map<String,String> addRecordTypes = new Map<String,String>();
        for(RecordType rt: rtypes) {
        addRecordTypes.put(rt.Name,rt.Id);
        }     	
        String recordTypeId = addRecordTypes.get('DE Address');
        List<Address__c> lstAddress = new List<Address__c>{
                                                            new Address__c(Account__c = lstAccount[0].Id,RecordTypeId = recordTypeId,Type__c = 'Bill To', Country__c = 'Germany', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = lstAccount[0].Id,RecordTypeId = recordTypeId,Type__c = 'Ship To',Country__c = 'Germany', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                                                          };
        insert lstAddress;
        
        CRM_Order_Event__e oEvent = new CRM_Order_Event__e(version__c = '1.0',orderType__c = 'Sales_Order', operation__c = 'create',stage__c = 'pending',eventSource__c = 'ECOM',
                                                           systemOfOrigin__c = '12345', systemOfOriginID__c = 'abcdefg', accountId__c = lstAccount[0].Id, 
                                                           billingAddress1__c = '10255 W Higgins Rd', billingAddress2__c = '', billingAddress3__c = '', 
                                                           billingAddressAccountID__c = lstAccount[0].Id, billingAddressBusinessName__c = 'Test', billingAddressCity__c = 'Rosemont',
                                                           billingAddressCountry__c = 'Germany', billingAddressCountryCode__c = 'DE', billingAddressFirstName__c = 'Test', 
                                                           billingAddressIsLocked__c = false, billingAddressLastName__c = 'Test', billingAddressPostalCode__c = '60089',
                                                           billingAddressPrimaryPhone__c = '9876543210', billingAddressStateProvince__c = '', creditCardAuthorizationCode__c = '12356890qwertyuiosd',
                                                           creditCardExpirationDate__c = '0421',creditCardId__c = '', creditCardToken__c = '1234567890qwetyuio',
                                                           creditCardType__c = 'Visa',entityType__c = 'order', eventDate__c = '', eventSourceID__c = '123456',
                                                           invoiceDate__c = String.ValueOf(Date.today().addMonths(2)), isSignatureRequired__c = false, Line_Items__c = JSON.serialize(lstOLI),
                                                           orderNumber__c = '', paymentTerm__c = '', pricebookName__c = 'DE Netto-Preis Cash',
                                                           rgaNumber__c = '', scheduledShipDate__c = '', shippingAddress1__c = '10255 W Higgins Rd',
                                                           shippingAddress2__c = '', shippingAddress3__c = '', shippingAddressAccountId__c = lstAccount[0].Id, 
                                                           shippingAddressBusinessName__c = 'test@1231', shippingAddressCity__c = 'Rosemont',
                                                           shippingAddressCountry__c = 'Germany', shippingAddressCountryCode__c = 'DE',
                                                           shippingAddressFirstName__c = 'test', shippingAddressIsLocked__c = false, shippingAddressLastName__c = 'Test1',
                                                           shippingAddressPostalCode__c = '60099', shippingAddressPrimaryPhone__c = '1111',
                                                           shippingAddressStateProvince__c = '', shippingMethod__c = '000001_CADS_D_3DS',
                                                           shippingNotes__c = '', status__c = '',
                                                           statusMessage__c = '', billingAddressId__c = lstAddress[0].Id,shippingAddressId__c = lstAddress[1].Id);
        System.debug('====oEvent===='+JSON.serialize(oEvent));
        Test.startTest();
            Database.SaveResult sr = EventBus.publish(oEvent);
        Test.stopTest();
        System.assertEquals(true, sr.isSuccess());
        List<Order> orders = [SELECT Id FROM Order];
        system.debug('=======orders====='+orders);
       // System.assertEquals(1, orders.size());
    }
    @isTest private static void testCreateOMSBatch(){
        List<PEClsHandleOrderEvents.OrderLineItem> lstOLI = new List<PEClsHandleOrderEvents.OrderLineItem>();
        for(Product2 product : [SELECT Id, Name FROM Product2]){
            lstOLI.add(new PEClsHandleOrderEvents.OrderLineItem(product.Name, 1, 10));
        }
        List<Product2> lstProduct = [SELECT Id, Name FROM Product2];
        List<Account> lstAccount = [SELECT Id, Name FROM Account];
        
         //Query for the Address record types
        List<RecordType> rtypes = [Select Name, Id From RecordType 
                               where sObjectType='Address__c' and isActive=true];
    
        //Create a map between the Record Type Name and Id 
        Map<String,String> addRecordTypes = new Map<String,String>();
        for(RecordType rt: rtypes) {
        addRecordTypes.put(rt.Name,rt.Id);
        }     	
        String recordTypeId = addRecordTypes.get('DE Address'); 
        List<Address__c> lstAddress = new List<Address__c>{
                                                            new Address__c(Account__c = lstAccount[0].Id,RecordTypeId = recordTypeId,Type__c = 'Bill To', Country__c = 'Germany', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = lstAccount[0].Id,RecordTypeId = recordTypeId,Type__c = 'Ship To',Country__c = 'Germany', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                                                          };
        insert lstAddress;
        
        CRM_Order_Event__e oEvent = new CRM_Order_Event__e(version__c = '1.0',orderType__c = 'Sales_Order', operation__c = 'create',stage__c = 'pending',eventSource__c = 'OMS',
                                                           systemOfOrigin__c = '12345', systemOfOriginID__c = 'abcdefg', accountId__c = lstAccount[0].Id, 
                                                           billingAddress1__c = '10255 W Higgins Rd', billingAddress2__c = '', billingAddress3__c = '', 
                                                           billingAddressAccountID__c = lstAccount[0].Id, billingAddressBusinessName__c = 'Test', billingAddressCity__c = 'Rosemont',
                                                           billingAddressCountry__c = 'Germany', billingAddressCountryCode__c = 'DE', billingAddressFirstName__c = 'Test', 
                                                           billingAddressIsLocked__c = false, billingAddressLastName__c = 'Test', billingAddressPostalCode__c = '60089',
                                                           billingAddressPrimaryPhone__c = '9876543210', billingAddressStateProvince__c = 'BC', creditCardAuthorizationCode__c = '12356890qwertyuiosd',
                                                           creditCardExpirationDate__c = '0421',creditCardId__c = '', creditCardToken__c = '1234567890qwetyuio',
                                                           creditCardType__c = 'Visa',entityType__c = 'order', eventDate__c = '', eventSourceID__c = '123456',
                                                           invoiceDate__c = String.ValueOf(Date.today().addMonths(2)), isSignatureRequired__c = false, Line_Items__c = JSON.serialize(lstOLI),
                                                           orderNumber__c = '', paymentTerm__c = '', pricebookName__c = 'DE Netto-Preis Cash',
                                                           rgaNumber__c = '', scheduledShipDate__c = '', shippingAddress1__c = '10255 W Higgins Rd',
                                                           shippingAddress2__c = '', shippingAddress3__c = '', shippingAddressAccountId__c = lstAccount[0].Id, 
                                                           shippingAddressBusinessName__c = 'test@1231', shippingAddressCity__c = 'Rosemont',
                                                           shippingAddressCountry__c = 'Germany', shippingAddressCountryCode__c = 'DE',
                                                           shippingAddressFirstName__c = 'test', shippingAddressIsLocked__c = false, shippingAddressLastName__c = 'Test1',
                                                           shippingAddressPostalCode__c = '60099', shippingAddressPrimaryPhone__c = '1111',
                                                           shippingAddressStateProvince__c = '', shippingMethod__c = '000001_CADS_D_3DS',
                                                           shippingNotes__c = '', status__c = '',
                                                           statusMessage__c = '', billingAddressId__c = lstAddress[0].Id,shippingAddressId__c = lstAddress[1].Id);
        System.debug('====oEvent===='+JSON.serialize(oEvent));
        Test.startTest();
            Database.SaveResult sr = EventBus.publish(oEvent); 
        Test.stopTest();
        System.assertEquals(true, sr.isSuccess());
        List<Order> orders = [SELECT Id FROM Order];
        system.debug('=======orders====='+orders);
       // System.assertEquals(1, orders.size());
    }
    @isTest private static void testCreateECOMError(){
        List<Account> lstAccount = [SELECT Id, Name FROM Account];
        List<PEClsHandleOrderEvents.OrderLineItem> lstOLI = new List<PEClsHandleOrderEvents.OrderLineItem>();
        for(Product2 product : [SELECT Id, Name FROM Product2]){
            lstOLI.add(new PEClsHandleOrderEvents.OrderLineItem(product.Id, 1, 10));
        }
        
         //Query for the Address record types
        List<RecordType> rtypes = [Select Name, Id From RecordType 
                               where sObjectType='Address__c' and isActive=true];
    
        //Create a map between the Record Type Name and Id 
        Map<String,String> addRecordTypes = new Map<String,String>();
        for(RecordType rt: rtypes) {
        addRecordTypes.put(rt.Name,rt.Id);
        }     	
        String recordTypeId = addRecordTypes.get('DE Address');
        List<Address__c> lstAddress = new List<Address__c>{
                                                            new Address__c(Account__c = lstAccount[0].Id,RecordTypeId = recordTypeId,Type__c = 'Bill To', Country__c = 'Germany', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = lstAccount[0].Id,RecordTypeId = recordTypeId,Type__c = 'Ship To',Country__c = 'Germany', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                                                          };
        insert lstAddress;
        
        CRM_Order_Event__e oEvent = new CRM_Order_Event__e(version__c = '1.0',orderType__c = 'Sales_Order', operation__c = 'create',stage__c = 'pending',eventSource__c = 'ECOM',
                                                           systemOfOrigin__c = '12345', systemOfOriginID__c = 'abcdefg', accountId__c = lstAccount[0].Id, 
                                                           billingAddress1__c = '10255 W Higgins Rd1', billingAddress2__c = '10255 W Higgins Rd1', billingAddress3__c = '10255 W Higgins Rd1', 
                                                           billingAddressAccountID__c = lstAccount[0].Id, billingAddressBusinessName__c = 'Test@@@', billingAddressCity__c = 'Rosemont@@',
                                                           billingAddressCountry__c = 'Germany', billingAddressCountryCode__c = 'D!E', billingAddressFirstName__c = 'Test1', 
                                                           billingAddressIsLocked__c = false, billingAddressLastName__c = 'Test', billingAddressPostalCode__c = '60099',
                                                           billingAddressPrimaryPhone__c = '9876543220', billingAddressStateProvince__c = '', creditCardAuthorizationCode__c = '12356890qwertyuiosd',
                                                           creditCardExpirationDate__c = '0421',creditCardId__c = '', creditCardToken__c = '1234567890qwetyuio',
                                                           creditCardType__c = 'Visa',entityType__c = 'order', eventDate__c = '', eventSourceID__c = '123456',
                                                           invoiceDate__c = String.ValueOf(Date.today().addMonths(2)), isSignatureRequired__c = false, Line_Items__c = JSON.serialize(lstOLI),
                                                           orderNumber__c = '', paymentTerm__c = '', pricebookName__c = 'DE Netto-Preis Cash',
                                                           rgaNumber__c = '', scheduledShipDate__c = '', shippingAddress1__c = '10255 W Higgins Rd1',
                                                           shippingAddress2__c = '10255 W Higgins Rd1', shippingAddress3__c = '10255 W Higgins Rd1', shippingAddressAccountId__c = lstAccount[0].Id, 
                                                           shippingAddressBusinessName__c = 'test@1231', shippingAddressCity__c = 'Rosemont1',
                                                           shippingAddressCountry__c = 'Germany', shippingAddressCountryCode__c = 'DE1',
                                                           shippingAddressFirstName__c = 'test1', shippingAddressIsLocked__c = false, shippingAddressLastName__c = 'Test1',
                                                           shippingAddressPostalCode__c = '60089', shippingAddressPrimaryPhone__c = '1234567890',
                                                           shippingAddressStateProvince__c = '', shippingMethod__c = '000001_CADS_D_3DS',shippingNotes__c = '', status__c = '', statusMessage__c = '');
        Test.startTest();
            Database.SaveResult sr = EventBus.publish(oEvent);
        Test.stopTest();
    }
    @isTest private static void testCreateOMS(){
        Account payorAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'DE Payor', 'Germany')[0];
        List<Account> lstAccount = [SELECT Id, Name FROM Account];
        List<PEClsHandleOrderEvents.OrderLineItem> lstOLI = new List<PEClsHandleOrderEvents.OrderLineItem>();
        for(Product2 product : [SELECT Id, Name FROM Product2]){
            lstOLI.add(new PEClsHandleOrderEvents.OrderLineItem(product.Id, 1, 10));
        }
        
        List<Product2> lstProduct = [SELECT Id, Name FROM Product2];
         //Query for the Address record types
        List<RecordType> rtypes = [Select Name, Id From RecordType 
                               where sObjectType='Address__c' and isActive=true];
    
        //Create a map between the Record Type Name and Id 
        Map<String,String> addRecordTypes = new Map<String,String>();
        for(RecordType rt: rtypes) {
        addRecordTypes.put(rt.Name,rt.Id);
        }     	
        String recordTypeId = addRecordTypes.get('DE Address');
        List<Address__c> lstAddress = new List<Address__c>{
                                                            new Address__c(Account__c = lstAccount[0].Id,RecordTypeId = recordTypeId,Type__c = 'Bill To', Country__c = 'Germany', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = lstAccount[0].Id,RecordTypeId = recordTypeId,Type__c = 'Ship To',Country__c = 'Germany', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = payorAccount.Id,RecordTypeId = recordTypeId,Type__c = 'Bill To', Country__c = 'Germany', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = payorAccount.Id,RecordTypeId = recordTypeId,Type__c = 'Ship To',Country__c = 'Germany', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                                                          };
        insert lstAddress;
        List<PricebookEntry> lstPBE = [SELECT Id, Pricebook2Id FROM PricebookEntry WHERE Pricebook2.Name = 'DE Netto-Preis Cash'];
        Order objOrder = new Order(AccountId = lstAccount[0].Id, EffectiveDate = Date.today(), Status = 'Draft', Type = '', Payor__c = payorAccount.Id, Pricebook2Id = lstPBE[0].Pricebook2Id);
        insert objOrder;
        List<OrderItem> lstOrderItem = new List<OrderItem>();
        for(PricebookEntry pbe : lstPBE){
            lstOrderItem.add(new OrderItem(PricebookEntryId = pbe.Id, OrderId = objOrder.Id, Quantity = 1, UnitPrice = 10));
        }
        insert lstOrderItem;
        List<Order> lstOrder = [SELECT Id, OrderNumber FROM Order]; 
        CRM_Order_Event__e oEvent = new CRM_Order_Event__e(version__c = '1.0',orderType__c = 'Sales_Order', operation__c = 'create',stage__c = 'confirmed',eventSource__c = 'OMS',
                                                           systemOfOrigin__c = '12345', systemOfOriginID__c = 'abcdefg', accountId__c = lstAccount[0].Id, 
                                                           billingAddress1__c = '10255 W Higgins Rd', billingAddress2__c = '10255 W Higgins Rd', billingAddress3__c = '10255 W Higgins Rd', 
                                                           billingAddressAccountID__c = lstAccount[0].Id, billingAddressBusinessName__c = 'Test', billingAddressCity__c = 'Rosemont1',
                                                           billingAddressCountry__c = 'Germany', billingAddressCountryCode__c = 'DE', billingAddressFirstName__c = 'Test', 
                                                           billingAddressIsLocked__c = false, billingAddressLastName__c = 'Test', billingAddressPostalCode__c = '60089',
                                                           billingAddressPrimaryPhone__c = '9876543210', billingAddressStateProvince__c = '', creditCardAuthorizationCode__c = '12356890qwertyuiosd',
                                                           billingAddressId__c = lstAddress[0].Id,shippingAddressId__c = lstAddress[1].Id,
                                                           creditCardExpirationDate__c = '0421',creditCardId__c = '', creditCardToken__c = '1234567890qwetyuio',
                                                           creditCardType__c = 'Visa',entityType__c = 'order', eventDate__c = '', eventSourceID__c = '123456',
                                                           invoiceDate__c = String.ValueOf(Date.today().addMonths(2)), invoiceNumber__c = '', isSignatureRequired__c = false, Line_Items__c = JSON.serialize(lstOLI),
                                                           orderNumber__c = lstOrder[0].OrderNumber, paymentTerm__c = '', pricebookName__c = 'DE Netto-Preis Cash',
                                                           rgaNumber__c = '', scheduledShipDate__c = '', shippingAddress1__c = '10255 W Higgins Rd',
                                                           shippingAddress2__c = '10255 W Higgins Rd', shippingAddress3__c = '10255 W Higgins Rd', shippingAddressAccountId__c = lstAccount[0].Id, 
                                                           shippingAddressBusinessName__c = 'test@123', shippingAddressCity__c = 'Rosemont1',
                                                           shippingAddressCountry__c = 'Germany', shippingAddressCountryCode__c = 'DE',shippingAddressFirstName__c = 'test', 
                                                           shippingAddressIsLocked__c = false, shippingAddressLastName__c = 'Test',
                                                           shippingAddressPostalCode__c = '60089', shippingAddressPrimaryPhone__c = '1234567890',
                                                           shippingAddressStateProvince__c = '', shippingMethod__c = '000001_CADS_D_3DS',
                                                           shippingNotes__c = '', status__c = '',
                                                           statusMessage__c = '');
        Test.startTest(); 
        Database.SaveResult sr = EventBus.publish(oEvent);
        Test.stopTest();
    }
    @isTest private static void testUpdateOMS(){
        Account payorAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'DE Payor', 'Germany')[0];
        List<Account> lstAccount = [SELECT Id, Name FROM Account];
        List<PEClsHandleOrderEvents.OrderLineItem> lstOLI = new List<PEClsHandleOrderEvents.OrderLineItem>();
        for(Product2 product : [SELECT Id, Name FROM Product2]){
            lstOLI.add(new PEClsHandleOrderEvents.OrderLineItem(product.Id, 1, 10));
        }
        List<Product2> lstProduct = [SELECT Id, Name FROM Product2];
         //Query for the Address record types
        List<RecordType> rtypes = [Select Name, Id From RecordType 
                               where sObjectType='Address__c' and isActive=true];
    
        //Create a map between the Record Type Name and Id 
        Map<String,String> addRecordTypes = new Map<String,String>();
        for(RecordType rt: rtypes) {
        addRecordTypes.put(rt.Name,rt.Id);
        }     	
        String recordTypeId = addRecordTypes.get('DE Address');
        List<Address__c> lstAddress = new List<Address__c>{
                                                            new Address__c(Account__c = lstAccount[0].Id,RecordTypeId = recordTypeId,Type__c = 'Bill To', Country__c = 'Germany', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = lstAccount[0].Id,RecordTypeId = recordTypeId,Type__c = 'Ship To',Country__c = 'Germany', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = payorAccount.Id,RecordTypeId = recordTypeId,Type__c = 'Bill To', Country__c = 'Germany', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = payorAccount.Id,RecordTypeId = recordTypeId,Type__c = 'Ship To',Country__c = 'Germany', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                                                          };
        insert lstAddress;
        List<PricebookEntry> lstPBE = [SELECT Id, Pricebook2Id FROM PricebookEntry WHERE Pricebook2.Name = 'DE Netto-Preis Cash'];
        Order objOrder = new Order(AccountId = lstAccount[0].Id, EffectiveDate = Date.today(), Status = 'Draft', Type = '', Payor__c = payorAccount.Id, Pricebook2Id = lstPBE[0].Pricebook2Id);
        insert objOrder;
        List<OrderItem> lstOrderItem = new List<OrderItem>();
        for(PricebookEntry pbe : lstPBE){
            lstOrderItem.add(new OrderItem(PricebookEntryId = pbe.Id, OrderId = objOrder.Id, Quantity = 1, UnitPrice = 10));
        }
        insert lstOrderItem;
        List<Order> lstOrder = [SELECT Id, OrderNumber FROM Order]; 
        CRM_Order_Event__e oEvent = new CRM_Order_Event__e(version__c = '1.0',orderType__c = 'Sales_Order', operation__c = 'update',stage__c = 'pending',eventSource__c = 'OMS',
                                                           systemOfOrigin__c = '12345', systemOfOriginID__c = 'abcdefg', accountId__c = lstAccount[0].Id, 
                                                           billingAddress1__c = '10255 W Higgins Rd', billingAddress2__c = '10255 W Higgins Rd', billingAddress3__c = '10255 W Higgins Rd', 
                                                           billingAddressAccountID__c = lstAccount[0].Id, billingAddressBusinessName__c = 'Test', billingAddressCity__c = 'Rosemont1',
                                                           billingAddressCountry__c = 'Germany', billingAddressCountryCode__c = 'DE', billingAddressFirstName__c = 'Test', 
                                                           billingAddressIsLocked__c = false, billingAddressLastName__c = 'Test', billingAddressPostalCode__c = '60089',
                                                           billingAddressPrimaryPhone__c = '9876543210', billingAddressStateProvince__c = '', creditCardAuthorizationCode__c = '12356890qwertyuiosd',
                                                           billingAddressId__c = lstAddress[0].Id,shippingAddressId__c = lstAddress[1].Id,
                                                           creditCardExpirationDate__c = '0421',creditCardId__c = '', creditCardToken__c = '1234567890qwetyuio',
                                                           creditCardType__c = 'Visa',entityType__c = 'order', eventDate__c = '', eventSourceID__c = '123456',
                                                           invoiceDate__c = String.ValueOf(Date.today().addMonths(2)), invoiceNumber__c = '', isSignatureRequired__c = false, Line_Items__c = JSON.serialize(lstOLI),
                                                           orderNumber__c = lstOrder[0].OrderNumber, paymentTerm__c = '', pricebookName__c = 'DE Netto-Preis Cash',
                                                           rgaNumber__c = '', scheduledShipDate__c = '', shippingAddress1__c = '10255 W Higgins Rd',
                                                           shippingAddress2__c = '10255 W Higgins Rd', shippingAddress3__c = '10255 W Higgins Rd', shippingAddressAccountId__c = lstAccount[0].Id, 
                                                           shippingAddressBusinessName__c = 'test@123', shippingAddressCity__c = 'Rosemont1',
                                                           shippingAddressCountry__c = 'Germany', shippingAddressCountryCode__c = 'DE',
                                                           shippingAddressFirstName__c = 'test', shippingAddressIsLocked__c = false, shippingAddressLastName__c = 'Test',
                                                           shippingAddressPostalCode__c = '60089', shippingAddressPrimaryPhone__c = '1234567890',
                                                           shippingAddressStateProvince__c = '', shippingMethod__c = '000001_CADS_D_3DS', shippingNotes__c = '');
        Test.startTest();
        Database.SaveResult sr = EventBus.publish(oEvent);
        Test.stopTest();
    }
    
    @isTest private static void test(){
        Account payorAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'DE Payor', 'Germany')[0];
        List<Account> lstAccount = [SELECT Id, Name FROM Account];
        List<PEClsHandleOrderEvents.OrderLineItem> lstOLI = new List<PEClsHandleOrderEvents.OrderLineItem>();
        for(Product2 product : [SELECT Id, Name FROM Product2]){
            lstOLI.add(new PEClsHandleOrderEvents.OrderLineItem(product.Id, 1, 10));
        }
        List<Product2> lstProduct = [SELECT Id, Name FROM Product2];
         //Query for the Address record types
        List<RecordType> rtypes = [Select Name, Id From RecordType 
                               where sObjectType='Address__c' and isActive=true];
    
        //Create a map between the Record Type Name and Id 
        Map<String,String> addRecordTypes = new Map<String,String>();
        for(RecordType rt: rtypes) {
        addRecordTypes.put(rt.Name,rt.Id);
        }     	
        String recordTypeId = addRecordTypes.get('DE Address');
        List<Address__c> lstAddress = new List<Address__c>{
                                                            new Address__c(Primary_Phone__c = '9876543210',RecordTypeId = recordTypeId, Business_Name__c = 'Test', Account__c = lstAccount[0].Id,Type__c = 'Bill To', First_Name__c = 'Test', Last_Name__c = 'Test', Country__c = 'Germany', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Primary_Phone__c = '1234567890', RecordTypeId = recordTypeId,Business_Name__c = 'Test', Account__c = lstAccount[0].Id,Type__c = 'Ship To', First_Name__c = 'Test', Last_Name__c = 'Test', Country__c = 'Germany', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = payorAccount.Id,RecordTypeId = recordTypeId,Type__c = 'Bill To', Country__c = 'Germany', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = payorAccount.Id,RecordTypeId = recordTypeId,Type__c = 'Ship To',Country__c = 'Germany', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                                                          };
        insert lstAddress;
        List<PricebookEntry> lstPBE = [SELECT Id, Pricebook2Id FROM PricebookEntry WHERE Pricebook2.Name = 'DE Netto-Preis Cash'];
        Order objOrder = new Order(AccountId = lstAccount[0].Id, EffectiveDate = Date.today(), Status = 'Draft', Type = '', Payor__c = payorAccount.Id, Pricebook2Id = lstPBE[0].Pricebook2Id);
        insert objOrder;
        List<OrderItem> lstOrderItem = new List<OrderItem>();
        for(PricebookEntry pbe : lstPBE){
            lstOrderItem.add(new OrderItem(PricebookEntryId = pbe.Id, OrderId = objOrder.Id, Quantity = 1, UnitPrice = 10));
        }
        insert lstOrderItem;
        List<Order> lstOrder = [SELECT Id, OrderNumber FROM Order]; 
        CRM_Order_Event__e oEvent = new CRM_Order_Event__e(version__c = '1.0',orderType__c = 'Sales_Order', operation__c = 'update',stage__c = 'pending',eventSource__c = 'OMS',
                                                           systemOfOrigin__c = '12345', systemOfOriginID__c = 'abcdefg', accountId__c = lstAccount[0].Id, 
                                                           billingAddress1__c = '10255 W Higgins Rd', billingAddress2__c = null, billingAddress3__c = null, 
                                                           billingAddressAccountID__c = lstAccount[0].Id, billingAddressBusinessName__c = 'Test', billingAddressCity__c = 'Rosemont',
                                                           billingAddressCountry__c = 'Germany', billingAddressCountryCode__c = 'DE', billingAddressFirstName__c = 'Test', 
                                                           billingAddressIsLocked__c = false, billingAddressLastName__c = 'Test', billingAddressPostalCode__c = '60089',
                                                           billingAddressPrimaryPhone__c = '9876543210', billingAddressStateProvince__c = '', creditCardAuthorizationCode__c = '12356890qwertyuiosd',
                                                           billingAddressId__c = lstAddress[0].Id,shippingAddressId__c = lstAddress[1].Id,
                                                           creditCardExpirationDate__c = '0421',creditCardId__c = '', creditCardToken__c = '1234567890qwetyuio',
                                                           creditCardType__c = 'Visa',entityType__c = 'order', eventDate__c = '', eventSourceID__c = '123456',
                                                           invoiceDate__c = String.ValueOf(Date.today().addMonths(2)), invoiceNumber__c = '', isSignatureRequired__c = false, Line_Items__c = JSON.serialize(lstOLI),
                                                           orderNumber__c = lstOrder[0].OrderNumber, paymentTerm__c = '', pricebookName__c = 'DE Netto-Preis Cash',
                                                           rgaNumber__c = '', scheduledShipDate__c = '', shippingAddress1__c = '10255 W Higgins Rd',
                                                           shippingAddress2__c = null, shippingAddress3__c = null, shippingAddressAccountId__c = lstAccount[0].Id, 
                                                           shippingAddressBusinessName__c = 'Test', shippingAddressCity__c = 'Rosemont',
                                                           shippingAddressCountry__c = 'Germany', shippingAddressCountryCode__c = 'DE',
                                                           shippingAddressFirstName__c = 'test', shippingAddressIsLocked__c = false, shippingAddressLastName__c = 'Test',
                                                           shippingAddressPostalCode__c = '60089', shippingAddressPrimaryPhone__c = '1234567890',
                                                           shippingAddressStateProvince__c = '', shippingMethod__c = '000001_CADS_D_3DS', shippingNotes__c = '');
        PEClsHandleOrderEvents.parseValue('');
        PEClsHandleOrderEvents.createUniqueKey(lstAddress[0]);
        PEClsHandleOrderEvents.findDuplicateAddress(new Map<String, Address__c>{'12345abcdefg' => lstAddress[0]});
        lstOrder = PEClsHandleOrderEvents.getOrders(new Set<String>{objOrder.Id}, new Set<String>(), new Set<String>());
        PEClsHandleOrderEvents.parseOrderType('Test', 'OMS');
        PEClsHandleOrderEvents.mappingOrderEvent(lstOrder[0], null, null, 'completed', 'update');
        PEClsHandleOrderEvents.publishOrderEvent(new Set<String>{objOrder.Id}, new Set<String>(), 'update');
        PEClsHandleOrderEvents.mappingFinancialDetail(oEvent, new Order());
        PEClsHandleOrderEvents.addressMapping(oEvent, null, null, 'BillTo');
        PEClsHandleOrderEvents.isShippingAddressChanged(lstAddress[0], oEvent);
        PEClsHandleOrderEvents.isBillingAddressChanged(lstAddress[0], oEvent);
        PEClsHandleOrderEvents.orderMapping(oEvent, null, null, null, null, null, new Order(), null, 'CA STANDARD', 'create');
    }

}