src/objects/Address__c.object
<CustomObject>
    <description>Created this custom object to track Address information.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Straße, Hausnummer</inlineHelpText>
        <label>Address Line 1</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>City</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>System_Of_Origin_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>System Of Origin ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Of_Origin__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>System Of Origin</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bill To</fullName>
                </value>
                <value>
                    <fullName>Ship To</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CRM_Error_Event_In__e.object
<CustomObject>
    <fields>
        <fullName>code__c</fullName>
        <label>code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>entityType__c</fullName>
        <label>entityType</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eventSource__c</fullName>
        <label>eventSource</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>key__c</fullName>
        <label>key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>message__c</fullName>
        <label>message</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>payload__c</fullName>
        <label>payload</label>
        <length>100000</length>
        <type>LongTextArea</type>
    </fields>
    <label>CRM Error Event In</label>
    <pluralLabel>CRM Error Events In</pluralLabel>
</CustomObject>

src/objects/Platform_Event_Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>EventSource__c</fullName>
        <description>Source of the Event. In Publish scenario, it is SELF.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>SELF or some external system that created the source event.</inlineHelpText>
        <label>EventSource</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Error__c</fullName>
        <description>Full exception error message.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Full exception error message.</inlineHelpText>
        <label>Event</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Platform Event Error Log</label>
    <nameField>
        <displayFormat>PEEL-{0000000}</displayFormat>
        <label>Error</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Platform Event Error Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Liechtenstein</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <customValue>
        <fullName>Ireland</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Chile</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Spain</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong</fullName>
    </customValue>
    <customValue>
        <fullName>Hungary</fullName>
    </customValue>
    <customValue>
        <fullName>Israel</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Jordan</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <customValue>
        <fullName>Korea</fullName>
    </customValue>
    <customValue>
        <fullName>Kuwait</fullName>
    </customValue>
    <customValue>
        <fullName>Lebanon</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>Norway</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>Oman</fullName>
    </customValue>
    <customValue>
        <fullName>Poland</fullName>
    </customValue>
    <description>Global picklist will be used in various places</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

src/classes/ClsTestTrgCRMErrorEventIn.cls
/****************************************************************************************************************
@Author        : Kumar Navneet
@Date Created    : 27/11/2019
@Description    : Test class for TrgCRMErrorEventIn 
****************************************************************************************************************/
@isTest()
private class ClsTestTrgCRMErrorEventIn  {
	
    @isTest private static void test(){
        
        List<Platform_Event_Error_Log__c> platfrm= new List<Platform_Event_Error_Log__c>();
        for(Integer i=0 ;i <200;i++)
        {
            Platform_Event_Error_Log__c pfe = new Platform_Event_Error_Log__c();
            pfe.Exception_Error__c ='Logging incoming Event'+i;
           
            platfrm.add(pfe);
        }
        
        insert platfrm;
        List<CRM_Error_Event_In__e> lstEvnt = new List<CRM_Error_Event_In__e>();
        CRM_Error_Event_In__e  oEvent = new CRM_Error_Event_In__e (code__c = 'Test',entityType__c = 'Sales_Order', eventSource__c = 'update', payload__c ='Test',
                                                        		  message__c = 'ESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTEST');
        lstEvnt.add(oEvent); 
        ClsPlatformEventErrorLogHandler.handleInboundErrors(lstEvnt);
        System.debug('====oEvent===='+JSON.serialize(oEvent));
        Test.startTest();        	
            Database.SaveResult sr = EventBus.publish(oEvent);
        Test.stopTest();
    }
     @isTest private static void testAddressErr(){
        List<CRM_Error_Event_In__e> lstEvnt = new List<CRM_Error_Event_In__e>();
         Account payorAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'DE Payor', 'Germany')[0];
        List<Account> lstAccount = [SELECT Id, Name FROM Account];
        Id recordTypeId = Schema.SObjectType.Address__c.getRecordTypeInfosByName().get('DE Address').getRecordTypeId(); 
        //String recordTypeId = addRecordTypes.get('DE Address');
        List<Address__c> lstAddress = new List<Address__c>{
                                                            new Address__c(Account__c = lstAccount[0].Id,RecordTypeId = recordTypeId,Type__c = 'Bill To', Country__c = 'Germany', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = lstAccount[0].Id,RecordTypeId = recordTypeId,Type__c = 'Ship To',Country__c = 'Germany', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                                                          };
        insert lstAddress;
        CRM_Error_Event_In__e  oEvent = new CRM_Error_Event_In__e (code__c = 'Test',entityType__c = 'address', eventSource__c = 'update', payload__c ='Test',
                                                        		   key__c = lstAddress[0].Id,
                                                                   message__c = 'ESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTEST');
        lstEvnt.add(oEvent); 
        ClsPlatformEventErrorLogHandler.handleInboundErrors(lstEvnt);
         lstEvnt.clear();
         CRM_Error_Event_In__e  oEvent1 = new CRM_Error_Event_In__e (code__c = 'Test',entityType__c = 'account', eventSource__c = 'update', payload__c ='Test',
                                                        		   key__c = lstAccount[0].Id,
                                                                   message__c = 'ESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTEST');
        lstEvnt.add(oEvent1); 
        ClsPlatformEventErrorLogHandler.handleInboundErrors(lstEvnt);
        
    }
   
}