src/objects/Address__c.object
<CustomObject>
    <description>Created this custom object to track Address information.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Straße, Hausnummer</inlineHelpText>
        <label>Address Line 1</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>City</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>System_Of_Origin_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>System Of Origin ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Of_Origin__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>System Of Origin</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bill To</fullName>
                </value>
                <value>
                    <fullName>Ship To</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Finance_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Finance Details</relationshipLabel>
        <relationshipName>Finance_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Card Token</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>Finance Detail</label>
    <nameField>
        <displayFormat>FD-{0000}</displayFormat>
        <label>Finance Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Details</pluralLabel>
    <recordTypes>
        <fullName>Credit_Card</fullName>
        <active>true</active>
        <label>Credit Card</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SSIP_Rule__c.object
<CustomObject>
    <description>Object stores all SSIP rule for the customers.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Master detail relationship to the account.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SSIP Rule</relationshipLabel>
        <relationshipName>SSIP_Rule</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country to which this rule is tied to</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>First Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>SSIP Rule</relationshipLabel>
        <relationshipName>SSIP_Rule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Repeat_Order_Lead_Days__c</fullName>
        <inlineHelpText>Lead days for the first shipment</inlineHelpText>
        <label>First Repeat Order Lead Days</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>First_Shipment_Date__c</fullName>
        <description>Date when the first shipment needs to happen for this Schedule. It cam be immediate or in the future and should fall between the Rule Start and End date.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Date should be within the Rule Start Date and Rule End Date (if applicable). This date is set with the first order is shipped. Setting this date will create the Schedules.</inlineHelpText>
        <label>First Shipment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Frequency_In_Days__c</fullName>
        <description>Schedule interval between each shipments.</description>
        <label>Frequency (In Days)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Term__c</fullName>
        <defaultValue>IF( $RecordType.DeveloperName = &apos;CH_SSIP_Rule&apos;, &apos;net30&apos;, &apos;net30&apos;)</defaultValue>
        <description>Payment terms that will be used to track the payment. The default value will be based on the country&apos; preference</description>
        <label>Payment Term</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Payment_Term</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PriceBookEntryId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>PriceBookEntryId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Price book, which will filter out only SSIP Pricebooks</description>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>SSIP Rule</relationshipLabel>
        <relationshipName>SSIP_Rule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>SSIP Rule</relationshipLabel>
        <relationshipName>SSIP_Rule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Product quantity populated based on the product that is chosen. Information is recorded in the pricebook entry level.</description>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rule_Re_schedule_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Rule Re-schedule Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Schedule_Count__c</fullName>
        <description>Field holds the number of Schedules that can be created for this rule.</description>
        <inlineHelpText>Count determines how many schedules will be created at first for this Rule.</inlineHelpText>
        <label>Schedule Count</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shipping_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>List of all Ship To addresses tied to the customer.</description>
        <label>Shipping Address</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Address__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Address__c.Type__c</field>
                <operation>equals</operation>
                <value>Ship To</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>SSIP Rule</relationshipLabel>
        <relationshipName>SSIP_Rule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&apos;Active&apos;</defaultValue>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SSIP Rule</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SSIP Rule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SSIP_Schedule__c.object
<CustomObject>
    <description>Object stores all the schedules related to the rule.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Will be referencing the grand parent and will be defaulted at the time of the Schedule creation. Need this for constraining the addressed tied to the customer.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SSIP Schedule</relationshipLabel>
        <relationshipName>SSIP_Schedule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Will be defaulted from SSIP Rule at the time of creation.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Shipment_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Scheduled Shipment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>SSIP Schedule</relationshipLabel>
        <relationshipName>SSIP_Schedule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Term__c</fullName>
        <description>Will be defaulted from Parent SSIP Rule</description>
        <label>Payment Term</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Payment_Term</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rescheduled_Shipment_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Rescheduled Shipment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SSIP_Rule__c</fullName>
        <description>Master Detail relationship to the parent Rule.</description>
        <label>SSIP Rule</label>
        <referenceTo>SSIP_Rule__c</referenceTo>
        <relationshipLabel>SSIP Schedule</relationshipLabel>
        <relationshipName>SSIP_Schedule</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Shipping_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>List of all Ship To addresses tied to the customer.</description>
        <label>Changed Shipping Address</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Address__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Address__c.Type__c</field>
                <operation>equals</operation>
                <value>Ship To</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>SSIP Schedule</relationshipLabel>
        <relationshipName>SSIP_Schedule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&apos;Open&apos;</defaultValue>
        <description>Will be defaulted to Open. Depending on the Order processing other values will be set.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>In Error</fullName>
                </value>
                <value>
                    <fullName>In Draft</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SSIP Schedule</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SSIP Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Liechtenstein</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <customValue>
        <fullName>Ireland</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Chile</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Spain</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong</fullName>
    </customValue>
    <customValue>
        <fullName>Hungary</fullName>
    </customValue>
    <customValue>
        <fullName>Israel</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Jordan</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <customValue>
        <fullName>Korea</fullName>
    </customValue>
    <customValue>
        <fullName>Kuwait</fullName>
    </customValue>
    <customValue>
        <fullName>Lebanon</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>Norway</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>Oman</fullName>
    </customValue>
    <customValue>
        <fullName>Poland</fullName>
    </customValue>
    <description>Global picklist will be used in various places</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

src/globalValueSets/Payment_Term.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>net30</fullName>
        <label>30 NET</label>
    </customValue>
    <customValue>
        <fullName>45 NET</fullName>
    </customValue>
    <customValue>
        <fullName>Check(Net 10)</fullName>
    </customValue>
    <customValue>
        <fullName>Credit Card</fullName>
        <label>0 NET</label>
    </customValue>
    <customValue>
        <fullName>Insurance 30</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance 45</fullName>
    </customValue>
    <customValue>
        <fullName>No Charge</fullName>
    </customValue>
    <customValue>
        <fullName>net0</fullName>
        <label>Credit Card</label>
    </customValue>
    <customValue>
        <fullName>net60</fullName>
        <label>60 NET</label>
    </customValue>
    <customValue>
        <fullName>net90</fullName>
        <label>90 NET</label>
    </customValue>
    <customValue>
        <fullName>net-1</fullName>
        <label>Prepaid</label>
    </customValue>
    <masterLabel>Payment Term</masterLabel>
</GlobalValueSet>

src/classes/SSIPRuleTriggerHandler_Test.cls
@isTest()
private class SSIPRuleTriggerHandler_Test { 
	@testSetup static void setup() {
        Map<String, String> mapPriceBook = ClsTestDataFactory.createCPB(new List<String>{'CH Cash','DE Netto-Preis Cash'}, 'CHF');        
        Map<String, Id> mapProduct = ClsTestDataFactory.createProducts(new List<String>{'Product-01', 'Product-02', 'Product-03', 'DEX-SHIP-01'});
        Map<Id, Decimal> productIdToPriceMap = new Map<Id, Decimal>{mapProduct.values()[0] => 10, mapProduct.values()[1] => 0, mapProduct.values()[2] => 0 };
        Map<Id, Id> mapPBE = ClsTestDataFactory.CreateCPBEntries(productIdToPriceMap, mapPriceBook.get('CH Cash'), 'CHF');
    }
    
    // for Class BClsSSIPSchedule
    @isTest private static void test1(){
		//Id rtId = Schema.SObjectType.Order.getRecordTypeInfosByName().get('CH Sales Order').getRecordTypeId();  
        Id chOrderRecdTypeId = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('CH_Sales_Order').getRecordTypeId();
        Account payorAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'CH Consumer', 'Switzerland')[0];
        payorAccount.Credit_Hold__c = false;
        update payorAccount;
        List<Account> lstAccount = [SELECT Id, Name,Credit_Hold__c FROM Account where Credit_Hold__c=false];
        System.debug('lstAccount--'+lstAccount);
        List<PEClsHandleOrderEvents.OrderLineItem> lstOLI = new List<PEClsHandleOrderEvents.OrderLineItem>();
        for(Product2 product : [SELECT Id, Name FROM Product2]){
            lstOLI.add(new PEClsHandleOrderEvents.OrderLineItem(product.Id, 1, 10));
        }
        List<Product2> lstProduct = [SELECT Id, Name FROM Product2];
        List<Address__c> lstAddress = new List<Address__c>{
                                                            new Address__c(Account__c = lstAccount[0].Id,Type__c = 'Bill To', Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = lstAccount[0].Id,Type__c = 'Ship To',Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = payorAccount.Id,Type__c = 'Bill To', Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = payorAccount.Id,Type__c = 'Ship To',Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = ' W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                                                          };
        insert lstAddress;
        List<PricebookEntry> lstPBE = [SELECT Id, Pricebook2Id, Product2Id FROM PricebookEntry WHERE Pricebook2.Name = 'CH Cash'];
        Order objOrder = new Order(AccountId = lstAccount[0].Id, EffectiveDate = Date.today(), Status = 'Draft', Type = 'CH STANDARD', 
                                   //Payor__c = payorAccount.Id,
                                   Pricebook2Id = lstPBE[0].Pricebook2Id,
                                   RecordTypeId = chOrderRecdTypeId, CurrencyISOCode = 'CHF');
        insert objOrder;
        List<OrderItem> lstOrderItem = new List<OrderItem>();
        lstOrderItem.add(new OrderItem(PricebookEntryId = lstPBE[0].Id, OrderId = objOrder.Id, Quantity = 1, UnitPrice = 10));
        insert lstOrderItem;
        
        List<SSIP_Rule__c> lstSSIPRule = new List<SSIP_Rule__c>();
        for(PricebookEntry pbe : lstPBE){
            lstSSIPRule.add(new SSIP_Rule__c(Account__c = lstAccount[0].Id, First_Order__c = objOrder.Id, Schedule_Count__c = 1, Frequency_In_Days__c = 30,
                                             First_Repeat_Order_Lead_Days__c = 7, Price_Book__c = pbe.Pricebook2Id, PriceBookEntryId__c = pbe.Id,
                                             First_Shipment_Date__c = Date.today(),Rule_Re_schedule_Date__c = Date.today()+1,
                                             Product__c = pbe.Product2Id, Quantity__c = 1, Shipping_Address__c = lstAddress[1].Id, Status__c = 'Active'));
        }
        
        insert lstSSIPRule;
        for(SSIP_Rule__c ssipRule : lstSSIPRule){
            ssipRule.First_Shipment_Date__c = Date.today();
            ssipRule.Rule_Re_schedule_Date__c = Date.today()+1;
        }
        //update lstSSIPRule;
        
        List<SSIP_Schedule__c> lstSSIPSchedule = [SELECT Id,Account__c FROM SSIP_Schedule__c where Account__c=: payorAccount.Id];
        for(SSIP_Schedule__c ssipSchedule : lstSSIPSchedule){
            ssipSchedule.Rescheduled_Shipment_Date__c = Date.today();
         
        }
        System.debug('====lstSSIPSchedule===='+lstSSIPSchedule);
        update lstSSIPSchedule;
        
        test.startTest();
        DataBase.executeBatch(new BClsSSIPSchedule());
        test.stopTest();
    }
    @isTest private static void test2(){
		//Id rtId = Schema.SObjectType.Order.getRecordTypeInfosByName().get('CH Sales Order').getRecordTypeId();  
        Id chOrderRecdTypeId = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('CH_Sales_Order').getRecordTypeId();
        Account payorAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'CH Consumer', 'Switzerland')[0];
        
        List<Account> lstAccount = [SELECT Id, Name,Credit_Hold__c FROM Account];
        System.debug('lstAccount--'+lstAccount);
        List<PEClsHandleOrderEvents.OrderLineItem> lstOLI = new List<PEClsHandleOrderEvents.OrderLineItem>();
        for(Product2 product : [SELECT Id, Name FROM Product2]){
            lstOLI.add(new PEClsHandleOrderEvents.OrderLineItem(product.Id, 1, 10));
        }
        List<Product2> lstProduct = [SELECT Id, Name FROM Product2];
        List<Address__c> lstAddress = new List<Address__c>{
                                                            new Address__c(Account__c = lstAccount[0].Id,Type__c = 'Bill To', Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = lstAccount[0].Id,Type__c = 'Ship To',Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = payorAccount.Id,Type__c = 'Bill To', Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = payorAccount.Id,Type__c = 'Ship To',Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = ' W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                                                          };
        insert lstAddress;
        List<PricebookEntry> lstPBE = [SELECT Id, Pricebook2Id, Product2Id FROM PricebookEntry WHERE Pricebook2.Name = 'CH Cash'];
        Order objOrder = new Order(AccountId = lstAccount[0].Id, EffectiveDate = Date.today(), Status = 'Draft', Type = 'CH STANDARD', 
                                   //Payor__c = payorAccount.Id,
                                   Pricebook2Id = lstPBE[0].Pricebook2Id,
                                   RecordTypeId = chOrderRecdTypeId, CurrencyISOCode = 'CHF');
        insert objOrder;
        // Dont insert the Order
        payorAccount.Credit_Hold__c = true;
        //payorAccount.RecordTypeId = null;
        update payorAccount;
        List<OrderItem> lstOrderItem = new List<OrderItem>();
        lstOrderItem.add(new OrderItem(PricebookEntryId = lstPBE[0].Id, OrderId = objOrder.Id, Quantity = 1, UnitPrice = 10));
        insert lstOrderItem;
        
        List<SSIP_Rule__c> lstSSIPRule = new List<SSIP_Rule__c>();
        for(PricebookEntry pbe : lstPBE){
            lstSSIPRule.add(new SSIP_Rule__c(Account__c = lstAccount[0].Id, First_Order__c = objOrder.Id, Schedule_Count__c = 1, Frequency_In_Days__c = 30,
                                             First_Repeat_Order_Lead_Days__c = 7, Price_Book__c = pbe.Pricebook2Id, PriceBookEntryId__c = pbe.Id,
                                             First_Shipment_Date__c = Date.today(),Rule_Re_schedule_Date__c = Date.today()+1,
                                             Product__c = pbe.Product2Id, Quantity__c = 1, Shipping_Address__c = null, Status__c = 'Active'));
        }
        
        insert lstSSIPRule;
        for(SSIP_Rule__c ssipRule : lstSSIPRule){
            ssipRule.First_Shipment_Date__c = Date.today();
            ssipRule.Rule_Re_schedule_Date__c = Date.today()+1;
        }
       // update lstSSIPRule;
        
        List<SSIP_Schedule__c> lstSSIPSchedule = [SELECT Id,Account__c FROM SSIP_Schedule__c where Account__c=: payorAccount.Id];
        for(SSIP_Schedule__c ssipSchedule : lstSSIPSchedule){
            ssipSchedule.Rescheduled_Shipment_Date__c = Date.today();
           ssipSchedule.Payment_Term__c = 'net0';
        }
        System.debug('====lstSSIPSchedule===='+lstSSIPSchedule);
        update lstSSIPSchedule;
        
        test.startTest();
        DataBase.executeBatch(new BClsSSIPSchedule());
        test.stopTest();
    }
    @isTest private static void test3(){
		//Id rtId = Schema.SObjectType.Order.getRecordTypeInfosByName().get('CH Sales Order').getRecordTypeId();  
        Id chOrderRecdTypeId = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('CH_Sales_Order').getRecordTypeId();
        Account payorAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'CH Consumer', 'Switzerland')[0];
        
        List<Account> lstAccount = [SELECT Id, Name,Credit_Hold__c FROM Account];
        System.debug('lstAccount--'+lstAccount);
        List<PEClsHandleOrderEvents.OrderLineItem> lstOLI = new List<PEClsHandleOrderEvents.OrderLineItem>();
        for(Product2 product : [SELECT Id, Name FROM Product2]){
            lstOLI.add(new PEClsHandleOrderEvents.OrderLineItem(product.Id, 1, 10));
        }
        List<Product2> lstProduct = [SELECT Id, Name FROM Product2];
        List<Address__c> lstAddress = new List<Address__c>{
                                                            new Address__c(Account__c = lstAccount[0].Id,Type__c = 'Bill To', Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = lstAccount[0].Id,Type__c = 'Ship To',Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = payorAccount.Id,Type__c = 'Bill To', Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = payorAccount.Id,Type__c = 'Ship To',Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = ' W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                                                          };
        insert lstAddress;
        List<PricebookEntry> lstPBE = [SELECT Id, Pricebook2Id, Product2Id FROM PricebookEntry WHERE Pricebook2.Name = 'CH Cash'];
        Order objOrder = new Order(AccountId = lstAccount[0].Id, EffectiveDate = Date.today(), Status = 'Draft', Type = 'CH STANDARD', 
                                   //Payor__c = payorAccount.Id,
                                   Pricebook2Id = lstPBE[0].Pricebook2Id,
                                   RecordTypeId = chOrderRecdTypeId, CurrencyISOCode = 'CHF');
        insert objOrder;
        List<OrderItem> lstOrderItem = new List<OrderItem>();
        lstOrderItem.add(new OrderItem(PricebookEntryId = lstPBE[0].Id, OrderId = objOrder.Id, Quantity = 1, UnitPrice = 10));
        insert lstOrderItem;
        
        List<SSIP_Rule__c> lstSSIPRule = new List<SSIP_Rule__c>();
        for(PricebookEntry pbe : lstPBE){
            lstSSIPRule.add(new SSIP_Rule__c(Account__c = lstAccount[0].Id, First_Order__c = objOrder.Id, Schedule_Count__c = 1, Frequency_In_Days__c = 30,
                                             First_Repeat_Order_Lead_Days__c = 7, Price_Book__c = pbe.Pricebook2Id, PriceBookEntryId__c = pbe.Id,
                                             First_Shipment_Date__c = Date.today(),Rule_Re_schedule_Date__c = Date.today()+1,
                                             Product__c = pbe.Product2Id, Quantity__c = 1, Shipping_Address__c = null, Status__c = 'Active'));
        }
        
        insert lstSSIPRule;
        for(SSIP_Rule__c ssipRule : lstSSIPRule){
            ssipRule.First_Shipment_Date__c = Date.today();
            ssipRule.Rule_Re_schedule_Date__c = Date.today()+1;
        }
       // update lstSSIPRule;
        
        List<SSIP_Schedule__c> lstSSIPSchedule = [SELECT Id,Account__c FROM SSIP_Schedule__c where Account__c=: payorAccount.Id];
        for(SSIP_Schedule__c ssipSchedule : lstSSIPSchedule){
            ssipSchedule.Rescheduled_Shipment_Date__c = Date.today();
           ssipSchedule.Payment_Term__c = 'net0';
        }
        System.debug('====lstSSIPSchedule===='+lstSSIPSchedule);
        update lstSSIPSchedule;
        
        test.startTest();
        DataBase.executeBatch(new BClsSSIPSchedule());
        test.stopTest();
    }
    //For class SSIPScheduleJobUtiltiy
    @isTest private static void test4(){ 
         
         
         Id chOrderRecdTypeId = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('CH_Sales_Order').getRecordTypeId();
        
		Account payorAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'CH Consumer', 'Switzerland')[0];
        payorAccount.Subscription_Pending_Payments__c = 1;
         update payorAccount;
        List<Account> lstAccount = [SELECT Id, Name,Credit_Hold__c FROM Account where Subscription_Pending_Payments__c >0];
       
        List<Product2> lstProduct = [SELECT Id, Name FROM Product2]; 
        List<Address__c> lstAddress = new List<Address__c>{
                                                            new Address__c(Account__c = lstAccount[0].Id,Type__c = 'Bill To', Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = lstAccount[0].Id,Type__c = 'Ship To',Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = payorAccount.Id,Type__c = 'Bill To', Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = payorAccount.Id,Type__c = 'Ship To',Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = ' W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                                                          };
        insert lstAddress;
         
         Id rtIdFDCC = Schema.SObjectType.Finance_Detail__c.getRecordTypeInfosByDeveloperName().get('Credit_Card').getRecordTypeId();
        Finance_Detail__c fd1= new Finance_Detail__c(Account__c=payorAccount.Id,Token__c='1111', Card_Type__c='Mastercard',CC_CUR__c='CHF',
                                                     Expiry_Date__c='1112/21', Primary__c=true, CC_Address__c=lstAddress[0].id, RecordTypeId=rtIdFDCC);
        insert fd1;
        List<PricebookEntry> lstPBE = [SELECT Id,Name, Pricebook2Id, Product2Id FROM PricebookEntry WHERE Pricebook2.Name = 'CH Cash'];
       Order objOrder = new Order(AccountId = payorAccount.Id, EffectiveDate = Date.today(), Status = 'Draft', Type = 'CH STANDARD', 
                                   Pricebook2Id = lstPBE[0].Pricebook2Id,
                                   Payment_Terms__c = 'net30',
                                   Finance_Detail__c = fd1.Id,
                                   RecordTypeId = chOrderRecdTypeId, CurrencyISOCode = 'CHF');
        insert objOrder;
        List<OrderItem> lstOrderItem = new List<OrderItem>();
        lstOrderItem.add(new OrderItem(PricebookEntryId = lstPBE[0].Id, OrderId = objOrder.Id, Quantity = 1, UnitPrice = 10));
        insert lstOrderItem;
        
        List<SSIP_Rule__c> lstSSIPRule = new List<SSIP_Rule__c>();
        for(PricebookEntry pbe : lstPBE){ // First_Order__c = objOrder.Id,
            System.debug('***pbe--'+pbe.Name);
            Integer fr = 0;
            Integer Ld = 0;
            Integer Quant = 0;
            if(pbe.Name == 'Product-01'){
                fr = 30;
                Ld = 0;
                Quant = 1;
                
            }else if(pbe.Name == 'Product-02'){
                fr = 90;
                Ld = 10;
                Quant = 3;
            }else{
                fr = 90;
                Ld = 10;
                Quant = 1;
            }
            lstSSIPRule.add(new SSIP_Rule__c(Account__c = lstAccount[0].Id, Schedule_Count__c = 1, Frequency_In_Days__c = fr,Payment_term__c ='net0',
                                             First_Repeat_Order_Lead_Days__c = Ld, Price_Book__c = pbe.Pricebook2Id, PriceBookEntryId__c = pbe.Id,
                                             Product__c = pbe.Product2Id,First_Shipment_Date__c = Date.today(),Rule_Re_schedule_Date__c = Date.today()+1,
                                             Quantity__c = Quant, Shipping_Address__c = null, Status__c = 'Active'));
        }
        
        insert lstSSIPRule;      
       
        List<SSIP_Schedule__c> lstSSIPSchedule = [SELECT Id,Account__c FROM SSIP_Schedule__c where Account__c=: payorAccount.Id];
        for(SSIP_Schedule__c ssipSchedule : lstSSIPSchedule){
            ssipSchedule.Rescheduled_Shipment_Date__c = Date.today();
            ssipSchedule.Payment_Term__c = 'net0';
        }
        
        update lstSSIPSchedule;
        System.debug('====lstSSIPSchedule===='+lstSSIPSchedule);
       test.startTest();            
       System.enqueueJob(new SSIPScheduleJobUtiltiy.CalculateTaxQueueable(objOrder.Id, objOrder.Payment_Terms__c,
                                                                          'CH',//objOrder.Account.RecordType.Name.substring(0,2)
                                                                          (Integer) objOrder.Count_of_Order_Line_Items__c,
                                                                          (Integer) objOrder.Account.Subscription_Pending_Payments__c,
                                                                          objOrder.AccountId, true));
        test.stopTest();
    }
    @isTest private static void testSheduleException(){ 
         
         
         Id chOrderRecdTypeId = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('CH_Sales_Order').getRecordTypeId();
        
		Account payorAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'CH Consumer', 'Switzerland')[0];
        payorAccount.Subscription_Pending_Payments__c = 1;
         update payorAccount;
        List<Account> lstAccount = [SELECT Id, Name,Credit_Hold__c FROM Account where Subscription_Pending_Payments__c >0];
       
        List<Product2> lstProduct = [SELECT Id, Name FROM Product2]; 
        List<Address__c> lstAddress = new List<Address__c>{
                                                            new Address__c(Account__c = lstAccount[0].Id,Type__c = 'Bill To', Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = lstAccount[0].Id,Type__c = 'Ship To',Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = payorAccount.Id,Type__c = 'Bill To', Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = payorAccount.Id,Type__c = 'Ship To',Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = ' W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                                                          };
        insert lstAddress;
         
         Id rtIdFDCC = Schema.SObjectType.Finance_Detail__c.getRecordTypeInfosByDeveloperName().get('Credit_Card').getRecordTypeId();
        Finance_Detail__c fd1= new Finance_Detail__c(Account__c=payorAccount.Id,Token__c='1111', Card_Type__c='Mastercard',CC_CUR__c='CHF',
                                                     Expiry_Date__c='1112/21', Primary__c=true, CC_Address__c=lstAddress[0].id, RecordTypeId=rtIdFDCC);
        insert fd1;
        List<PricebookEntry> lstPBE = [SELECT Id,Name, Pricebook2Id, Product2Id FROM PricebookEntry WHERE Pricebook2.Name = 'CH Cash'];
       Order objOrder = new Order(AccountId = payorAccount.Id, EffectiveDate = Date.today(), Status = 'Draft', Type = 'CH STANDARD', 
                                   Pricebook2Id = lstPBE[0].Pricebook2Id,
                                   Payment_Terms__c = 'net0',
                                   Finance_Detail__c = fd1.Id,
                                   RecordTypeId = chOrderRecdTypeId, CurrencyISOCode = 'CHF');
        insert objOrder;
        List<OrderItem> lstOrderItem = new List<OrderItem>();
        lstOrderItem.add(new OrderItem(PricebookEntryId = lstPBE[0].Id, OrderId = objOrder.Id, Quantity = 1, UnitPrice = 10));
        insert lstOrderItem;
        
        List<SSIP_Rule__c> lstSSIPRule = new List<SSIP_Rule__c>();
        for(PricebookEntry pbe : lstPBE){ // First_Order__c = objOrder.Id,
            System.debug('***pbe--'+pbe.Name);
            Integer fr = 0;
            Integer Ld = 0;
            Integer Quant = 0;
            if(pbe.Name == 'Product-01'){
                fr = 30;
                Ld = 0;
                Quant = 1;
                
            }else if(pbe.Name == 'Product-02'){
                fr = 90;
                Ld = 10;
                Quant = 3;
            }else{
                fr = 90;
                Ld = 10;
                Quant = 1;
            }
            lstSSIPRule.add(new SSIP_Rule__c(Account__c = lstAccount[0].Id, Schedule_Count__c = 1, Frequency_In_Days__c = fr,Payment_term__c ='net0',
                                             First_Repeat_Order_Lead_Days__c = Ld, Price_Book__c = pbe.Pricebook2Id, PriceBookEntryId__c = pbe.Id,
                                             Product__c = pbe.Product2Id,First_Shipment_Date__c = Date.today(),Rule_Re_schedule_Date__c = Date.today()+1,
                                             Quantity__c = Quant, Shipping_Address__c = null, Status__c = 'Active'));
        }
        
        insert lstSSIPRule;      
       
        List<SSIP_Schedule__c> lstSSIPSchedule = [SELECT Id,Account__c FROM SSIP_Schedule__c where Account__c=: payorAccount.Id];
        for(SSIP_Schedule__c ssipSchedule : lstSSIPSchedule){
            ssipSchedule.Rescheduled_Shipment_Date__c = Date.today();
            ssipSchedule.Payment_Term__c = 'net0';
            ssipSchedule.Order__c = objOrder.Id;
        }
        
        update lstSSIPSchedule;
        System.debug('====lstSSIPSchedule===='+lstSSIPSchedule);
       
       	
	   test.startTest();            
       System.enqueueJob(new SSIPScheduleJobUtiltiy.CalculateTaxQueueable(objOrder.Id, objOrder.Payment_Terms__c,
                                                                          'CH',//objOrder.Account.RecordType.Name.substring(0,2)
                                                                          (Integer) objOrder.Count_of_Order_Line_Items__c,
                                                                          (Integer) objOrder.Account.Subscription_Pending_Payments__c,
                                                                          objOrder.AccountId, true));
        test.stopTest();
    }
    //For AuthorizeAndSettlePaymentQueueable
    @isTest private static void testAuthirizeSettle(){ 
         
         
         Id chOrderRecdTypeId = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('CH_Sales_Order').getRecordTypeId();
        
		Account payorAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'CH Consumer', 'Switzerland')[0];
        payorAccount.Subscription_Pending_Payments__c = 1;
         update payorAccount;
        List<Account> lstAccount = [SELECT Id, Name,Credit_Hold__c FROM Account where Subscription_Pending_Payments__c >0];
       
        List<Product2> lstProduct = [SELECT Id, Name FROM Product2]; 
        List<Address__c> lstAddress = new List<Address__c>{
                                                            new Address__c(Account__c = lstAccount[0].Id,Type__c = 'Bill To', Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = lstAccount[0].Id,Type__c = 'Ship To',Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = payorAccount.Id,Type__c = 'Bill To', Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = payorAccount.Id,Type__c = 'Ship To',Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = ' W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                                                          };
        insert lstAddress;
         
         Id rtIdFDCC = Schema.SObjectType.Finance_Detail__c.getRecordTypeInfosByDeveloperName().get('Credit_Card').getRecordTypeId();
        Finance_Detail__c fd1= new Finance_Detail__c(Account__c=payorAccount.Id,Token__c='1111', Card_Type__c='Mastercard',CC_CUR__c='CHF',
                                                     Expiry_Date__c='1112/21', Primary__c=true, CC_Address__c=lstAddress[0].id, RecordTypeId=rtIdFDCC);
        insert fd1;
        List<PricebookEntry> lstPBE = [SELECT Id,Name, Pricebook2Id, Product2Id FROM PricebookEntry WHERE Pricebook2.Name = 'CH Cash'];
       Order objOrder = new Order(AccountId = payorAccount.Id, EffectiveDate = Date.today(), Status = 'Draft', Type = 'CH STANDARD', 
                                   Pricebook2Id = lstPBE[0].Pricebook2Id,
                                   Payment_Terms__c = 'net30',
                                   Finance_Detail__c = fd1.Id,
                                   RecordTypeId = chOrderRecdTypeId, CurrencyISOCode = 'CHF');
        insert objOrder;
        List<OrderItem> lstOrderItem = new List<OrderItem>();
        lstOrderItem.add(new OrderItem(PricebookEntryId = lstPBE[0].Id, OrderId = objOrder.Id, Quantity = 1, UnitPrice = 10));
        insert lstOrderItem;
        
        List<SSIP_Rule__c> lstSSIPRule = new List<SSIP_Rule__c>();
        for(PricebookEntry pbe : lstPBE){ // First_Order__c = objOrder.Id,
            System.debug('***pbe--'+pbe.Name);
            Integer fr = 0;
            Integer Ld = 0;
            Integer Quant = 0;
            if(pbe.Name == 'Product-01'){
                fr = 30;
                Ld = 0;
                Quant = 1;
                
            }else if(pbe.Name == 'Product-02'){
                fr = 90;
                Ld = 10;
                Quant = 3;
            }else{
                fr = 90;
                Ld = 10;
                Quant = 1;
            }
            lstSSIPRule.add(new SSIP_Rule__c(Account__c = lstAccount[0].Id, Schedule_Count__c = 1, Frequency_In_Days__c = fr,Payment_term__c ='net30',
                                             First_Repeat_Order_Lead_Days__c = Ld, Price_Book__c = pbe.Pricebook2Id, PriceBookEntryId__c = pbe.Id,
                                             Product__c = pbe.Product2Id,First_Shipment_Date__c = Date.today(),Rule_Re_schedule_Date__c = Date.today()+1,
                                             Quantity__c = Quant, Shipping_Address__c = null, Status__c = 'Active'));
        }
        
        insert lstSSIPRule;      
       
        List<SSIP_Schedule__c> lstSSIPSchedule = [SELECT Id,Account__c FROM SSIP_Schedule__c where Account__c=: payorAccount.Id];
        for(SSIP_Schedule__c ssipSchedule : lstSSIPSchedule){
            ssipSchedule.Rescheduled_Shipment_Date__c = Date.today();
            ssipSchedule.Payment_Term__c = 'net30';
            ssipSchedule.Order__c = objorder.Id;
        }
        
        update lstSSIPSchedule;
        System.debug('====lstSSIPSchedule===='+lstSSIPSchedule);
        
        test.startTest();
         Test.setMock(HttpCalloutMock.class, new ClsMockHttpResponseGenCCAuthorize());
		 System.enqueueJob(new SSIPScheduleJobUtiltiy.AuthorizeAndSettlePaymentQueueable(objOrder.Id,'CH',
                                                                          (Integer) objOrder.Count_of_Order_Line_Items__c,
                                                                          (Integer) objOrder.Account.Subscription_Pending_Payments__c,
                                                                          objOrder.AccountId, true));
         
         test.stopTest();
    }
    @isTest private static void testAuthirizeSettleException(){ 
         
         
         Id chOrderRecdTypeId = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('CH_Sales_Order').getRecordTypeId();
        
		Account payorAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'CH Consumer', 'Switzerland')[0];
        payorAccount.Subscription_Pending_Payments__c = 1;
         update payorAccount;
        List<Account> lstAccount = [SELECT Id, Name,Credit_Hold__c FROM Account where Subscription_Pending_Payments__c >0];
       
        List<Product2> lstProduct = [SELECT Id, Name FROM Product2]; 
        List<Address__c> lstAddress = new List<Address__c>{
                                                            new Address__c(Account__c = lstAccount[0].Id,Type__c = 'Bill To', Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = lstAccount[0].Id,Type__c = 'Ship To',Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = payorAccount.Id,Type__c = 'Bill To', Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = payorAccount.Id,Type__c = 'Ship To',Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = ' W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                                                          };
        insert lstAddress;
         
         Id rtIdFDCC = Schema.SObjectType.Finance_Detail__c.getRecordTypeInfosByDeveloperName().get('Credit_Card').getRecordTypeId();
        Finance_Detail__c fd1= new Finance_Detail__c(Account__c=payorAccount.Id,Token__c='1111', Card_Type__c='Mastercard',CC_CUR__c='CHF',
                                                     Expiry_Date__c='1112/21', Primary__c=true, CC_Address__c=lstAddress[0].id, RecordTypeId=rtIdFDCC);
        insert fd1;
        List<PricebookEntry> lstPBE = [SELECT Id,Name, Pricebook2Id, Product2Id FROM PricebookEntry WHERE Pricebook2.Name = 'CH Cash'];
       Order objOrder = new Order(AccountId = payorAccount.Id, EffectiveDate = Date.today(), Status = 'Draft', Type = 'CH STANDARD', 
                                   Pricebook2Id = lstPBE[0].Pricebook2Id,
                                   Payment_Terms__c = 'net30',
                                   //Finance_Detail__c = fd1.Id,
                                   RecordTypeId = chOrderRecdTypeId, CurrencyISOCode = 'CHF');
        insert objOrder;
        List<OrderItem> lstOrderItem = new List<OrderItem>();
        lstOrderItem.add(new OrderItem(PricebookEntryId = lstPBE[0].Id, OrderId = objOrder.Id, Quantity = 1, UnitPrice = 10));
        insert lstOrderItem;
        
        List<SSIP_Rule__c> lstSSIPRule = new List<SSIP_Rule__c>();
        for(PricebookEntry pbe : lstPBE){ // First_Order__c = objOrder.Id,
            System.debug('***pbe--'+pbe.Name);
            Integer fr = 0;
            Integer Ld = 0;
            Integer Quant = 0;
            if(pbe.Name == 'Product-01'){
                fr = 30;
                Ld = 0;
                Quant = 1;
                
            }else if(pbe.Name == 'Product-02'){
                fr = 90;
                Ld = 10;
                Quant = 3;
            }else{
                fr = 90;
                Ld = 10;
                Quant = 1;
            }
            lstSSIPRule.add(new SSIP_Rule__c(Account__c = lstAccount[0].Id, Schedule_Count__c = 1, Frequency_In_Days__c = fr,Payment_term__c ='net30',
                                             First_Repeat_Order_Lead_Days__c = Ld, Price_Book__c = pbe.Pricebook2Id, PriceBookEntryId__c = pbe.Id,
                                             Product__c = pbe.Product2Id,First_Shipment_Date__c = Date.today(),Rule_Re_schedule_Date__c = Date.today()+1,
                                             Quantity__c = Quant, Shipping_Address__c = null, Status__c = 'Active'));
        }
        
        insert lstSSIPRule;      
       
        List<SSIP_Schedule__c> lstSSIPSchedule = [SELECT Id,Account__c FROM SSIP_Schedule__c where Account__c=: payorAccount.Id];
        for(SSIP_Schedule__c ssipSchedule : lstSSIPSchedule){
            ssipSchedule.Rescheduled_Shipment_Date__c = Date.today();
            ssipSchedule.Payment_Term__c = 'net30';
            ssipSchedule.Order__c = objorder.Id;
        }
        
        update lstSSIPSchedule;
        System.debug('====lstSSIPSchedule===='+lstSSIPSchedule);
        
        test.startTest();
         Test.setMock(HttpCalloutMock.class, new ClsMockHttpResponseGenCCAuthorize());
		 System.enqueueJob(new SSIPScheduleJobUtiltiy.AuthorizeAndSettlePaymentQueueable(objOrder.Id,'CH',
                                                                          (Integer) objOrder.Count_of_Order_Line_Items__c,
                                                                          (Integer) objOrder.Account.Subscription_Pending_Payments__c,
                                                                          objOrder.AccountId, true));
         
         test.stopTest();
                   
		
    }
    @isTest private static void testAuthirizeSettleFinanceException(){ 
         
         
         Id chOrderRecdTypeId = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('CH_Sales_Order').getRecordTypeId();
        
		Account payorAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'CH Consumer', 'Switzerland')[0];
        payorAccount.Subscription_Pending_Payments__c = 1;
         update payorAccount;
        List<Account> lstAccount = [SELECT Id, Name,Credit_Hold__c FROM Account where Subscription_Pending_Payments__c >0];
       
        List<Product2> lstProduct = [SELECT Id, Name FROM Product2]; 
        List<Address__c> lstAddress = new List<Address__c>{
                                                            new Address__c(Account__c = lstAccount[0].Id,Type__c = 'Bill To', Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = lstAccount[0].Id,Type__c = 'Ship To',Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = payorAccount.Id,Type__c = 'Bill To', Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = payorAccount.Id,Type__c = 'Ship To',Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = ' W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                                                          };
        insert lstAddress;
         
         Id rtIdFDCC = Schema.SObjectType.Finance_Detail__c.getRecordTypeInfosByDeveloperName().get('Credit_Card').getRecordTypeId();
        Finance_Detail__c fd1= new Finance_Detail__c(Account__c=payorAccount.Id,Token__c='1111', Card_Type__c='Mastercard',CC_CUR__c='CHF',
                                                     Expiry_Date__c=null, Primary__c=true, CC_Address__c=null, RecordTypeId=rtIdFDCC);
        insert fd1;
        List<PricebookEntry> lstPBE = [SELECT Id,Name, Pricebook2Id, Product2Id FROM PricebookEntry WHERE Pricebook2.Name = 'CH Cash'];
       Order objOrder = new Order(AccountId = payorAccount.Id, EffectiveDate = Date.today(), Status = 'Draft', Type = 'CH STANDARD', 
                                   Pricebook2Id = lstPBE[0].Pricebook2Id,
                                   Payment_Terms__c = 'net30',
                                   Finance_Detail__c = fd1.Id,
                                   RecordTypeId = chOrderRecdTypeId, CurrencyISOCode = 'CHF');
        insert objOrder;
        List<OrderItem> lstOrderItem = new List<OrderItem>();
        lstOrderItem.add(new OrderItem(PricebookEntryId = lstPBE[0].Id, OrderId = objOrder.Id, Quantity = 1, UnitPrice = 10));
        insert lstOrderItem;
        
        List<SSIP_Rule__c> lstSSIPRule = new List<SSIP_Rule__c>();
        for(PricebookEntry pbe : lstPBE){ // First_Order__c = objOrder.Id,
            System.debug('***pbe--'+pbe.Name);
            Integer fr = 0;
            Integer Ld = 0;
            Integer Quant = 0;
            if(pbe.Name == 'Product-01'){
                fr = 30;
                Ld = 0;
                Quant = 1;
                
            }else if(pbe.Name == 'Product-02'){
                fr = 90;
                Ld = 10;
                Quant = 3;
            }else{
                fr = 90;
                Ld = 10;
                Quant = 1;
            }
            lstSSIPRule.add(new SSIP_Rule__c(Account__c = lstAccount[0].Id, Schedule_Count__c = 1, Frequency_In_Days__c = fr,Payment_term__c ='net30',
                                             First_Repeat_Order_Lead_Days__c = Ld, Price_Book__c = pbe.Pricebook2Id, PriceBookEntryId__c = pbe.Id,
                                             Product__c = pbe.Product2Id,First_Shipment_Date__c = Date.today(),Rule_Re_schedule_Date__c = Date.today()+1,
                                             Quantity__c = Quant, Shipping_Address__c = null, Status__c = 'Active'));
        }
        
        insert lstSSIPRule;      
       
        List<SSIP_Schedule__c> lstSSIPSchedule = [SELECT Id,Account__c FROM SSIP_Schedule__c where Account__c=: payorAccount.Id];
        for(SSIP_Schedule__c ssipSchedule : lstSSIPSchedule){
            ssipSchedule.Rescheduled_Shipment_Date__c = Date.today();
            ssipSchedule.Payment_Term__c = 'net30';
            ssipSchedule.Order__c = objorder.Id;
        }
        
        update lstSSIPSchedule;
        System.debug('====lstSSIPSchedule===='+lstSSIPSchedule);
        
        test.startTest();
         Test.setMock(HttpCalloutMock.class, new ClsMockHttpResponseGenCCAuthorize());
		 System.enqueueJob(new SSIPScheduleJobUtiltiy.AuthorizeAndSettlePaymentQueueable(objOrder.Id,'CH',1,
                                                                          (Integer) objOrder.Account.Subscription_Pending_Payments__c,
                                                                          objOrder.AccountId, true));
         
         test.stopTest();
                   
		
    }
    @isTest private static void testAcccUpdateException(){ 
         
         
         Id chOrderRecdTypeId = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('CH_Sales_Order').getRecordTypeId();
        
		Account payorAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'CH Consumer', 'Switzerland')[0];
        payorAccount.Subscription_Pending_Payments__c = 1;
         update payorAccount;
        List<Account> lstAccount = [SELECT Id, Name,Credit_Hold__c FROM Account where Subscription_Pending_Payments__c >0];
       
        List<Product2> lstProduct = [SELECT Id, Name FROM Product2]; 
        List<Address__c> lstAddress = new List<Address__c>{
                                                            new Address__c(Account__c = lstAccount[0].Id,Type__c = 'Bill To', Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = lstAccount[0].Id,Type__c = 'Ship To',Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = payorAccount.Id,Type__c = 'Bill To', Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = payorAccount.Id,Type__c = 'Ship To',Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = ' W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                                                          };
        insert lstAddress;
         
         Id rtIdFDCC = Schema.SObjectType.Finance_Detail__c.getRecordTypeInfosByDeveloperName().get('Credit_Card').getRecordTypeId();
        Finance_Detail__c fd1= new Finance_Detail__c(Account__c=payorAccount.Id,Token__c='1111', Card_Type__c='Mastercard',CC_CUR__c='CHF',
                                                     Expiry_Date__c=null, Primary__c=true, CC_Address__c=null, RecordTypeId=rtIdFDCC);
        insert fd1;
        List<PricebookEntry> lstPBE = [SELECT Id,Name, Pricebook2Id, Product2Id FROM PricebookEntry WHERE Pricebook2.Name = 'CH Cash'];
       Order objOrder = new Order(AccountId = payorAccount.Id, EffectiveDate = Date.today(), Status = 'Draft', Type = 'CH STANDARD', 
                                   Pricebook2Id = lstPBE[0].Pricebook2Id,
                                   Payment_Terms__c = 'net30',
                                   Finance_Detail__c = fd1.Id,
                                   RecordTypeId = chOrderRecdTypeId, CurrencyISOCode = 'CHF');
        insert objOrder;
        List<OrderItem> lstOrderItem = new List<OrderItem>();
        lstOrderItem.add(new OrderItem(PricebookEntryId = lstPBE[0].Id, OrderId = objOrder.Id, Quantity = 1, UnitPrice = 10));
        insert lstOrderItem;
        
        List<SSIP_Rule__c> lstSSIPRule = new List<SSIP_Rule__c>();
        for(PricebookEntry pbe : lstPBE){ // First_Order__c = objOrder.Id,
            System.debug('***pbe--'+pbe.Name);
            Integer fr = 0;
            Integer Ld = 0;
            Integer Quant = 0;
            if(pbe.Name == 'Product-01'){
                fr = 30;
                Ld = 0;
                Quant = 1;
                
            }else if(pbe.Name == 'Product-02'){
                fr = 90;
                Ld = 10;
                Quant = 3;
            }else{
                fr = 90;
                Ld = 10;
                Quant = 1;
            }
            lstSSIPRule.add(new SSIP_Rule__c(Account__c = lstAccount[0].Id, Schedule_Count__c = 1, Frequency_In_Days__c = fr,Payment_term__c ='net30',
                                             First_Repeat_Order_Lead_Days__c = Ld, Price_Book__c = pbe.Pricebook2Id, PriceBookEntryId__c = pbe.Id,
                                             Product__c = pbe.Product2Id,First_Shipment_Date__c = Date.today(),Rule_Re_schedule_Date__c = Date.today()+1,
                                             Quantity__c = Quant, Shipping_Address__c = null, Status__c = 'Active'));
        }
        
        insert lstSSIPRule;      
       
        List<SSIP_Schedule__c> lstSSIPSchedule = [SELECT Id,Account__c FROM SSIP_Schedule__c where Account__c=: payorAccount.Id];
        for(SSIP_Schedule__c ssipSchedule : lstSSIPSchedule){
            ssipSchedule.Rescheduled_Shipment_Date__c = Date.today();
            ssipSchedule.Payment_Term__c = 'net30';
            ssipSchedule.Order__c = objorder.Id;
        }
        
        update lstSSIPSchedule;
        System.debug('====lstSSIPSchedule===='+lstSSIPSchedule);
        
        test.startTest();
         Test.setMock(HttpCalloutMock.class, new ClsMockHttpResponseGenCCAuthorize());
		 System.enqueueJob(new SSIPScheduleJobUtiltiy.AuthorizeAndSettlePaymentQueueable(objOrder.Id,'CH',1,
                                                                          (Integer) objOrder.Account.Subscription_Pending_Payments__c,
                                                                          null, true));
         
         test.stopTest();
                   
		
    }
    @isTest private static void testOrderUpdateException(){ 
         
         
         Id chOrderRecdTypeId = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('CH_Sales_Order').getRecordTypeId();
        
		Account payorAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'CH Consumer', 'Switzerland')[0];
        payorAccount.Subscription_Pending_Payments__c = 1;
         update payorAccount;
        List<Account> lstAccount = [SELECT Id, Name,Credit_Hold__c FROM Account where Subscription_Pending_Payments__c >0];
       
        List<Product2> lstProduct = [SELECT Id, Name FROM Product2]; 
        List<Address__c> lstAddress = new List<Address__c>{
                                                            new Address__c(Account__c = lstAccount[0].Id,Type__c = 'Bill To', Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = lstAccount[0].Id,Type__c = 'Ship To',Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = payorAccount.Id,Type__c = 'Bill To', Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                                                            new Address__c(Account__c = payorAccount.Id,Type__c = 'Ship To',Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = ' W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                                                          };
        insert lstAddress;
         
         Id rtIdFDCC = Schema.SObjectType.Finance_Detail__c.getRecordTypeInfosByDeveloperName().get('Credit_Card').getRecordTypeId();
        Finance_Detail__c fd1= new Finance_Detail__c(Account__c=payorAccount.Id,Token__c='1111', Card_Type__c='Mastercard',CC_CUR__c='CHF',
                                                     Expiry_Date__c='1112/21', Primary__c=true, CC_Address__c=lstAddress[0].id, RecordTypeId=rtIdFDCC);
        insert fd1;
        List<PricebookEntry> lstPBE = [SELECT Id,Name, Pricebook2Id, Product2Id FROM PricebookEntry WHERE Pricebook2.Name = 'CH Cash'];
       Order objOrder = new Order(AccountId = payorAccount.Id, EffectiveDate = Date.today(), Status = 'Draft', Type = 'CH STANDARD', 
                                   Pricebook2Id = lstPBE[0].Pricebook2Id,
                                   Payment_Terms__c = 'net30',
                                   Finance_Detail__c = fd1.Id,
                                   RecordTypeId = chOrderRecdTypeId, CurrencyISOCode = 'CHF');
        insert objOrder;
        List<OrderItem> lstOrderItem = new List<OrderItem>();
        lstOrderItem.add(new OrderItem(PricebookEntryId = lstPBE[0].Id, OrderId = objOrder.Id, Quantity = 1, UnitPrice = 10));
        insert lstOrderItem;
        
        List<SSIP_Rule__c> lstSSIPRule = new List<SSIP_Rule__c>();
        for(PricebookEntry pbe : lstPBE){ // First_Order__c = objOrder.Id,
            System.debug('***pbe--'+pbe.Name);
            Integer fr = 0;
            Integer Ld = 0;
            Integer Quant = 0;
            if(pbe.Name == 'Product-01'){
                fr = 30;
                Ld = 0;
                Quant = 1;
                
            }else if(pbe.Name == 'Product-02'){
                fr = 90;
                Ld = 10;
                Quant = 3;
            }else{
                fr = 90;
                Ld = 10;
                Quant = 1;
            }
            lstSSIPRule.add(new SSIP_Rule__c(Account__c = lstAccount[0].Id, Schedule_Count__c = 1, Frequency_In_Days__c = fr,Payment_term__c ='net30',
                                             First_Repeat_Order_Lead_Days__c = Ld, Price_Book__c = pbe.Pricebook2Id, PriceBookEntryId__c = pbe.Id,
                                             Product__c = pbe.Product2Id,First_Shipment_Date__c = Date.today(),Rule_Re_schedule_Date__c = Date.today()+1,
                                             Quantity__c = Quant, Shipping_Address__c = null, Status__c = 'Active'));
        }
        
        insert lstSSIPRule;      
       
        List<SSIP_Schedule__c> lstSSIPSchedule = [SELECT Id,Account__c FROM SSIP_Schedule__c where Account__c=: payorAccount.Id];
        for(SSIP_Schedule__c ssipSchedule : lstSSIPSchedule){
            ssipSchedule.Rescheduled_Shipment_Date__c = Date.today();
            ssipSchedule.Payment_Term__c = 'net30';
            ssipSchedule.Order__c = objorder.Id;
        }
        
        update lstSSIPSchedule;
        System.debug('====lstSSIPSchedule===='+lstSSIPSchedule);
        
        test.startTest();
         Test.setMock(HttpCalloutMock.class, new ClsMockHttpResponseGenCCAuthorize());
		 System.enqueueJob(new SSIPScheduleJobUtiltiy.AuthorizeAndSettlePaymentQueueable(objOrder.Id,'CHSD',
                                                                          (Integer) objOrder.Count_of_Order_Line_Items__c,
                                                                          (Integer) objOrder.Account.Subscription_Pending_Payments__c,
                                                                          objOrder.AccountId, true));
         
         test.stopTest();
    }
    
}