src/objects/Address__c.object
<CustomObject>
    <description>Created this custom object to track Address information.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Straße, Hausnummer</inlineHelpText>
        <label>Address Line 1</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_2__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Zusätzliche Informationen</inlineHelpText>
        <label>Address Line 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>City</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bill To</fullName>
                </value>
                <value>
                    <fullName>Ship To</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Finance_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Finance Details</relationshipLabel>
        <relationshipName>Finance_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Bank Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_CUR__c</fullName>
        <label>CC CUR</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CC_Currency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Card_Type__c</fullName>
        <label>Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                    <default>true</default>
                    <label>N/A</label>
                </value>
                <value>
                    <fullName>Visa</fullName>
                </value>
                <value>
                    <fullName>Mastercard</fullName>
                </value>
                <value>
                    <fullName>Amex</fullName>
                    <label>AMEX</label>
                </value>
                <value>
                    <fullName>American Express</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Expiry Date</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>InActive?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_4_Digits__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last 4 Digits</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Card Token</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>Finance Detail</label>
    <nameField>
        <displayFormat>FD-{0000}</displayFormat>
        <label>Finance Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Details</pluralLabel>
    <recordTypes>
        <fullName>Bank</fullName>
        <active>true</active>
        <label>Bank</label>
    </recordTypes>
    <recordTypes>
        <fullName>Credit_Card</fullName>
        <active>true</active>
        <label>Credit Card</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/CC_Currency.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <masterLabel>CC Currency</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Liechtenstein</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <customValue>
        <fullName>Ireland</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Chile</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Spain</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong</fullName>
    </customValue>
    <customValue>
        <fullName>Hungary</fullName>
    </customValue>
    <customValue>
        <fullName>Israel</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Jordan</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <customValue>
        <fullName>Korea</fullName>
    </customValue>
    <customValue>
        <fullName>Kuwait</fullName>
    </customValue>
    <customValue>
        <fullName>Lebanon</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>Norway</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>Oman</fullName>
    </customValue>
    <customValue>
        <fullName>Poland</fullName>
    </customValue>
    <description>Global picklist will be used in various places</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

src/classes/ClsFinanceDetailsCon.cls
public class ClsFinanceDetailsCon {
	@AuraEnabled
    public static List<Finance_Detail__c> getCCData(string accId){
    	
        if(accId.startsWith('001')){
            System.Debug('**** Acc Id=' + accId);
        	return [Select Id, Token__c, Card_Type__c, Expiry_Date__c, Last_4_Digits__c, Primary__c, LastModifiedDate		
         		FROM Finance_Detail__c Where Account__c =:accId AND RecordType.DeveloperName='Credit_Card' Order By Primary__c desc, LastModifiedDate Desc LIMIT 200]; 	   
        } else{
        	Id aId=[Select AccountId from Order Where Id=:accId Limit 1][0].AccountId;
            if(aId!=null){
                System.Debug('**** Order Acc Id=' + aId);
            	return [Select Id, Token__c, Card_Type__c, Expiry_Date__c, Last_4_Digits__c, Primary__c, LastModifiedDate		
         		FROM Finance_Detail__c Where Account__c =:aId AND RecordType.DeveloperName='Credit_Card' Order By Primary__c desc, LastModifiedDate Desc LIMIT 200];    
            }
        }
        return null;
    }
    
    @AuraEnabled
    public static Account getAccName(string accId){
    	System.Debug('**** Acc Id=' + accId);
        if(!accId.startsWith('001')){
        	accId=[Select AccountId from Order Where Id=:accId Limit 1][0].AccountId;    
        }
        Account acc=[Select Id, Name, CurrencyISOCode from Account where ID=:accId Limit 1][0];
        return acc;
    }
    
    @AuraEnabled 
    public static Map<String, String> getAccBTAddr(Id accId){
        
        Map<String, String> mapAddrOptions = new Map<String, String>();
        if(!string.valueOf(accId).startsWith('001')){
        	accId=[Select AccountId from Order Where Id=:accId Limit 1][0].AccountId;    
        }
        for(Address__c addr : [Select Id, Account__r.Name, Address_Line_1__c, Address_Line_2__c, City__c, State__c, Postal_Code__c, Country__c,Type__c, Primary_Flag__c
                               from Address__c Where Account__c=:accId  AND Type__c='Bill To' AND Inactive__c=False ]){
    		string strAddr=(String.isBlank(addr.Address_Line_1__c)? '' : addr.Address_Line_1__c + ', ') + 
                (String.isBlank(addr.City__c)? '' : addr.City__c + ', ')  +
                (String.isBlank(addr.State__c)? '' : addr.State__c + ', ') + 
                (String.isBlank(addr.Postal_Code__c)? '' : addr.Postal_Code__c + ', ') + 
                (String.isBlank(addr.Country__c)? '' : addr.Country__c );
                
    		if(addr.Primary_Flag__c)
    			strAddr+= ' (Primary)';
            
            mapAddrOptions.put(addr.Id, strAddr);
        }
 		return mapAddrOptions;
    }
    
    @AuraEnabled 
    public static string getCCNumberToken(Finance_Detail__c recFD, string ccNum){
        if(recFD != null){
            boolean isPrimary=false;
        	clsCSAPIHelper cls= new clsCSAPIHelper();
            string currCode=(recFD.CC_CUR__c==null)? 'GBP' : recFD.CC_CUR__c; 
        	string ccToken=cls.getCCToken(ccNum, currCode);
			System.Debug('**** Token=' + ccToken);
            if(ccToken != null){
            	recFD.RecordTypeId= Schema.SObjectType.Finance_Detail__c.getRecordTypeInfosByDeveloperName().get('Credit_Card').getRecordTypeId();
            	recFD.Token__c=ccToken;                
                recFD.Last_4_Digits__c=ccToken.Right(4);
                isPrimary=recFD.Primary__c;
                insert recFD;
            }
            
            /* If a primary card is being saved then mark other cards for this account as non primary */
            if(recFD.Primary__c){
                clsJobMarkCardsNonPrimary jobUpdateCC = new clsJobMarkCardsNonPrimary(new List<Finance_Detail__c>{recFD});
				// Enqueue the job for later processing
				//ID jobID = System.enqueueJob(jobUpdateCC);	    
            }
        	return ccToken;    
        }
    	return null; 
    }
    
   /* @AuraEnabled 
    public static Finance_Detail__c AddIbanNum(string ibanNum, string accId){
        map<string, string> mapReturn = new map<string, string>();
        System.Debug('**** TPS:EH 1.0 Starting AddIbanNum ibanNum=' + ibanNum + ' accId='+accId);
        if(ibanNum !=null && accId != null){
            System.Debug('**** TPS:EH 1.1 ibanNum=' + ibanNum + ' accId=' + accId);
        	Id recTypeId = Schema.SObjectType.Finance_Detail__c.getRecordTypeInfosByDeveloperName().get('Bank').getRecordTypeId();
            Finance_Detail__c fd=new Finance_Detail__c(Account__c=accId, IBan__c=ibanNum, Account_Num__c='Acc-'+ibanNum, BIC__c='BIC-' + ibanNum, Bank_Name__c='Bank-' + ibanNum);
            fd.RecordTypeId=recTypeId;
            System.Debug('**** TPS:EH 1.2 fd=' + fd);
            insert fd;
        }
        return null;
    } */
    
    /* @AuraEnabled
    public static List<Finance_Detail__c> getIBanData(string accId){    	
        if(accId.startsWith('001')){
            System.Debug('**** Acc Id=' + accId);
        	return [Select Id, Name,Primary__c, IBan__c, Account_Num__c, BIC__c, Bank_Name__c
         		FROM Finance_Detail__c Where Account__c =:accId AND RecordType.DeveloperName='Bank' Order By Primary__c desc, LastModifiedDate Desc LIMIT 100]; 	   
        } 
        return null;
    } */
    
    @AuraEnabled
    public static Account getVATData(string accId){    	
        if(accId.startsWith('001')){
            System.Debug('**** Acc Id=' + accId);
        	return [Select Id, Tax_Registration_Number__c, VAT_Valid__c from Account where Id=:accId Limit 1][0];
        } 
        return null;
    }
    
   @AuraEnabled 
    public static boolean ValidateVATNum(string vatNum, string accId){
        map<string, string> mapReturn = new map<string, string>();
        System.Debug('**** TPS:EH 1.0 Starting AddVATNum vatNum=' + vatNum + ' accId='+accId);
        if(vatNum !=null && accId != null){
            VATAPIRes clsRes=ClsApiHelper.VatNumCheck(vatNum);
            if(clsRes.status ==200 && clsRes.message=='success'){
                if(clsRes.validation.status=='ok' && clsRes.validation.valid){
                    Account a = new Account(Id=accId, Tax_Registration_Number__c=vatNum.toUppercase(), VAT_Valid__c=true);
                    update a;
                    
                    // Insert task to log results of vat validation call
                    Id recTypeId = Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('Service_Log').getRecordTypeId();
                    Task tLog= new Task(WhatId=accId, Subject='VAT # [' + vatNum + '] Validation', Description=JSON.serializePretty(clsRes), 
                    	Status='Completed', ActivityDate=Date.Today(), Priority='Normal', Type='Other');
                    insert tLog;
                    return true;
                }
            }
        }
        return false;
    }
}