src/objects/Address__c.object
<CustomObject>
    <description>Created this custom object to track Address information.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Straße, Hausnummer</inlineHelpText>
        <label>Address Line 1</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>City</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bill To</fullName>
                </value>
                <value>
                    <fullName>Ship To</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Liechtenstein</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <customValue>
        <fullName>Ireland</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Chile</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Spain</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong</fullName>
    </customValue>
    <customValue>
        <fullName>Hungary</fullName>
    </customValue>
    <customValue>
        <fullName>Israel</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Jordan</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <customValue>
        <fullName>Korea</fullName>
    </customValue>
    <customValue>
        <fullName>Kuwait</fullName>
    </customValue>
    <customValue>
        <fullName>Lebanon</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>Norway</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>Oman</fullName>
    </customValue>
    <customValue>
        <fullName>Poland</fullName>
    </customValue>
    <description>Global picklist will be used in various places</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

src/classes/ClsTestAddressObject.cls
/********************************************************************************
@Author        : Jagan Periyakaruppan
@Date Created    : 08/12/2017
@Description    : Test class to test the scenarios involved in Address object
*********************************************************************************/
@isTest
private class ClsTestAddressObject {
    @isTest static void TestAccountAddress(){
        //Insert 1 account record
        List<Account> accts = ClsTestDataFactory.createAccountsWithBillingAddress(2, 'DE Consumer', 'Germany');
        Test.startTest();
		ClsAccountAddressTriggerStaticClass.addressChangeInvokedFromAddress = TRUE;
		ClsAccountAddressTriggerStaticClass.addressChangeInvokedFromAccount = FALSE;
		//Get the first account, which was inserted
		Account a = accts[0];
		String street = a.BillingStreet;
        a.Copy_Billing_To_Shipping__c = true ;
     //   a.Copy_Shipping_To_Billing__c = true ;        
		update a ;
        
       //Query for the Address record types
        List<RecordType> rtypes = [Select Name, Id From RecordType 
                               where sObjectType='Address__c' and isActive=true];
    
        //Create a map between the Record Type Name and Id 
        Map<String,String> addRecordTypes = new Map<String,String>();
        for(RecordType rt: rtypes) {
        addRecordTypes.put(rt.Name,rt.Id);
        }     	
        String recordTypeId = addRecordTypes.get('DE Address');
        
		//Insert new Bill To and Ship To address records
		List<Address__c> addrListToBeInserted = new List<Address__c>();
		Address__c newBillToAddr = new Address__c();
		newBillToAddr.Account__c = a.Id;
        newBillToAddr.RecordTypeId = recordTypeId;
		newBillToAddr.Address_Line_1__c = '3 Main Street';
		newBillToAddr.City__c = 'San Diego';
		newBillToAddr.Postal_Code__c = '92121';
		newBillToAddr.Country__c = 'Germany';
		newBillToAddr.Type__c = 'Bill To';
		newBillToAddr.Primary_Flag__c = TRUE;
		addrListToBeInserted.add(newBillToAddr);

        Address__c newShipToAddr = new Address__c();
		newShipToAddr.Account__c = a.Id;
        newShipToAddr.RecordTypeId = recordTypeId;
		newShipToAddr.Address_Line_1__c = '3 Main Street';
		newShipToAddr.City__c = 'San Diego';
		newShipToAddr.Postal_Code__c = '92123';
		newShipToAddr.Country__c = 'Germany';
		newShipToAddr.Type__c = 'Ship To';
		newShipToAddr.Primary_Flag__c = TRUE;
		addrListToBeInserted.add(newShipToAddr);
		insert addrListToBeInserted;
				
		//Process to make existing address as Primary
		List<Address__c> addrListToBeUpdated = new List<Address__c>();
		//Query for original billing primary address and make it as primary
		Address__c billToAddrToBeMadePrimary = [SELECT Id FROM Address__c WHERE Address_Line_1__c = :street AND Account__c = :a.Id AND Type__c = 'Bill To'];
		billToAddrToBeMadePrimary.Primary_Flag__c = TRUE;
		addrListToBeUpdated.add(billToAddrToBeMadePrimary);
		//Query for original shipping primary address and make it as primary
		Address__c shipToAddrToBeMadePrimary = [SELECT Id FROM Address__c WHERE Address_Line_1__c = :street AND Account__c = :a.Id AND Type__c = 'Ship To'];
		shipToAddrToBeMadePrimary.Primary_Flag__c = TRUE;
		addrListToBeUpdated.add(shipToAddrToBeMadePrimary);
		update addrListToBeUpdated;
		addrListToBeUpdated.clear();
		
		//Alter existing primary address attributes
		//Query for original billing primary address and make it as primary
		Address__c billToPrimaryAddr = [SELECT Id FROM Address__c WHERE Account__c = :a.Id AND Type__c = 'Bill To' AND Primary_Flag__c = TRUE];
		billToPrimaryAddr.Address_Line_1__c = 'Street Address Changed';
		addrListToBeUpdated.add(billToPrimaryAddr);
		Address__c shipToPrimaryAddr = [SELECT Id FROM Address__c WHERE Account__c = :a.Id AND Type__c = 'Ship To' AND Primary_Flag__c = TRUE];
		shipToPrimaryAddr.Address_Line_1__c = 'Street Address Changed';
		addrListToBeUpdated.add(shipToPrimaryAddr);
		Update addrListToBeUpdated;
        
        Account acc = [SELECT Id FROM Account limit 1];
        delete acc;
		
		Test.stopTest();
	}
}