src/objects/Address__c.object
<CustomObject>
    <description>Created this custom object to track Address information.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Straße, Hausnummer</inlineHelpText>
        <label>Address Line 1</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>City</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bill To</fullName>
                </value>
                <value>
                    <fullName>Ship To</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country_Admin__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This setting will hold the User Id of the person , who is the country admin .</description>
    <fields>
        <fullName>User_Id__c</fullName>
        <description>Salesforce user id of the Country admin.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>User Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Country Admin</label>
</CustomObject>

src/objects/Zip_to_Terr__c.object
<CustomObject>
    <description>Jagan 04/2/2017 - Created this object to hold zip to terr alignment information for all countries.</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>District</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Region</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Territory</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Zip to Terr</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip to Terrs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Liechtenstein</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <customValue>
        <fullName>Ireland</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Chile</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Spain</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong</fullName>
    </customValue>
    <customValue>
        <fullName>Hungary</fullName>
    </customValue>
    <customValue>
        <fullName>Israel</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Jordan</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <customValue>
        <fullName>Korea</fullName>
    </customValue>
    <customValue>
        <fullName>Kuwait</fullName>
    </customValue>
    <customValue>
        <fullName>Lebanon</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>Norway</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>Oman</fullName>
    </customValue>
    <customValue>
        <fullName>Poland</fullName>
    </customValue>
    <description>Global picklist will be used in various places</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

src/classes/ClsTestAccountObject.cls
/********************************************************************************
@Author        : Jagan Periyakaruppan
@Date Created    : 08/12/2017
@Description    : Test class to test the scenarios involved in Account object
*********************************************************************************/
@isTest
private class ClsTestAccountObject {
    @isTest static void TestAccountAddress(){
        //Insert 10 account records
        List<Account> accts = ClsTestDataFactory.createAccountsWithBillingAddress(10, 'DE Consumer', 'Germany');
        Test.startTest();
        ClsAccountAddressTriggerStaticClass.addressChangeInvokedFromAddress = FALSE;
        ClsAccountAddressTriggerStaticClass.addressChangeInvokedFromAccount = TRUE;
        //Get the first account, which was inserted
        Account a = accts[0];
        String street = a.BillingStreet;
        String city = a.BillingCity;
        String state = a.BillingState;
        String postalCode = a.BillingPostalCode;
        String country = a.BillingCountry;
        List<Address__c> addrList = [SELECT Id FROM Address__c WHERE Account__c = :a.Id];
        system.assertEquals(2, addrList.size());
        addrList.clear();
        //Change the Billing and Shipping address and save the account
        a.BillingStreet = '1 Main Street';
        a.BillingCity = 'San Diego';
        a.BillingPostalCode = '92121';
        a.BillingCountryCode = 'DE';
        a.ShippingStreet = '2 Main Street';
        a.ShippingCity = 'San Diego';
        a.ShippingPostalCode = '92121';
        a.ShippingCountryCode = 'DE';
        Update a;
        addrList = [SELECT Id FROM Address__c WHERE Account__c = :a.Id];
        system.assertEquals(4, addrList.size());
        addrList.clear();
        //Query for the Address record types
        List<RecordType> rtypes = [Select Name, Id From RecordType 
                               where sObjectType='Address__c' and isActive=true];
    
        //Create a map between the Record Type Name and Id 
        Map<String,String> addRecordTypes = new Map<String,String>();
        for(RecordType rt: rtypes) {
        addRecordTypes.put(rt.Name,rt.Id);
        }     	
        String recordTypeId = addRecordTypes.get('DE Address');
        
        //Insert new address record
        List<Address__c> addrListToBeInserted = new List<Address__c>();
        Address__c newBillToAddr = new Address__c();
        newBillToAddr.Account__c = a.Id;
        newBillToAddr.RecordTypeId = recordTypeId;
        newBillToAddr.Address_Line_1__c = '3 Main Street';
        newBillToAddr.City__c = 'San Diego';
        newBillToAddr.Postal_Code__c = '92121';
        newBillToAddr.Country__c = 'Germany';
        newBillToAddr.Type__c = 'Bill To';
        newBillToAddr.Primary_Flag__c = TRUE;
        addrListToBeInserted.add(newBillToAddr);
        Address__c newShipToAddr = new Address__c();
        newShipToAddr.Account__c = a.Id;
        newShipToAddr.RecordTypeId = recordTypeId;
        newShipToAddr.Address_Line_1__c = '4 Main Street';
        newShipToAddr.City__c = 'San Diego';
        newShipToAddr.Postal_Code__c = '92121';
        newShipToAddr.Country__c = 'Germany';
        newShipToAddr.Type__c = 'Ship To';
        newShipToAddr.Primary_Flag__c = TRUE;
        addrListToBeInserted.add(newShipToAddr);
        insert addrListToBeInserted;
        //Process to make existing address as Primary
        List<Address__c> addrListToBeUpdated = new List<Address__c>();
        //Query for original billing primary address and make it as primary
        Address__c billToAddrToBeMadePrimary = [SELECT Id FROM Address__c WHERE Address_Line_1__c = :street AND Account__c = :a.Id AND Type__c = 'Bill To'];
        billToAddrToBeMadePrimary.Primary_Flag__c = TRUE;
        addrListToBeUpdated.add(billToAddrToBeMadePrimary);
        //Query for original shipping primary address and make it as primary
        Address__c shipToAddrToBeMadePrimary = [SELECT Id FROM Address__c WHERE Address_Line_1__c = :street AND Account__c = :a.Id AND Type__c = 'Ship To'];
        shipToAddrToBeMadePrimary.Primary_Flag__c = TRUE;
        addrListToBeUpdated.add(shipToAddrToBeMadePrimary);
        update addrListToBeUpdated;
        //Make existing address as primary
        //Change the Billing and Shipping address and save the account
        a.BillingStreet = '3 Main Street';
        a.BillingCity = 'San Diego';
        a.BillingPostalCode = '92121';
        a.BillingCountryCode = 'DE';
        a.ShippingStreet = '4 Main Street';
        a.ShippingCity = 'San Diego';
        a.ShippingPostalCode = '92121';
        a.ShippingCountryCode = 'DE';
        Update a;
        Test.stopTest();
        //Confirm the counts
        addrList = [SELECT Id FROM Address__c WHERE Account__c = :a.Id];
        system.assertEquals(10, accts.size());
        system.assertEquals(6, addrList.size());
    }
    @isTest static void TestPrescriberToMedFacRelation(){
        //Insert 5 Prescriber record
        List<Account> prescriberAccts = ClsTestDataFactory.createAccountsWithBillingAddress(5, 'DE Prescriber', 'Germany');
        //Insert 2 Prescribers tied to a Med Fac
        List<Account> prescribersWithMedFac = ClsTestDataFactory.createAccountsWithPrescriberToMedFacAssociation(2, 'Germany');
        Account prescriberAccnt = prescriberAccts[0];
        //Insert 5 Medical Facility record
        List<Account> medFacAccts = ClsTestDataFactory.createAccountsWithBillingAddress(5, 'DE Medical Facility', 'Germany');
        Test.startTest();
        //Associate a Medical Facility to a Prescriber
        prescriberAccnt.Medical_Facility__c = medFacAccts[0].Id;
        update prescriberAccnt;
        //Change the association to another Medical Facility
        prescriberAccnt.Medical_Facility__c = medFacAccts[1].Id;
        update prescriberAccnt;
        //Change the association to first Medical Facility
        prescriberAccnt.Medical_Facility__c = medFacAccts[0].Id;
        update prescriberAccnt;
        Test.stopTest();
    }	
    @isTest static void TestAccountTerritoryAssignment(){
        //Insert zip to terr
        List<Zip_to_Terr__c> zipToTerrList = new List<Zip_to_Terr__c>();
        Zip_to_Terr__c zipToTerr = new Zip_to_Terr__c();
        zipToTerr.Name = '61169';
        ZipToTerr.Territory__c = 'DE020101';
        ZipToTerr.Region__c = 'DE020000';
        ZipToTerr.District__c = 'DE020100';
        ZipToTerr.Country__c = 'Germany';
        zipToTerrList.add(ZipToTerr);
        Zip_to_Terr__c zipToTerr1 = new Zip_to_Terr__c();
        zipToTerr1.Name = '61168';
        zipToTerr1.Territory__c = 'DE020102';
        zipToTerr1.Region__c = 'DE020000';
        zipToTerr1.District__c = 'DE020100';
        zipToTerr1.Country__c = 'Germany';
        zipToTerrList.add(zipToTerr1);
        insert zipToTerrList;
        //Insert 10 account records
        List<Account> accts = ClsTestDataFactory.createAccountsWithBillingAddress(10, 'DE Consumer', 'Germany');
        //Insert 5 Medical Facility record
        List<Account> medFacAccts = ClsTestDataFactory.createAccountsWithBillingAddress(5, 'DE Medical Facility', 'Germany');
        //Insert 5 Prescriber record
        List<Account> prescriberAccts = ClsTestDataFactory.createAccountsWithBillingAddress(5, 'DE Prescriber', 'Germany');
        List<Account> accntsToBeUpdated = new List<Account>();
        Test.startTest();
        Account accntWithMedFac = accts[0];
        accntWithMedFac.Medical_Facility__c = medFacAccts[0].Id;
        accntsToBeUpdated.add(accntWithMedFac);
        Account accntWithMedPrescriber = accts[1];
        accntWithMedPrescriber.Prescriber__c = prescriberAccts[0].Id;
        accntsToBeUpdated.add(accntWithMedPrescriber);
        Account accntWithChangedZip = accts[2];
        accntWithChangedZip.ShippingPostalCode = '61168';
        accntsToBeUpdated.add(accntWithChangedZip);
        //Insert User
        Profile pf = [SELECT Id FROM Profile WHERE Name = 'DE Salesforce Admin'];
        UserRole ur = [SELECT Id FROM UserRole WHERE Name = 'DE Inside Sales'];
        User usr = ClsTestDataFactory.createTestUser(ur.Id, pf.Id, 'Test FirstName', 'Test LastName');
        try
        {
            insert usr;
        }
        Catch(DMLException e){}
        //Insert custom setting
        Country_Admin__c countryAdminSetting = new Country_Admin__c();
        countryAdminSetting.Name='DE';
        countryAdminSetting.User_Id__c = usr.Id;
        insert countryAdminSetting;
        Update accntsToBeUpdated;
        Test.stopTest();
    }
    @isTest Static void testAccountMerge() {
        // Insert new accounts
        List<Account> ls = new List<Account>{
            new Account(name='Acme Inc.'),
                new Account(name='Acme')
                };                                        
        insert ls;
        
        // Queries to get the inserted accounts 
        Account masterAcct = [SELECT Id, Name FROM Account WHERE Name = 'Acme Inc.' LIMIT 1];
        Account mergeAcct = [SELECT Id, Name FROM Account WHERE Name = 'Acme' LIMIT 1];
        
        // Add a contact to the account to be merged
        Contact c = new Contact(FirstName='Joe',LastName='Merged');
        c.AccountId = mergeAcct.Id;
        insert c;
        test.startTest();
        try {
            merge masterAcct mergeAcct;
        } catch (DmlException e) {
            // Process exception
            System.debug('An unexpected error has occurred: ' + e.getMessage()); 
        }
        test.stopTest();
        // Once the account is merged with the master account,
        // the related contact should be moved to the master record.
        masterAcct = [SELECT Id, Name, (SELECT FirstName,LastName From Contacts) 
                      FROM Account WHERE Name = 'Acme Inc.' LIMIT 1];
        System.assert(masterAcct.getSObjects('Contacts').size() > 0);
        System.assertEquals('Joe', masterAcct.getSObjects('Contacts')[0].get('FirstName'));
        System.assertEquals('Merged', masterAcct.getSObjects('Contacts')[0].get('LastName'));
        
        // Verify that the merge record got deleted
        Account[] result = [SELECT Id, Name FROM Account WHERE Id=:mergeAcct.Id];
        System.assertEquals(0, result.size());
    }
}