src/objects/Address__c.object
<CustomObject>
    <description>Created this custom object to track Address information.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Straße, Hausnummer</inlineHelpText>
        <label>Address Line 1</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>City</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsLocked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Address needs to be locked when an Order is activated so that it is not updated.</description>
        <label>Locked?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bill To</fullName>
                </value>
                <value>
                    <fullName>Ship To</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Record_Updater__c.object
<CustomObject>
    <description>To be used for updating any Object&apos;s individual field. Logic can be implemented in batch jobs to pull multiple fields for a given record and updated at once.</description>
    <fields>
        <fullName>Acted_On__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If the Record&apos;s action was completed. This is to be used to find out which actions already took place.</description>
        <label>Acted On</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Update</fullName>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
                <value>
                    <fullName>Upsert</fullName>
                </value>
                <value>
                    <fullName>Undelete</fullName>
                </value>
                <value>
                    <fullName>Insert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Field_Type__c</fullName>
        <description>Field Type of the field that needs to be acted on.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Field Type</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fieldname__c</fullName>
        <description>API of the Field Name</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>API of the Field Name</inlineHelpText>
        <label>Fieldname</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>Value of the field that should be used in the action.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Value</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Record Updater</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Record Updater</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Liechtenstein</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <customValue>
        <fullName>Ireland</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Chile</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Spain</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong</fullName>
    </customValue>
    <customValue>
        <fullName>Hungary</fullName>
    </customValue>
    <customValue>
        <fullName>Israel</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Jordan</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <customValue>
        <fullName>Korea</fullName>
    </customValue>
    <customValue>
        <fullName>Kuwait</fullName>
    </customValue>
    <customValue>
        <fullName>Lebanon</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>Norway</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>Oman</fullName>
    </customValue>
    <customValue>
        <fullName>Poland</fullName>
    </customValue>
    <description>Global picklist will be used in various places</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

src/classes/BClsRecordUpdaterPurger_Test.cls
/*
 * Description - BClsRecordUpdaterPurger_Test Class will cover Code Coverage 
 * for below Classes --
 * 
 * 1 - BClsRecordUpdaterPurger
 * 2 - BClsAddressLocker
 * 
*/

@isTest
public class BClsRecordUpdaterPurger_Test {

    @isTest static void TestRecordUpdater(){
        //Insert 1 account record
        List<Account> accts = ClsTestDataFactory.createAccountsWithBillingAddress(2, 'DE Consumer', 'Germany');
        
		Account a = accts[0];
		String street = a.BillingStreet;
        a.Copy_Billing_To_Shipping__c = true ;       
		update a ;
        Id recordTypeId = Schema.SObjectType.Address__c.getRecordTypeInfosByName().get('DE Address').getRecordTypeId();
 		//Insert new Bill To and Ship To address records
		List<Address__c> addrListToBeInserted = new List<Address__c>();
		Address__c newBillToAddr = new Address__c();
		newBillToAddr.Account__c = a.Id;
        newBillToAddr.RecordTypeId = recordTypeId;
		newBillToAddr.Address_Line_1__c = '3 Main Street';
		newBillToAddr.City__c = 'San Diego';
		newBillToAddr.Postal_Code__c = '92121';
		newBillToAddr.Country__c = 'Germany';
		newBillToAddr.Type__c = 'Bill To';
		newBillToAddr.Primary_Flag__c = TRUE;
		addrListToBeInserted.add(newBillToAddr);

        Address__c newShipToAddr = new Address__c();
		newShipToAddr.Account__c = a.Id;
        newShipToAddr.RecordTypeId = recordTypeId;
		newShipToAddr.Address_Line_1__c = '3 Main Street';
		newShipToAddr.City__c = 'San Diego';
		newShipToAddr.Postal_Code__c = '92123';
		newShipToAddr.Country__c = 'Germany';
		newShipToAddr.Type__c = 'Ship To';
		newShipToAddr.Primary_Flag__c = TRUE;
		addrListToBeInserted.add(newShipToAddr);
		insert addrListToBeInserted;
				
		Record_Updater__c recUpdater = new Record_Updater__c();
		recUpdater.Acted_On__c = true;
        recUpdater.Action__c = 'Insert';
        recUpdater.Id__c = addrListToBeInserted[0].Id;
        insert recUpdater;
        
       Test.startTest();
        Database.executeBatch(new BClsRecordUpdaterPurger(), 1);
		Test.stopTest();
        
        // For Address Locker Batch Class
        Record_Updater__c recUpdater1 = new Record_Updater__c();
        recUpdater1.Name = 'Address__c';
		recUpdater1.Acted_On__c = false;
        recUpdater1.Action__c = 'Insert';
        recUpdater1.Id__c = addrListToBeInserted[0].Id;
        insert recUpdater1;
        
        recUpdater1.Action__c = 'Update';
        recUpdater1.Field_Type__c = 'Checkbox';
        recUpdater1.Value__c = 'true';
        recUpdater1.FieldName__c = 'IsLocked__c';
        update recUpdater1;
        Database.executeBatch(new BClsAddressLocker(), 1);

        

	}
}