src/objects/Address__c.object
<CustomObject>
    <description>Created this custom object to track Address information.</description>
    <fields>
        <fullName>IsLocked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Address needs to be locked when an Order is activated so that it is not updated.</description>
        <label>Locked?</label>
        <type>Checkbox</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Record_Updater__c.object
<CustomObject>
    <description>To be used for updating any Object&apos;s individual field. Logic can be implemented in batch jobs to pull multiple fields for a given record and updated at once.</description>
    <fields>
        <fullName>Acted_On__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If the Record&apos;s action was completed. This is to be used to find out which actions already took place.</description>
        <label>Acted On</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Update</fullName>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
                <value>
                    <fullName>Upsert</fullName>
                </value>
                <value>
                    <fullName>Undelete</fullName>
                </value>
                <value>
                    <fullName>Insert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Field_Type__c</fullName>
        <description>Field Type of the field that needs to be acted on.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Field Type</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fieldname__c</fullName>
        <description>API of the Field Name</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>API of the Field Name</inlineHelpText>
        <label>Fieldname</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>Value of the field that should be used in the action.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Value</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Record Updater</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Record Updater</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BClsAddressLocker.cls
global class BClsAddressLocker implements Database.Batchable<Sobject> {
	global Database.QueryLocator start(Database.BatchableContext BC){
        //((STATUS__c = 'OPEN') OR (STATUS__c = 'IN ERROR' AND TRY_TO_CREATE_OREDER__c = TRUE))
        String query = 'Select Id, Id__c from Record_Updater__c where Name = \'Address__c\' AND Action__c=\'Update\' and FieldName__c = \'IsLocked__c\' AND Field_Type__c = \'Checkbox\' AND Value__c = \'true\' AND Acted_On__c = false';
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<Record_Updater__c> scope){
        List<Record_Updater__c> updRecList = new List<Record_Updater__c>();
        List<Address__c> updAddressList = new List<Address__c>();
        Map<String, Id> updRecMap = new Map<String, Id>();
        Map<Id, Address__c> updAddressMap = new Map<Id, Address__c>();
        Set<Id> addIds = new Set<Id>();
		for(Record_Updater__c rec : scope) addIds.add(rec.Id__c);        
        Map<Id, Address__c> lockedAddressMap = new Map<Id, Address__c>([Select Id from Address__c where id in :addIds AND IsLocked__c = true]);
        for(Record_Updater__c rec : scope) {
            if (!lockedAddressMap.containsKey(rec.Id__c)) { updAddressMap.put(rec.Id__c, new Address__c(id=rec.Id__c, IsLocked__c = true)); updRecMap.put(rec.Id__c, rec.Id); }
        }
        Boolean allSucceeded = true;
        if (updAddressMap.size() > 0) {
            updAddressList = updAddressMap.values();
            Database.SaveResult[] dsr = Database.update(updAddressList, false);
            for(Integer i = 0; i < dsr.size(); i++){
                if(dsr[i].isSuccess()){
                        updRecList.add(new Record_Updater__c(id = updRecMap.get(updAddressList[i].id), Acted_On__c = true));
                }else {
                    allSucceeded = false;
                    String error = '';
                    for(Database.Error err : dsr[i].getErrors()) {
                        error += error == '' ? 'Order ' + err.getMessage() : ', ' + err.getMessage();
                    }
                    //LogError(String action, String classNMethodName, String errorMsg, String eventType, String eventSource, String exceptionError, String externalID, String severity)
                    ErrorUtility.LogError('Consume', 'BClsAddressLocker.updateAddress__c', error, 'Address', 'crm', '', updAddressList[i].id, 'Informational');
                    System.debug('====error in order====='+error);
                }
            }
        }
        if (allSucceeded == true) {
            updRecList.clear();
            for(Record_Updater__c r : scope) updRecList.add(new Record_Updater__c(id = r.Id, Acted_On__c = true));
        }
        if (updRecList.size() > 0) {
            Database.SaveResult[] dsr = Database.update(updRecList, false);
            for(Integer i = 0; i < dsr.size(); i++){
                if(!dsr[i].isSuccess()){
                    String error = '';
                    for(Database.Error err : dsr[i].getErrors()) {
                        error += error == '' ? 'Order ' + err.getMessage() : ', ' + err.getMessage();
                    }
                    //LogError(String action, String classNMethodName, String errorMsg, String eventType, String eventSource, String exceptionError, String externalID, String severity)
                    ErrorUtility.LogError('Consume', 'BClsAddressLocker.updateRecord_Updater__c', error, 'Address', 'crm', '', updRecList[i].id, 'Informational');
                    System.debug('====error in order====='+error);
                }
            }
        }
    }
    global void finish(Database.BatchableContext BC){
        
    }
}