src/objects/Benefit__c.object
<CustomObject>
    <description>Jagan 03/29/2017 - Created this custom object to track Benefits information.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Benefits</relationshipLabel>
        <relationshipName>Benefits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Benefit_Hierarchy__c</fullName>
        <label>Benefit Hierarchy</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Secondary</fullName>
                </value>
                <value>
                    <fullName>Tertiary</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Represents whether the Benefit is still active for the Account Holder.</description>
        <inlineHelpText>Inactivate the Benefit if the Payor or number is changed.</inlineHelpText>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Insurance_Holder_s_Relationship__c</fullName>
        <label>Insurance Holder&apos;s Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Self</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Spouse</fullName>
                </value>
                <value>
                    <fullName>Domestic Partner</fullName>
                </value>
                <value>
                    <fullName>Guardian</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Account with Payer record type</description>
        <label>Payor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>contains</operation>
                <value>Payor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payors</relationshipLabel>
        <relationshipName>Payors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Policy_Number__c</fullName>
        <description>Insurance Payer or Issuer ID</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Insurance Payer or Issuer ID</inlineHelpText>
        <label>Policy Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Benefit</label>
    <nameField>
        <displayFormat>B-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CtrlCanadianPayorMatrixTest.cls
@isTest
public class CtrlCanadianPayorMatrixTest {

    @isTest
    public static void testgetAccountId() {
        Map<String, Id> recTypesMap = ClsTestDataFactory.getRecordTypeMap();
        Account payorAcc = new Account(Name='Payor Account', RecordTypeId = recTypesMap.get('CA Payor') , BillingStreet = '1121 Main St.', BillingCity='Toronto',  BillingState= 'Ontario', BillingPostalCode='M4G 3L2',BillingStateCode = 'ON', BillingCountryCode='CA' );
        insert payorAcc;
        Account conAcc = new Account(firstname='Test', lastName='Consumer', personEmail='test@tester.com',RecordTypeId = recTypesMap.get('CA Consumer') );
		insert conAcc;
        Benefit__c ben = new Benefit__c(Account__c = conAcc.Id, Benefit_Hierarchy__c = 'Primary', Payor__c=payorAcc.Id,  Insurance_Holder_s_Relationship__c='Self',Policy_Number__c = '23228232', InActive__c = false);
        insert ben;
        ID oppRecType = [Select Id from RecordType where isActive = true AND Sobjecttype = 'Opportunity' and DeveloperName = 'CA_Opportunity'].id;
        Opportunity opp = new Opportunity(Name='Test Opp', CloseDate=System.today(), StageName='New Opportunity', AccountId = conAcc.Id, Benefit__c = ben.Id, RecordTypeId = oppRecType);
        insert opp;
        String benPayorId = CtrlCanadianPayorMatrix.getAccountId(opp.id);
        system.assertEquals(payorAcc.Id, benPayorId);
        Account a = CtrlCanadianPayorMatrix.getReqDocs(benPayorId);
        system.assertEquals(payorAcc.Id, a.Id);
    }
}