src/objects/Benefit__c.object
<CustomObject>
    <description>Jagan 03/29/2017 - Created this custom object to track Benefits information.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Benefits</relationshipLabel>
        <relationshipName>Benefits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Account with Payer record type</description>
        <label>Payor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>contains</operation>
                <value>Payor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payors</relationshipLabel>
        <relationshipName>Payors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Benefit</label>
    <nameField>
        <displayFormat>B-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Content_Metadata__c.object
<CustomObject>
    <description>Object stores the metadata information about the file, which was uploaded</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Captures the Account to which the file was linked</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Content Metadata</relationshipLabel>
        <relationshipName>Content_Metadata</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Content_Document_Id__c</fullName>
        <description>Stores the ContentDocumentId of the file, which was uploaded</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Content Document Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Content_Size__c</fullName>
        <description>Records the content size of the document</description>
        <label>Size</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Document_Created_By_User__c</fullName>
        <formula>CreatedBy.FirstName + &apos; &apos; + CreatedBy.LastName</formula>
        <label>Document Created By User</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Created_Date__c</fullName>
        <description>Created date of the document</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Document Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <description>This field tracks the document type to classify the documents.</description>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Empf</fullName>
                </value>
                <value>
                    <fullName>VO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>File_Type__c</fullName>
        <description>Stores the file type, which was uploaded</description>
        <encryptionScheme>None</encryptionScheme>
        <label>File Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Linked_Objects__c</fullName>
        <description>Field displays the Objects a particular document is linked</description>
        <formula>IF(AND (Account__c != NULL, Opportunity__c = NULL, Order__c = NULL), &apos;Account&apos;, 
IF(AND (Account__c != NULL, Opportunity__c != NULL, Order__c = NULL), &apos;Account, Opportunity&apos;, 
IF(AND (Account__c != NULL, Opportunity__c != NULL, Order__c != NULL), &apos;Account, Opportunity, Order&apos;, 
IF(AND (Account__c = NULL, Opportunity__c != NULL, Order__c = NULL), &apos;Opportunity&apos;, 
IF(AND (Account__c = NULL, Opportunity__c != NULL, Order__c != NULL), &apos;Opportunity, Order&apos;,
IF(AND (Account__c = NULL, Opportunity__c = NULL, Order__c != NULL), &apos;Order&apos;, &apos;&apos;
))))))</formula>
        <label>Linked Objects</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owned_By_User__c</fullName>
        <formula>Owner:User.FirstName + &apos; &apos; + Owner:User.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owned By User</label>
        <type>Text</type>
    </fields>
    <label>Content Metadata</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Content Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClsTestContentDocumentLinkTriggerHandler.cls
/****************************************************************************************************************
@Author        : Anuj Patel
@Date Created    : 05/19/2017
@Description    : Test Class covering methods from ContentDocumentLinkTrigger 
****************************************************************************************************************/
@isTest
public class ClsTestContentDocumentLinkTriggerHandler {

    @isTest Static void testInsertCDL(){
        test.startTest();
        List<ContentDocumentLink> AddCDL = new List<ContentDocumentLink>();
        list <Opportunity> oppList = new list <Opportunity>();
        
        Account Prescriber =  ClsTestDataBuilder.testPrescriberAccount();
        insert Prescriber;
		Account MedFac =  ClsTestDataBuilder.testMedFacAccount();
        insert MedFac;
        Account Payor =  ClsTestDataBuilder.testPayorAccount();
        insert Payor; 
        /** This will create an Account and add a document on Account **/ 
        Account AccObj = ClsTestDataBuilder.testAccount();
        AccObj.Prescriber__c = Prescriber.Id;
        AccObj.Medical_Facility__c = MedFac.Id;
        AccObj.Payor__c = Payor.Id;
        insert AccObj;
        /** This will create an Benefit Records  **/ 
        List<Benefit__c> bnf = new List<Benefit__c>();
        bnf =  ClsTestDataBuilder.getBenefits(AccObj.Id, Payor.Id, 1, 'Primary');
        insert bnf;
        bnf[0].account__c = AccObj.Id;
        AccObj.Benefit__c = bnf[0].id; 
        
        ContentVersion CvObj = ClsTestDataBuilder.testContentVersion();
		insert CvObj;
		CvObj = [SELECT ContentDocumentId FROM ContentVersion where Id = :CvObj.Id]; 
        ContentDocumentLink newFileShare = new ContentDocumentLink();
		newFileShare.ShareType = 'V' ;
		newFileShare.Visibility = 'AllUsers' ; 
        newFileShare.contentdocumentid = CvObj.contentdocumentid;
        newFileShare.LinkedEntityId = AccObj.Id;
		system.debug('Linked entity id is ' + newFileShare.LinkedEntityId);
        ClsCheckRecursive.run = true ;
        insert newFileShare;
      //  AddCDL.add(newFileShare);  // account inserted
         
        
        /** This will create an Opportunity and add a document on Opportunity **/    
        oppList = ClsTestDataBuilder.getOpportunityList(2, AccObj.Id, Payor.Id,Prescriber.Id, MedFac.Id, bnf[0].Id ); // Integer recLimit, Id acc, Id payor, ID Prescriber
        insert oppList;
	    ContentVersion CvObj2 = ClsTestDataBuilder.testContentVersion();
		insert CvObj2;
		CvObj2 = [SELECT ContentDocumentId FROM ContentVersion where Id = :CvObj2.Id]; 
        ContentDocumentLink newFileShare2 = new ContentDocumentLink();
		newFileShare2.ShareType = 'V' ;
		newFileShare2.Visibility = 'AllUsers' ; 
        newFileShare2.contentdocumentid = CvObj2.contentdocumentid;
        newFileShare2.LinkedEntityId = OppList[0].Id;
        AddCDL.add(newFileShare2);
        
		ContentVersion CvObj3 = ClsTestDataBuilder.testContentVersion();
		insert CvObj3;
		CvObj3 = [SELECT ContentDocumentId FROM ContentVersion where Id = :CvObj3.Id];
        ContentDocumentLink newFileShare3 = new ContentDocumentLink();
		newFileShare3.ShareType = 'V' ;
		newFileShare3.Visibility = 'AllUsers' ; 
        newFileShare3.contentdocumentid = CvObj3.contentdocumentid;
        newFileShare3.LinkedEntityId = OppList[1].Id;
        AddCDL.add(newFileShare3);
        ClsCheckRecursive.run = true ;
        insert AddCDL;
        
      /** 	List<ContentDocumentLink> newCDLs = [Select ID, contentdocumentid from ContentDocumentLink where ID In :AddCDL ];
        for(ContentDocumentLink c: newCDLs){
            System.assertEquals('V', c.ShareType);
        } **/
        for(ContentDocumentLink c: AddCDL){
        System.assertEquals('V', c.ShareType);
        System.assertEquals('AllUsers', c.Visibility);
        
        }
        List<Content_Metadata__c> ConMet = [Select Id, Name, Content_Document_Id__c, Linked_Objects__c, Document_Type__c, Owned_By_User__c, Document_Created_By_User__c, Document_Created_Date__c, Content_Size__c from Content_Metadata__c];
        ConMet[0].File_Type__c = 'SNOTE' ;
        update ConMet ;
        List<ContentDocument> ConDoc = [Select Id from ContentDocument];        
        delete ConDoc ;
        List<ContentDocument> ConDo = [Select Id from ContentDocument];        
        delete ConDo ;
        test.stopTest();
    }
}