src/objects/Content_Metadata__c.object
<CustomObject>
    <description>Object stores the metadata information about the file, which was uploaded</description>
    <fields>
        <fullName>Content_Document_Id__c</fullName>
        <description>Stores the ContentDocumentId of the file, which was uploaded</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Content Document Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Content_Size__c</fullName>
        <description>Records the content size of the document</description>
        <label>Size</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Document_Created_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person who created the document</description>
        <label>Document Created By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Content_Metadata</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Created_Date__c</fullName>
        <description>Created date of the document</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Document Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <description>This field tracks the document type to classify the documents.</description>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Empf</fullName>
                </value>
                <value>
                    <fullName>VO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>File_Extension__c</fullName>
        <description>Stores the file extension of the file, which was uploaded</description>
        <encryptionScheme>None</encryptionScheme>
        <label>File Extension</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Type__c</fullName>
        <description>Stores the file type, which was uploaded</description>
        <encryptionScheme>None</encryptionScheme>
        <label>File Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Latest_Content_Version_Id__c</fullName>
        <description>Latest content version for the document.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Latest Content Version Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Records the document source</description>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Document_Source</valueSetName>
        </valueSet>
    </fields>
    <label>Content Metadata</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Content Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClsContentVersionTriggerHandler.cls
/*******************************************************************************************************************
@Author        : Jagan Periyakaruppan
@Date Created    : 10/07/2018
@Description    : Trigger handler invokes the logic for Content Version
********************************************************************************************************************/
public class ClsContentVersionTriggerHandler {
    
    //This method will upsert the Content_Metadata__c based on the ContentDocumentId 
    public static void ProcessContentMetaData (List<ContentVersion> contentVersionsToBeProcessed)
    {
        List<Content_Metadata__c> customMetadataToBeUpsertedList = new List<Content_Metadata__c>();//Content Metadata List to be upserted 
        
        for(ContentVersion cv : contentVersionsToBeProcessed)
        {
            //For the regular Files uploaded, sync up the Content_Metadata__c record
            //if(cv.FileType != 'SNOTE')
            //{
            Content_Metadata__c contentMetadata = new Content_Metadata__c (Content_Document_Id__c = cv.ContentDocumentId);
            contentMetadata.Name = cv.Title;
            contentMetadata.Content_Document_Id__c = cv.ContentDocumentId;
            contentMetadata.Latest_Content_Version_Id__c = cv.Id;
            contentMetadata.Document_Created_By__c = cv.CreatedById;
            contentMetadata.Document_Created_Date__c = cv.CreatedDate;
            contentMetadata.Document_Type__c = cv.Document_Type__c;
            contentMetadata.OwnerId = cv.OwnerId;
            contentMetadata.File_Type__c = cv.FileType;
            contentMetadata.File_Extension__c = cv.FileExtension;
            contentMetadata.Content_Size__c = cv.ContentSize;
            contentMetadata.Source__c = cv.Source__c;
            customMetadataToBeUpsertedList.add(contentMetadata);
            //}	
        }
        if(!customMetadataToBeUpsertedList.isEmpty())
        {
            try{
                upsert customMetadataToBeUpsertedList Content_Document_Id__c;
            }catch(DmlException e) { System.debug('Exception occurred on Upserting Content_Metadata__c: ' + e.getMessage()); }
        }
    }
}