src/objects/Content_Metadata__c.object
<CustomObject>
    <description>Object stores the metadata information about the file, which was uploaded</description>
    <fields>
        <fullName>File_Type__c</fullName>
        <description>Stores the file type, which was uploaded</description>
        <encryptionScheme>None</encryptionScheme>
        <label>File Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Content Metadata</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Content Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClsContentMetadataTriggerHandler.cls
/*******************************************************************************************************************
@Author        : Jagan Periyakaruppan
@Date Created    : 10/07/2018
@Description    : Content_Metadata__c Trigger handler
********************************************************************************************************************/ 
public class ClsContentMetadataTriggerHandler {
    
    //Method deletes Content Metadata for Notes 
    public static void ProcessContentMetadataDeletes(List<Content_Metadata__c> contentMetadataToBeProcessedForDelete) 
    {
        Set<Id> contentMetadataDeleteSet = new Set<Id>();//Content Metadata List to be deleted
        
        //Loop through the Content Metadata records and delete the ones, which are Notes
        for(Content_Metadata__c cm : contentMetadataToBeProcessedForDelete)
        {
            if(cm.File_Type__c == 'SNOTE')
                contentMetadataDeleteSet.add(cm.Id);
        }
        //Delete the CustomMetaData
        if(!contentMetadataDeleteSet.isEmpty())
            DeleteContentMetadata(contentMetadataDeleteSet);
        
    }
    //Make a future call to delete the Content Metadata for Notes to avoid any trigger context errors
    @future
    public static void DeleteContentMetadata (Set<Id> contentMetadataDeleteSet)
    {
        List<Content_Metadata__c> contentMetataToBeDeleted = [SELECT Id FROM Content_Metadata__c WHERE Id IN : contentMetadataDeleteSet];
        try{
            delete contentMetataToBeDeleted;
        }catch(DmlException e) { System.debug('Exception occurred on deleting Content_Metadata__c: ' + e.getMessage()); }
    }
}