src/objects/Content_Metadata__c.object
<CustomObject>
    <description>Object stores the metadata information about the file, which was uploaded</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Captures the Account to which the file was linked</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Content Metadata</relationshipLabel>
        <relationshipName>Content_Metadata</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Content_Document_Id__c</fullName>
        <description>Stores the ContentDocumentId of the file, which was uploaded</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Content Document Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Content_Size__c</fullName>
        <description>Records the content size of the document</description>
        <label>Size</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Document_Created_By_User__c</fullName>
        <formula>CreatedBy.FirstName + &apos; &apos; + CreatedBy.LastName</formula>
        <label>Document Created By User</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Created_Date__c</fullName>
        <description>Created date of the document</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Document Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <description>This field tracks the document type to classify the documents.</description>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Empf</fullName>
                </value>
                <value>
                    <fullName>VO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Linked_Objects__c</fullName>
        <description>Field displays the Objects a particular document is linked</description>
        <formula>IF(AND (Account__c != NULL, Opportunity__c = NULL, Order__c = NULL), &apos;Account&apos;, 
IF(AND (Account__c != NULL, Opportunity__c != NULL, Order__c = NULL), &apos;Account, Opportunity&apos;, 
IF(AND (Account__c != NULL, Opportunity__c != NULL, Order__c != NULL), &apos;Account, Opportunity, Order&apos;, 
IF(AND (Account__c = NULL, Opportunity__c != NULL, Order__c = NULL), &apos;Opportunity&apos;, 
IF(AND (Account__c = NULL, Opportunity__c != NULL, Order__c != NULL), &apos;Opportunity, Order&apos;,
IF(AND (Account__c = NULL, Opportunity__c = NULL, Order__c != NULL), &apos;Order&apos;, &apos;&apos;
))))))</formula>
        <label>Linked Objects</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Account__c</fullName>
        <description>Account Id tied to Opportunity</description>
        <formula>CASESAFEID(Opportunity__r.AccountId)</formula>
        <label>Opportunity Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity to which the file is associated</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Content Metadata</relationshipLabel>
        <relationshipName>Content_Metadata</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Account__c</fullName>
        <description>Account tied to the Order</description>
        <formula>CASESAFEID(Order__r.AccountId)</formula>
        <label>Order Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Order to which the file is associated</description>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Content Metadata</relationshipLabel>
        <relationshipName>Content_Metadata</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Owned_By_User__c</fullName>
        <formula>Owner:User.FirstName + &apos; &apos; + Owner:User.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owned By User</label>
        <type>Text</type>
    </fields>
    <label>Content Metadata</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Content Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CtrlContentMetadataInformation.cls
public class CtrlContentMetadataInformation {
    @AuraEnabled
    //Method will retrieve the contentmetadata for the documents attached to a particular salesforce record
    public static List<Object> getContentMetadata  (String recordId) {
        //Find if the recordId is Opportunity or Account
        String oppAccntId;
        List<Object> accountList = new List<Object>();
        //If objectName is Opportunity then get the accountId corresponding to the Opp
        if(String.valueOf(recordId).substring(0,3) == '006'){
            List<Opportunity> oppList = new List<Opportunity>([SELECT Id, AccountId FROM Opportunity WHERE Id = : recordId]);
            if(!oppList.isEmpty()) oppAccntId = oppList[0].AccountId;
        }
 
        //Get the list of Content Metadata Types if the object referred to is only Account
        if(oppAccntId == null){
            accountList = [Select Id, Name, Content_Document_Id__c, Linked_Objects__c, Document_Type__c, Owned_By_User__c, Document_Created_By_User__c, Document_Created_Date__c, Content_Size__c from Content_Metadata__c Where Id = :recordId OR Account__c = :recordId OR Opportunity__c = :recordId OR Order__c = :recordId OR Opportunity_Account__c = :recordId OR Order_Account__c = :recordId Order by Document_Created_Date__c desc];
        }else //Get the list of Content Metadata Types if the object referred to Opportunity. In this case get both documents attached to Account and Opportunity object
        {
            accountList = [Select Id, Name, Content_Document_Id__c, Linked_Objects__c, Document_Type__c, Owned_By_User__c, Document_Created_By_User__c, Document_Created_Date__c, Content_Size__c from Content_Metadata__c Where Id = :recordId OR Account__c = :recordId OR Opportunity__c = :recordId OR Order__c = :recordId OR Opportunity_Account__c = :recordId OR Order_Account__c = :recordId OR Id = :oppAccntId OR Account__c = :oppAccntId OR Opportunity__c = :oppAccntId OR Order__c = :oppAccntId OR Opportunity_Account__c = :oppAccntId OR Order_Account__c = :oppAccntId Order by Document_Created_Date__c desc];
        }
        return accountList;
    }
}