src/objects/CRM_Account_Event__e.object
<CustomObject>
    <description>Platform event invoked from Kafka to Salesforce upon Account inserts and updates</description>
    <fields>
        <fullName>accountID__c</fullName>
        <label>accountID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>accountType__c</fullName>
        <label>accountType</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>countryCode__c</fullName>
        <label>countryCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>emailOptin__c</fullName>
        <label>emailOptin</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>entityType__c</fullName>
        <label>entityType</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eventDate__c</fullName>
        <label>eventDate</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eventSourceID__c</fullName>
        <label>eventSourceID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eventSource__c</fullName>
        <label>eventSource</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>firstName__c</fullName>
        <label>firstName</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>lastName__c</fullName>
        <label>lastName</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>middleName__c</fullName>
        <label>middleName</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>operation__c</fullName>
        <label>operation</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>personalEmail__c</fullName>
        <label>personalEmail</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>stage__c</fullName>
        <label>stage</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>systemOfOriginID__c</fullName>
        <label>systemOfOriginID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>systemOfOrigin__c</fullName>
        <label>systemOfOrigin</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>version__c</fullName>
        <label>version</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>CRM Account Event - In</label>
    <pluralLabel>CRM Account Events - In</pluralLabel>
</CustomObject>

src/classes/PEClsHandleAccountEvents_Test.cls
@isTest
public class PEClsHandleAccountEvents_Test {
    @isTest static void sfccPublishEvent() {
        // Create a test event instance
        CRM_Account_Event__e inkEvent = new CRM_Account_Event__e(accountID__c='MN-123', 
                                            accountType__c ='Consumer', eventDate__c = String.valueOf(System.now()), eventSource__c = 'ecom', eventSourceID__c = 'MN-123', lastName__c = 'Test', 
                                            firstName__c= 'First', middleName__c = 'Old', personalemail__c = 'testingPEs@tester.com',  countryCode__c = 'CA',
                                            systemOfOrigin__c = 'ecom', systemOfOriginID__c = 'MN-123', operation__c = 'create', stage__c = 'pending',
                                            version__c = '1.0', entityType__c = 'account', isActive__c = true);
        Test.startTest();
            // Publish test event
            Database.SaveResult sr = EventBus.publish(inkEvent);
        Test.stopTest();
        System.assertEquals(true, sr.isSuccess());
        List<Account> acts = [SELECT Id FROM Account];
        system.debug('Account Id: ' + acts[0].id);
        System.assertEquals(1, acts.size());
    }
    
    @isTest static void sfccUpdateEvent() {
        id recId = [Select id from recordType where DeveloperName = 'CA_Consumer' AND isActive = true].id;
        Account a = new Account(firstname = 'New',
                                lastname = 'test', recordtypeId = recId);
        insert a;
        List<Account> acts = [SELECT Id FROM Account];
        system.debug('Account Id: ' + acts[0].id);
        CRM_Account_Event__e  inkEvent = new CRM_Account_Event__e(accountID__c=a.id, middleName__c= 'New', 
                                accountType__c ='Consumer', eventDate__c = String.valueOf(System.now()), eventSource__c = 'ts', eventSourceID__c = 'MN-123', lastName__c= 'Test', firstName__c = 'null',
                                countryCode__c = 'CA', operation__c = 'update', stage__c = 'pending', isActive__c = true,
                                                                version__c = '1.0', entityType__c = 'account', emailOptin__c = 'True' ); 
        Test.startTest();
            // Publish test event
            Database.SaveResult sr = EventBus.publish(inkEvent);
        Test.stopTest();
        acts = [SELECT Id FROM Account where middlename = 'New'];
        System.assertEquals(1, acts.size());
    }
    
    @isTest static void oraRegisterEvent() {
        id recId = [Select id from recordType where DeveloperName = 'CA_Consumer' AND isActive = true].id;
        Account a = new Account(firstname = 'New',
                                lastname = 'test', recordtypeId = recId);
        insert a;
        List<Account> acts = [SELECT Id FROM Account];
        system.debug('Account Id: ' + acts[0].id);
        CRM_Account_Event__e  inkEvent = new CRM_Account_Event__e(accountID__c=a.id, middleName__c = 'New', 
                                accountType__c ='Consumer', eventDate__c = String.valueOf(System.now()), eventSource__c = 'oms', eventSourceID__c = 'MN-123', lastName__c = 'Test',
                                systemOfOriginID__c = a.id, systemOfOrigin__c = 'crm',   countryCode__c = 'CA', operation__c = 'create', stage__c = 'confirmed', firstName__c = 'null', isActive__c = true,
                                                                version__c = '1.0', entityType__c = 'account'); 
        
        Test.startTest();
            // Publish test event
            Database.SaveResult sr = EventBus.publish(inkEvent);
        	Test.getEventBus().deliver();
        Test.stopTest();
        acts = [SELECT Id FROM Account where sync_status__c = 'Created'];
       // System.assertEquals(1, acts.size());
    }
    @isTest static void ecomAccountConfirmedEvent() {
        id recId = [Select id from recordType where DeveloperName = 'CA_Consumer' AND isActive = true].id;
        Account a = new Account(firstname = 'New',
                                lastname = 'test', recordtypeId = recId);
        insert a;
        List<Account> acts = [SELECT Id FROM Account];
        system.debug('Account Id: ' + acts[0].id);
        CRM_Account_Event__e  inkEvent = new CRM_Account_Event__e(accountID__c=a.id, middleName__c = 'New', 
                                accountType__c ='Consumer', eventDate__c = String.valueOf(System.now()), eventSource__c = 'ecom', eventSourceID__c = 'MN-123', lastName__c = 'Test',
                                systemOfOriginID__c = a.id, systemOfOrigin__c = 'crm',   countryCode__c = 'CA', operation__c = 'create', stage__c = 'confirmed', firstName__c = 'null', isActive__c = true,
                                                                version__c = '1.0', entityType__c = 'account'); 
        Test.startTest();
            // Publish test event
            Database.SaveResult sr = EventBus.publish(inkEvent);
        Test.stopTest();
        acts = [SELECT Id FROM Account where SFCC_Account_Id__c = 'MN-123'];
        System.assertEquals(1, acts.size());
    }
    
    @isTest static void ecomCreateAndUpdateEvent() {
        // Create a test event instance
        List<CRM_Account_Event__e> inkEvents = new List<CRM_Account_Event__e>();
        CRM_Account_Event__e inkEvent = new CRM_Account_Event__e(accountID__c='MN-123', 
                                            accountType__c ='Consumer', eventDate__c = String.valueOf(System.now()), eventSource__c = 'ecom', eventSourceID__c = 'MN-123', lastName__c = 'Test', 
                                            firstName__c= 'First', middleName__c = 'Old', personalemail__c = 'testingPEs@tester.com', countryCode__c = 'CA',
                                            systemOfOrigin__c = 'ecom', systemOfOriginID__c = 'MN-123', operation__c = 'create', stage__c = 'pending',
                                            version__c = '1.0', entityType__c = 'account', isActive__c = true);
        inkEvents.add(inkEvent);
        inkEvent = new CRM_Account_Event__e(accountID__c='', 
                                            accountType__c ='Consumer', eventDate__c = String.valueOf(System.now()), eventSource__c = 'ecom', eventSourceID__c = 'MN-123', lastName__c = 'Test', 
                                            firstName__c= 'First', middleName__c = 'New', personalemail__c = 'testingPEs@tester.com',  countryCode__c = 'CA',
                                            systemOfOrigin__c = 'ecom', systemOfOriginID__c = 'MN-123', operation__c = 'update', stage__c = 'pending',
                                            version__c = '1.0', entityType__c = 'account', isActive__c = true);
        inkEvents.add(inkEvent);
        Test.startTest();
            // Publish test event
            List<Database.SaveResult> sr = EventBus.publish(inkEvents);
        Test.stopTest();
        System.assertEquals(true, sr[0].isSuccess());
        System.assertEquals(true, sr[1].isSuccess());
        List<Account> acts = [SELECT Id, MiddleName FROM Account];
        system.debug('Middle Name: '+ acts[0].MiddleName);
        System.assertEquals(1, acts.size());
    }
    @isTest static void sfdcTestAccountPublishUpdate() {
        id recId = [Select id from recordType where DeveloperName = 'CA_Consumer' AND isActive = true].id;
        Account a = new Account(firstname = 'New',
                                lastname = 'test', recordtypeId = recId);
        insert a;
        List<Account> acts = [SELECT Id FROM Account];
        a.FirstName = 'Brand New';
        Test.startTest();
        	update a;
            PEClsHandleAccountEventsStatic.firstEventPublish();
        Test.stopTest();
        //System.assert(PEClsHandleAccountEvents.eventList.size() == 1, 'Matching whether an update event got created');
        system.debug('Event List Size: ' + PEClsHandleAccountEvents.eventList.size());
    }
	@isTest static void sfdcTestAccountNotPublishUpdate() {
        id recId = [Select id from recordType where DeveloperName = 'CA_Consumer' AND isActive = true].id;
        Account a = new Account(firstname = 'New',
                                lastname = 'test', recordtypeId = recId, Blind__c = true);
        insert a;
        List<Account> acts = [SELECT Id FROM Account];
        a.Blind__c = false;
        Test.startTest();
        	update a;
        PEClsHandleAccountEventsStatic.firstEventPublish();
        Test.stopTest();
        System.assert(PEClsHandleAccountEvents.eventList.size() == 0, 'Matching whether an update event got created');
        //system.debug('Event List Size: ' + PEClsHandleAccountEvents.eventList.size());
    }
}