src/objects/Customer_Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Feedbacks</relationshipLabel>
        <relationshipName>Customer_Feedbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>High_Level_Feedback_Box__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>High Level Feedback</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Note_Box__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Note</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Resolution_Box__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Resolution</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Code 400 Data Entry</fullName>
                    <default>true</default>
                    <label>Code 400 Data Entry</label>
                </value>
                <value>
                    <fullName>Code 401 Billing Error</fullName>
                </value>
                <value>
                    <fullName>Code 402 Shipping Error</fullName>
                </value>
                <value>
                    <fullName>Code 403 Fulfillment Error</fullName>
                </value>
                <value>
                    <fullName>Code 404 Order Entry</fullName>
                </value>
                <value>
                    <fullName>Code 405 Lack of Follow Up</fullName>
                </value>
                <value>
                    <fullName>Code 406 Distributor</fullName>
                </value>
                <value>
                    <fullName>Code 407 Phone</fullName>
                </value>
                <value>
                    <fullName>Code 408 Clarity of Process</fullName>
                </value>
                <value>
                    <fullName>Code 409 Quoting Error</fullName>
                </value>
                <value>
                    <fullName>Code 410 Insurance</fullName>
                </value>
                <value>
                    <fullName>Code 411 Online Store</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Feedback</label>
    <nameField>
        <displayFormat>CF-{0000}</displayFormat>
        <label>Customer Feedback</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CLSCustomerFeedbackCon.cls
public class CLSCustomerFeedbackCon {

	@AuraEnabled    
    public Static Account getAccountDetails(String accRecId){
        System.debug('accRecId--'+accRecId);
    	Account accObj = new Account();
        if(accRecId !=null){
            accObj = [Select Id,Name From account where Id=:accRecId Limit 1];
        }
        return accObj;
    } 
    
    @AuraEnabled    
    public Static Map<String,String> getCFTypePicklist(){
        Map<String,String> options = new Map<String,String>();
        Schema.DescribeFieldResult fieldResult = Customer_Feedback__c.Type__c.getDescribe();
        List<Schema.PicklistEntry> pList = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry p: pList) {
            options.put(p.getValue(),p.getLabel());
        }
        return options;
    }
    
     @AuraEnabled    
    public Static void saveCustfeedbackDetails(Customer_Feedback__c recCF){
        try{
            insert recCF;
            System.debug('Insertion Successful--'+recCF.Id);
        }catch(Exception ex){
           System.debug('Insert Error at Line -'+ ex.getLineNumber()); 
        }
    }
    
    @AuraEnabled    
    public Static void updateCustfeedbackDetails(Customer_Feedback__c recCF,String custFeedbackId){
        try{
           recCF.Id=  Id.valueOf( custFeedbackId);
            update recCF;
            System.debug('Update Succesful--'+recCF.Id);
        }catch(Exception ex){
           System.debug('Update Error at Line -'+ ex.getLineNumber());
        }
    }
    
     @AuraEnabled    
    public Static List<Customer_Feedback__c> getCustomerFeedbackDetails(String accRecordId){
        List<Customer_Feedback__c> lstCustFeedback=  new List<Customer_Feedback__c>();
        if(accRecordId != null){
            lstCustFeedback = [SELECT Id, Name, Type__c, High_Level_Feedback_Box__c, Note_Box__c, 
                               Resolution_Box__c, Account__c 
                               FROM Customer_Feedback__c
                               where Account__c=:accRecordId
                              ];
        }
        return lstCustFeedback;
    }
}