src/objects/Finance_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Finance Details</relationshipLabel>
        <relationshipName>Finance_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Finance Detail</label>
    <nameField>
        <displayFormat>FD-{0000}</displayFormat>
        <label>Finance Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ClsJobMarkCardsNonPrimary.cls
public class ClsJobMarkCardsNonPrimary {
    public ClsJobMarkCardsNonPrimary(List<Finance_Detail__c> lstFDUpdToPrimary) {
        system.debug('***ENTERED ClsJobMarkCardsNonPrimary ****');
        List<Finance_Detail__c> lstFDUpdToNonPrimary= new List<Finance_Detail__c>();
        for(Finance_Detail__c redFD : lstFDUpdToPrimary){
            for(Finance_Detail__c fd : [Select Id, Primary__C from Finance_Detail__c where Id !=:redFD.Id AND Account__c=:redFD.Account__c AND Primary__c=true]){
                system.debug('***ID TO SET NON PRIMARY IS ' + fd.Id  + ' ****');
                fd.Primary__c=false;
                lstFDUpdToNonPrimary.Add(fd);                
            }
        } 
        if(lstFDUpdToNonPrimary.size()>0){
            update lstFDUpdToNonPrimary;  
            system.debug('***UPDATE COMPLETED ****');
        }
      
    }
}