src/objects/Fund__c.object
<CustomObject>
    <description>Object will track information related to Funded Patients.</description>
    <fields>
        <fullName>Amount_Limit__c</fullName>
        <description>Amount limit enforced in PO</description>
        <label>Amount Limit</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Auth_End_Date__c</fullName>
        <description>Date when the authorization ends</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Auth End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Auth_Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>Date when the authorization starts</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Auth Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Fund associated with the Payor.</description>
        <label>Payor</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Fund Payor should be of Payor type if using GBP or EUR. Otherwise Fund Currency should be in USD.</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>contains</operation>
                <value>Payor</value>
            </filterItems>
            <filterItems>
                <field>$Source.CurrencyIsoCode</field>
                <operation>equals</operation>
                <value>USD</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fund (Payor)</relationshipLabel>
        <relationshipName>Payor_Fund</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Receiver_Qty_Limit__c</fullName>
        <description>Qty of Receivers that can be used within the Authorized period</description>
        <label>Receiver Qty Limit</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sensor_Limit__c</fullName>
        <description>Qty of Sensors that can be used within the Authorized period</description>
        <label>Sensor Qty Limit</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transmitter_Qty_Limit__c</fullName>
        <description>Qty of Transmitters that can be used within the Authorized period</description>
        <label>Transmitter Qty Limit</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Fund</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>Fund Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fund</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClsFundTriggerHandler_Test.cls
@isTest()
private class ClsFundTriggerHandler_Test {
    @isTest private static void test(){
        Account payorAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'DE Payor', 'Germany')[0];
        Fund__c fund = new Fund__c(Payor__c = payorAccount.Id, Amount_Limit__c = 100000, Auth_End_Date__c = Date.today().addDays(100), Auth_Start_Date__c = Date.today(), 
                                   Receiver_Qty_Limit__c = 100, Sensor_Limit__c = 100, Transmitter_Qty_Limit__c = 100);
      	insert fund;
    }
}