src/objects/Fund__c.object
<CustomObject>
    <description>Object will track information related to Funded Patients.</description>
    <fields>
        <fullName>Country__c</fullName>
        <defaultValue>If(OR(BEGINS($Profile.Name , &apos;UK&apos;), BEGINS($Profile.Name , &apos;System&apos;)), &apos;United Kingdom&apos;, &apos;&apos;)</defaultValue>
        <description>Possible countries that can be selected defaulted based on the Profile</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <label>Fund</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>Fund Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fund</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SSIP_Rule__c.object
<CustomObject>
    <description>Object stores all SSIP rule for the customers.</description>
    <fields>
        <fullName>Account_18_Digit_Id__c</fullName>
        <description>Records 18 digit Id. Mainly used for Duplicate Rule logic.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Account 18 Digit Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <description>Master detail relationship to the account.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SSIP Rule</relationshipLabel>
        <relationshipName>SSIP_Rule</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country to which this rule is tied to</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>First Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>SSIP Rule</relationshipLabel>
        <relationshipName>SSIP_Rule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Repeat_Order_Lead_Days__c</fullName>
        <inlineHelpText>Lead days for the first shipment</inlineHelpText>
        <label>First Repeat Order Lead Days</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>First_Shipment_Date__c</fullName>
        <description>Date when the first shipment needs to happen for this Schedule. It cam be immediate or in the future and should fall between the Rule Start and End date.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Date should be within the Rule Start Date and Rule End Date (if applicable). This date is set with the first order is shipped. Setting this date will create the Schedules.</inlineHelpText>
        <label>First Shipment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Frequency_In_Days__c</fullName>
        <description>Schedule interval between each shipments.</description>
        <label>Frequency (In Days)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Term__c</fullName>
        <defaultValue>IF( $RecordType.DeveloperName = &apos;CH_SSIP_Rule&apos;, &apos;net30&apos;, &apos;net30&apos;)</defaultValue>
        <description>Payment terms that will be used to track the payment. The default value will be based on the country&apos; preference</description>
        <label>Payment Term</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Payment_Term</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Price book, which will filter out only SSIP Pricebooks</description>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>SSIP Rule</relationshipLabel>
        <relationshipName>SSIP_Rule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>SSIP Rule</relationshipLabel>
        <relationshipName>SSIP_Rule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rule_End_Date__c</fullName>
        <description>Date when the rule will end.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Date should be greater than or equal to today&apos;s date. Setting this date will delete any open schedules past this date.</inlineHelpText>
        <label>Rule End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Rule_Re_schedule_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Rule Re-schedule Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Schedule_Count__c</fullName>
        <description>Field holds the number of Schedules that can be created for this rule.</description>
        <inlineHelpText>Count determines how many schedules will be created at first for this Rule.</inlineHelpText>
        <label>Schedule Count</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shipping_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>List of all Ship To addresses tied to the customer.</description>
        <label>Shipping Address</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Address__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Address__c.Type__c</field>
                <operation>equals</operation>
                <value>Ship To</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>SSIP Rule</relationshipLabel>
        <relationshipName>SSIP_Rule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipping_Method__c</fullName>
        <description>Shipping method will be constrained by Country</description>
        <inlineHelpText>Chosen value will be defaulted to all the schedules associated to this Rule.</inlineHelpText>
        <label>Shipping Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Shipping_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&apos;Active&apos;</defaultValue>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>SSIP Rule</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SSIP Rule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SSIP_Schedule__c.object
<CustomObject>
    <description>Object stores all the schedules related to the rule.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Will be referencing the grand parent and will be defaulted at the time of the Schedule creation. Need this for constraining the addressed tied to the customer.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SSIP Schedule</relationshipLabel>
        <relationshipName>SSIP_Schedule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Will be defaulted from SSIP Rule at the time of creation.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Shipment_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Scheduled Shipment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fund__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fund</label>
        <referenceTo>Fund__c</referenceTo>
        <relationshipLabel>SSIP Schedule</relationshipLabel>
        <relationshipName>SSIP_Schedule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Term__c</fullName>
        <description>Will be defaulted from Parent SSIP Rule</description>
        <label>Payment Term</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Payment_Term</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <description>Product tied to the Rule</description>
        <formula>SSIP_Rule__r.Product_Name__c</formula>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rescheduled_Shipment_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Rescheduled Shipment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SSIP_Rule__c</fullName>
        <description>Master Detail relationship to the parent Rule.</description>
        <label>SSIP Rule</label>
        <referenceTo>SSIP_Rule__c</referenceTo>
        <relationshipLabel>SSIP Schedule</relationshipLabel>
        <relationshipName>SSIP_Schedule</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Schedule_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Schedule Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Shipping_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>List of all Ship To addresses tied to the customer.</description>
        <label>Changed Shipping Address</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Address__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Address__c.Type__c</field>
                <operation>equals</operation>
                <value>Ship To</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>SSIP Schedule</relationshipLabel>
        <relationshipName>SSIP_Schedule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipping_Method__c</fullName>
        <description>Shipping Method will be defaulted based on the country default value.</description>
        <label>Shipping Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Shipping_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&apos;Open&apos;</defaultValue>
        <description>Will be defaulted to Open. Depending on the Order processing other values will be set.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>In Error</fullName>
                </value>
                <value>
                    <fullName>In Draft</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SSIP Schedule</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SSIP Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Liechtenstein</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <customValue>
        <fullName>Ireland</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Chile</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Spain</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong</fullName>
    </customValue>
    <customValue>
        <fullName>Hungary</fullName>
    </customValue>
    <customValue>
        <fullName>Israel</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Jordan</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <customValue>
        <fullName>Korea</fullName>
    </customValue>
    <customValue>
        <fullName>Kuwait</fullName>
    </customValue>
    <customValue>
        <fullName>Lebanon</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>Norway</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>Oman</fullName>
    </customValue>
    <customValue>
        <fullName>Poland</fullName>
    </customValue>
    <description>Global picklist will be used in various places</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

src/globalValueSets/Payment_Term.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>net30</fullName>
        <label>30 NET</label>
    </customValue>
    <customValue>
        <fullName>45 NET</fullName>
    </customValue>
    <customValue>
        <fullName>Check(Net 10)</fullName>
    </customValue>
    <customValue>
        <fullName>Credit Card</fullName>
        <label>0 NET</label>
    </customValue>
    <customValue>
        <fullName>Insurance 30</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance 45</fullName>
    </customValue>
    <customValue>
        <fullName>No Charge</fullName>
    </customValue>
    <customValue>
        <fullName>net0</fullName>
        <label>Credit Card</label>
    </customValue>
    <customValue>
        <fullName>net60</fullName>
        <label>60 NET</label>
    </customValue>
    <customValue>
        <fullName>net90</fullName>
        <label>90 NET</label>
    </customValue>
    <customValue>
        <fullName>net-1</fullName>
        <label>Prepaid</label>
    </customValue>
    <masterLabel>Payment Term</masterLabel>
</GlobalValueSet>

src/classes/SSIPRuleTriggerHandler.cls
/**********************************************************************
@Description    : Class will handle logic for SSIPRule object
***********************************************************************/
public class SSIPRuleTriggerHandler {
    
    
    public void onBeforeInsert(List<SSIP_Rule__c> lstSSIPRuleNew){
        //Collection variables
        Set<Id> productIds = new Set<Id>();
        Set<Id> PBIds = new set<Id>();
        Map<Id, String> productNameMap = new Map<Id, String>();
        List<PricebookEntry> PBEItemList = new List<PricebookEntry>();
        //Prepares the product map for the rules that need to be updated with Product Name
        for(SSIP_Rule__c objSSIPRule : lstSSIPRuleNew){
            if(objSSIPRule.Product__c != null && objSSIPRule.Product_Name__c == null) productIds.add(objSSIPRule.Product__c);
           
            PBIds.add(objSSIPRule.Price_Book__c); 
        }
        if(!productIds.isEmpty()){
            for(Product2 prod : [SELECT Id, Name FROM Product2 WHERE Id IN : productIds])
                productNameMap.put(prod.Id, prod.Name);
        }
        for(PricebookEntry pbe : [select id, Name, UnitPrice, Pricebook2Id, Product2Id from PricebookEntry where Pricebook2Id IN :PBIds] )   PBEItemList.add(pbe); 
        
        system.debug('PBEItemList'+PBEItemList);
        //For every rule update the 18 digit account id and Product name based on the chosen product
        for(SSIP_Rule__c objSSIPRule : lstSSIPRuleNew)
        {
            objSSIPRule.Account_18_Digit_Id__c = objSSIPRule.Account__c;
            Boolean Prodfound = false;
            for(PricebookEntry PBE :PBEItemList){  
                if(PBE.Pricebook2Id == objSSIPRule.Price_Book__c && PBE.Product2Id == objSSIPRule.Product__c){                    
                    Prodfound = True ;
                    objSSIPRule.Unit_Price__c = PBE.UnitPrice;
                    
                }
            }
            if(!Prodfound){
                objSSIPRule.addError('Wrong combination of Product and Pricbook.');
                return;
            }  
            if(!productNameMap.isEmpty() && objSSIPRule.Product__c != null && objSSIPRule.Product_Name__c == null && productNameMap.containsKey(objSSIPRule.Product__c))
                objSSIPRule.Product_Name__c = productNameMap.get(objSSIPRule.Product__c);
        }    
        
       
    }
    
    public void onAfterInsert(List<SSIP_Rule__c> lstSSIPRuleNew){
        createSSIPScheduleRecord(lstSSIPRuleNew, new Map<Id,SSIP_Rule__c>());
    }
    
    public void onAfterUpdate(List<SSIP_Rule__c> lstSSIPRuleNew, Map<Id, SSIP_Rule__c> mapSSIPRuleOld){
        createSSIPScheduleRecord(lstSSIPRuleNew, mapSSIPRuleOld);
    }
    
    
    private void createSSIPScheduleRecord(List<SSIP_Rule__c> lstSSIPRuleNew, Map<Id, SSIP_Rule__c> mapSSIPRuleOld){
        Map<Id, SSIP_Rule__c> mapSSIPRuleNew = new Map<Id, SSIP_Rule__c>(lstSSIPRuleNew);
        Map<Id, Id> ruleToFundMap = new Map<Id, Id>();		
        Map<Id, List<SSIP_Schedule__c>> mapSSIPIdTolstSSIPSchedule = new Map<Id, List<SSIP_Schedule__c>>();
        List<SSIP_Schedule__c> lstSSIPSchedule = new List<SSIP_Schedule__c>();
        Set<SSIP_Schedule__c>  lstSSIPSet  = new Set<SSIP_Schedule__c>();        
        List<SSIP_Schedule__c> lstSSIPScheduleToDelete = new List<SSIP_Schedule__c>();
        Set<Id> setSSIPRuleId = new Set<Id>();
        
      
        //Find if the Rule has order association and prepare the map
        for(SSIP_Rule__c objSSIPRule : [SELECT Id, First_Order__r.Fund__c FROM SSIP_Rule__c WHERE First_Order__c != null AND Id IN: lstSSIPRuleNew]){
            if(objSSIPRule.First_Order__r.Fund__c != null)
                ruleToFundMap.put(objSSIPRule.Id, objSSIPRule.First_Order__r.Fund__c);
        }        
        
        //Process the SSIP Rule records to create Schedules
        for(SSIP_Rule__c objSSIPRule : lstSSIPRuleNew){
            System.debug('createSSIPScheduleRecord for loop');                
      
            Integer count = objSSIPRule.Schedule_Count__c != null ? Integer.valueOf(objSSIPRule.Schedule_Count__c) : 3;
            Integer firstRepeatOrderLeadDays = objSSIPRule.First_Repeat_Order_Lead_Days__c != null ? Integer.valueOf(objSSIPRule.First_Repeat_Order_Lead_Days__c) : 0;
            if((Trigger.isInsert && objSSIPRule.First_Shipment_Date__c != null) || (Trigger.isUpdate && mapSSIPRuleOld.get(objSSIPRule.Id).First_Shipment_Date__c == null && objSSIPRule.First_Shipment_Date__c != null) && objSSIPRule.Frequency_In_Days__c != null){
                for(Integer i = 1; i <= count; i++){
                    lstSSIPSchedule.add(new SSIP_Schedule__c(Account__c = objSSIPRule.Account__c, Country__c = objSSIPRule.Country__c, Payment_Term__c = objSSIPRule.Payment_Term__c, Shipping_Address__c = objSSIPRule.Shipping_Address__c,
                                                             Shipping_Method__c = objSSIPRule.Shipping_Method__c, SSIP_Rule__c = objSSIPRule.Id, Status__c = 'Open',
                                                             Fund__c = !ruleToFundMap.isEmpty() ? ruleToFundMap.get(objSSIPRule.Id) : null, 	
                                                             Schedule_Date__c = objSSIPRule.First_Shipment_Date__c.addDays(Integer.valueOf(objSSIPRule.Frequency_In_Days__c) * i) - firstRepeatOrderLeadDays));
                }
            }                        
            if(Trigger.isUpdate && ((mapSSIPRuleOld.get(objSSIPRule.Id).First_Shipment_Date__c != null && objSSIPRule.Rule_End_Date__c != mapSSIPRuleOld.get(objSSIPRule.Id).Rule_End_Date__c) 
                                    || mapSSIPRuleOld.get(objSSIPRule.Id).Payment_Term__c != objSSIPRule.Payment_Term__c || mapSSIPRuleOld.get(objSSIPRule.Id).Shipping_Method__c != objSSIPRule.Shipping_Method__c
                                    /*|| (objSSIPRule.Rule_Re_schedule_Date__c != null && mapSSIPRuleOld.get(objSSIPRule.Id).Rule_Re_schedule_Date__c != objSSIPRule.Rule_Re_schedule_Date__c ) */)){
                                       
                                        system.debug('objSSIPRule.Id = '+ objSSIPRule.Id);
                                        setSSIPRuleId.add(objSSIPRule.Id);
                                    }
            if(Trigger.isUpdate && (objSSIPRule.Rule_Re_schedule_Date__c != null && mapSSIPRuleOld.get(objSSIPRule.Id).Rule_Re_schedule_Date__c != objSSIPRule.Rule_Re_schedule_Date__c ))
                handleScheduleChange(objSSIPRule);
        }
        //Set Payment Term, Shipping Method from the Rule to the schedule records. Also delete all schedules once the Rule End Date is set on the Rule
        for(SSIP_Schedule__c objSSIPSchedule : [SELECT Id, SSIP_Rule__c, SSIP_Rule__r.Rule_End_Date__c, Rescheduled_Shipment_Date__c, Schedule_Date__c FROM SSIP_Schedule__c WHERE SSIP_Rule__c IN: setSSIPRuleId AND Status__c = 'Open']){
            System.debug('createSSIPScheduleRecord for loop 2');                
      
            //Process deletion logic first and then go to update logic
            //If the Reschedued Shipment Date is populated on the SSIP Schedule that takes the precedence
            if(objSSIPSchedule.Rescheduled_Shipment_Date__c != null && (objSSIPSchedule.Rescheduled_Shipment_Date__c > objSSIPSchedule.SSIP_Rule__r.Rule_End_Date__c))
                lstSSIPScheduleToDelete.add(objSSIPSchedule);
            else
                if(objSSIPSchedule.Rescheduled_Shipment_Date__c == null && (objSSIPSchedule.Schedule_Date__c > objSSIPSchedule.SSIP_Rule__r.Rule_End_Date__c))
                lstSSIPScheduleToDelete.add(objSSIPSchedule);
            else{
                if(mapSSIPRuleNew.get(objSSIPSchedule.SSIP_Rule__c).Payment_Term__c != mapSSIPRuleOld.get(objSSIPSchedule.SSIP_Rule__c).Payment_Term__c){
                    objSSIPSchedule.Payment_Term__c = mapSSIPRuleNew.get(objSSIPSchedule.SSIP_Rule__c).Payment_Term__c;
                }
                if(mapSSIPRuleNew.get(objSSIPSchedule.SSIP_Rule__c).Shipping_Method__c != mapSSIPRuleOld.get(objSSIPSchedule.SSIP_Rule__c).Shipping_Method__c){
                    objSSIPSchedule.Shipping_Method__c = mapSSIPRuleNew.get(objSSIPSchedule.SSIP_Rule__c).Shipping_Method__c;
                }    
                // Re-Scheduling ssip schedule  - Navneet
                /* This is being handled from else where.        
                if(Trigger.isUpdate && (mapSSIPRuleNew.get(objSSIPSchedule.SSIP_Rule__c).Rule_Re_schedule_Date__c != null && mapSSIPRuleNew.get(objSSIPSchedule.SSIP_Rule__c).Rule_Re_schedule_Date__c != mapSSIPRuleOld.get(objSSIPSchedule.SSIP_Rule__c).Rule_Re_schedule_Date__c) ){
                    Integer firstRepeatOrderLeadDays = mapSSIPRuleNew.get(objSSIPSchedule.SSIP_Rule__c).First_Repeat_Order_Lead_Days__c != null ? Integer.valueOf(mapSSIPRuleNew.get(objSSIPSchedule.SSIP_Rule__c).First_Repeat_Order_Lead_Days__c) : 7;
                    Date firstsDate = mapSSIPRuleNew.get(objSSIPSchedule.SSIP_Rule__c).First_Shipment_Date__c ;
                    Integer difdays = firstsDate.daysBetween(mapSSIPRuleNew.get(objSSIPSchedule.SSIP_Rule__c).Rule_Re_schedule_Date__c) ;
                    objSSIPSchedule.Rescheduled_Shipment_Date__c = objSSIPSchedule.Schedule_Date__c.addDays(difdays); 
                    //handleScheduleChange();
                }
				*/
                
                lstSSIPSchedule.add(objSSIPSchedule);
            }
        }
        delete lstSSIPScheduleToDelete;
        upsert lstSSIPSchedule;
        
    }
    public Static void handleScheduleChange(SSIP_Rule__c objSSIPRule) {
        List<SSIP_Schedule__c> scheds = [Select Id, Schedule_Date__c from SSIP_Schedule__c where SSIP_Rule__c = :objSSIPRule.id and Status__c = 'OPEN'];
        Integer count = objSSIPRule.Schedule_Count__c != null ? Integer.valueOf(objSSIPRule.Schedule_Count__c) : 3;
        Integer firstRepeatOrderLeadDays = objSSIPRule.First_Repeat_Order_Lead_Days__c != null ? Integer.valueOf(objSSIPRule.First_Repeat_Order_Lead_Days__c) : 0;
        List<SSIP_Schedule__c> lstSSIPSchedule = new List<SSIP_Schedule__c>();
        integer schedCounter = 0;
        for(SSIP_Schedule__c sched : scheds) {
            if (schedCounter == 0 && (objSSIPRule.Rule_End_Date__c == null ||  objSSIPRule.Rule_Re_schedule_Date__c <= objSSIPRule.Rule_End_Date__c)) 
                lstSSIPSchedule.add(new SSIP_Schedule__c(id=sched.Id, Schedule_Date__c = objSSIPRule.Rule_Re_schedule_Date__c));
            else if (objSSIPRule.Rule_End_Date__c == null  || objSSIPRule.Rule_Re_schedule_Date__c.adddays((Integer) ((objSSIPRule.Frequency_In_Days__c * schedCounter) - firstRepeatOrderLeadDays)) <= objSSIPRule.Rule_End_Date__c) 
                lstSSIPSchedule.add(new SSIP_Schedule__c(id=sched.Id, Schedule_Date__c = objSSIPRule.Rule_Re_schedule_Date__c.adddays((Integer) ((objSSIPRule.Frequency_In_Days__c * schedCounter) - firstRepeatOrderLeadDays))));
        	schedCounter++;
        }
        If (count > schedCounter) {
            for(Integer i = schedCounter; i < count; i++){
                if (objSSIPRule.Rule_End_Date__c == null  || objSSIPRule.Rule_Re_schedule_Date__c.adddays((Integer) ((objSSIPRule.Frequency_In_Days__c * i) - firstRepeatOrderLeadDays)) <= objSSIPRule.Rule_End_Date__c)
                        lstSSIPSchedule.add(new SSIP_Schedule__c(Account__c = objSSIPRule.Account__c, Country__c = objSSIPRule.Country__c, Payment_Term__c = objSSIPRule.Payment_Term__c, Shipping_Address__c = objSSIPRule.Shipping_Address__c,
                                                                 Shipping_Method__c = objSSIPRule.Shipping_Method__c, SSIP_Rule__c = objSSIPRule.Id, Status__c = 'Open',
                                                                 //Fund__c = !ruleToFundMap.isEmpty() ? ruleToFundMap.get(objSSIPRule.Id) : null, 	
                                                                 Schedule_Date__c = objSSIPRule.Rule_Re_schedule_Date__c.addDays(Integer.valueOf(objSSIPRule.Frequency_In_Days__c) * i) - firstRepeatOrderLeadDays));
            }
        }
        upsert lstSSIPSchedule;

    }
}