src/objects/Marketing_Interaction__c.object
<CustomObject>
    <description>Object used to trigger journeys in Marketing Cloud.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Marketing Interactions</relationshipLabel>
        <relationshipName>Marketing_Interactions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Communication_Type__c</fullName>
        <label>Communication Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CA - Customer Onboarding</fullName>
                </value>
                <value>
                    <fullName>CA - Product Onboarding - G5</fullName>
                </value>
                <value>
                    <fullName>CA - Reorder Reminder - G5</fullName>
                </value>
                <value>
                    <fullName>CA - Product Onboarding - G6</fullName>
                </value>
                <value>
                    <fullName>CA - Reorder Reminder - G6 Starter Kit</fullName>
                </value>
                <value>
                    <fullName>UKIE - Customer Onboarding - G6</fullName>
                </value>
                <value>
                    <fullName>UKIE - Customer Review</fullName>
                </value>
                <value>
                    <fullName>UKIE - Warrior Recruitment</fullName>
                </value>
                <value>
                    <fullName>UKIE - Subscription Renewal - G6</fullName>
                </value>
                <value>
                    <fullName>CA - Subscription Upsell - G6</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country should always be required for all records entered in this object.</description>
        <label>Country</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_Information__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Related Information</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Record_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Source Record Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Marketing Interaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Marketing Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SSIP_Rule__c.object
<CustomObject>
    <description>Object stores all SSIP rule for the customers.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Master detail relationship to the account.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SSIP Rule</relationshipLabel>
        <relationshipName>SSIP_Rule</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country to which this rule is tied to</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>SSIP Rule</relationshipLabel>
        <relationshipName>SSIP_Rule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Date when the contract can be renewed</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Date should be greater than or equal to today&apos;s date.</inlineHelpText>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&apos;Active&apos;</defaultValue>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SSIP Rule</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SSIP Rule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Liechtenstein</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <customValue>
        <fullName>Ireland</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Chile</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Spain</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong</fullName>
    </customValue>
    <customValue>
        <fullName>Hungary</fullName>
    </customValue>
    <customValue>
        <fullName>Israel</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Jordan</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <customValue>
        <fullName>Korea</fullName>
    </customValue>
    <customValue>
        <fullName>Kuwait</fullName>
    </customValue>
    <customValue>
        <fullName>Lebanon</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>Norway</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>Oman</fullName>
    </customValue>
    <customValue>
        <fullName>Poland</fullName>
    </customValue>
    <description>Global picklist will be used in various places</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

src/classes/BclsMarketingInteractionGBIEBatch.cls
global class BclsMarketingInteractionGBIEBatch implements database.Batchable<SObject>  {
 global Database.QueryLocator start(Database.BatchableContext bc){
     Date sixtyDate= date.today().adddays(60);
     Date todayDate= date.today();
       String SSIPQuery = 'SELECT Id, Account__c, Account__r.Id, Renewal_Date__c, ' + 
            'Product__c, Product__r.Name, Account__r.RecordType.DeveloperName ' + 
            'FROM SSIP_Rule__c'
            +' WHERE Status__c=\'Active\' AND ((Account__r.RecordType.DeveloperName =\'GB_Consumer\' OR Account__r.RecordType.DeveloperName =\'IE_Consumer\')' +
            'AND (Product__r.Name =\'MTRNTG611MOS\' OR Product__r.Name =\'MTRNTG612MOS\') AND (Renewal_Date__c<:sixtyDate AND Renewal_Date__c>:todayDate))';
     
     return Database.getQueryLocator(SSIPQuery);
 }
     global void execute(Database.BatchableContext bc, List<SObject> scope){
         Date sixDate= date.today();
         if(runningInASandbox()){
             sixdate=sixdate.addDays(-2);
         }
         else{
             sixdate=sixdate.addmonths(-6);
         }
         
         List<id> validDateId=new list<id>();
         map<id, SSIP_Rule__c> idToSSIP= new map<id,SSIP_Rule__c>();
         
         for(SSIP_Rule__c a : (List<SSIP_Rule__c>)scope){
             if(string.isNotBlank(a.Renewal_Date__c.format())){              
                     validDateId.add(a.Account__r.Id);
                     idToSSIP.put(a.Account__r.Id, a);
             }
         }
         for(marketing_interaction__c mi: [SELECT id, Account__c, CreatedDate FROM marketing_interaction__c WHERE account__c in :validDateId AND 
                                           Communication_Type__c='UKIE - Subscription Renewal - G6' ]){
             if(mi.CreatedDate>sixDate){
                 if(idToSSIP.containskey(mi.account__c)){
                     idToSSIP.remove(mi.account__c);
                 }
             }
         }
         List<marketing_interaction__c> newMI = new list<marketing_interaction__c>();
         for(SSIP_Rule__c a :idToSSIP.values()){
             marketing_interaction__c mi = new marketing_interaction__c();
             mi.Account__c=a.Account__r.Id;
             mi.Communication_Type__c='UKIE - Subscription Renewal - G6';
             mi.Source_Record_Id__c=a.id;
             mi.Related_Information__c=a.Renewal_Date__c.format();
             if(a.Account__r.RecordType.DeveloperName =='GB_Consumer'){
                 mi.Country__c='United Kingdom';
             }else{
                 mi.Country__c='Ireland';
             }
             newMI.add(mi);
         }
        insert newMI; 
     }
    public static Boolean runningInASandbox() {
        return [SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox;
    }
    
     global void finish(Database.BatchableContext bc){
     }
}