src/objects/Marketing_Interaction__c.object
<CustomObject>
    <description>Object used to trigger journeys in Marketing Cloud.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Marketing Interactions</relationshipLabel>
        <relationshipName>Marketing_Interactions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Communication_Type__c</fullName>
        <label>Communication Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CA - Customer Onboarding</fullName>
                </value>
                <value>
                    <fullName>CA - Product Onboarding - G5</fullName>
                </value>
                <value>
                    <fullName>CA - Reorder Reminder - G5</fullName>
                </value>
                <value>
                    <fullName>CA - Product Onboarding - G6</fullName>
                </value>
                <value>
                    <fullName>CA - Reorder Reminder - G6 Starter Kit</fullName>
                </value>
                <value>
                    <fullName>UKIE - Customer Onboarding - G6</fullName>
                </value>
                <value>
                    <fullName>UKIE - Customer Review</fullName>
                </value>
                <value>
                    <fullName>UKIE - Warrior Recruitment</fullName>
                </value>
                <value>
                    <fullName>UKIE - Subscription Renewal - G6</fullName>
                </value>
                <value>
                    <fullName>CA - Subscription Upsell - G6</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country should always be required for all records entered in this object.</description>
        <label>Country</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_Information__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Related Information</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Record_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Source Record Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Marketing Interaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Marketing Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Liechtenstein</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <customValue>
        <fullName>Ireland</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Chile</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Spain</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong</fullName>
    </customValue>
    <customValue>
        <fullName>Hungary</fullName>
    </customValue>
    <customValue>
        <fullName>Israel</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Jordan</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <customValue>
        <fullName>Korea</fullName>
    </customValue>
    <customValue>
        <fullName>Kuwait</fullName>
    </customValue>
    <customValue>
        <fullName>Lebanon</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>Norway</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>Oman</fullName>
    </customValue>
    <customValue>
        <fullName>Poland</fullName>
    </customValue>
    <description>Global picklist will be used in various places</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

src/classes/BclsMarketingInteractionCABatch.cls
global class BclsMarketingInteractionCABatch implements database.Batchable<SObject>  {
 global Database.QueryLocator start(Database.BatchableContext bc){
     Date ninetyDate= date.today().adddays(-90);
         Date onehundredDate= date.today().adddays(-100);
       String accountBaseQuery = 'SELECT Id, PersonEmail, PersonContactID, ' + 
            'G6_Transmitter_Ship_Date__c, G6_Starter_Kit_Ship_Date__c ' + 
            'FROM Account ' + 
            'WHERE RecordType.DeveloperName =\'CA_Consumer\' AND G6_Transmitter_Ship_Date__c<:ninetyDate'+
           ' AND G6_Transmitter_Ship_Date__c>:onehundredDate';
     
     return Database.getQueryLocator(accountBaseQuery);
 }
     global void execute(Database.BatchableContext bc, List<SObject> scope){
         
         List<id> validDateId=new list<id>();
         map<id, account> idToAccount= new map<id,account>();
         
         for(Account a : (List<Account>)scope){
            // if(a.G6_Transmitter_Ship_Date__c<ninetyDate && a.G6_Transmitter_Ship_Date__c>onehundredDate){                 
                 validDateId.add(a.id);
                 idToAccount.put(a.id, a);
             //}
         }
         for(marketing_interaction__c mi: [SELECT id, Account__c FROM marketing_interaction__c WHERE account__c in :validDateId AND Communication_Type__c='CA - Subscription Upsell - G6']){
             if(idToAccount.containskey(mi.account__c)){
                 idToAccount.remove(mi.account__c);
             }
         }
         List<marketing_interaction__c> newMI = new list<marketing_interaction__c>();
         for(Account a :idToAccount.values()){
             marketing_interaction__c mi = new marketing_interaction__c();
             mi.Account__c=a.id;
             mi.Communication_Type__c='CA - Subscription Upsell - G6';
             mi.Source_Record_Id__c=a.id;
             if(a.G6_Transmitter_Ship_Date__c==a.G6_Starter_Kit_Ship_Date__c){
                 mi.Related_Information__c='True';
             }else{
                 mi.Related_Information__c='False';
             }
             mi.Country__c='Canada';
             newMI.add(mi);
         }
        insert newMI; 
     }
    
     global void finish(Database.BatchableContext bc){
     }
}