src/objects/Marketing_Interaction__c.object
<CustomObject>
    <description>Object used to trigger journeys in Marketing Cloud.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Marketing Interactions</relationshipLabel>
        <relationshipName>Marketing_Interactions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Communication_Type__c</fullName>
        <label>Communication Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CA - Customer Onboarding</fullName>
                </value>
                <value>
                    <fullName>CA - Product Onboarding - G5</fullName>
                </value>
                <value>
                    <fullName>CA - Reorder Reminder - G5</fullName>
                </value>
                <value>
                    <fullName>CA - Product Onboarding - G6</fullName>
                </value>
                <value>
                    <fullName>CA - Reorder Reminder - G6 Starter Kit</fullName>
                </value>
                <value>
                    <fullName>UKIE - Customer Onboarding - G6</fullName>
                </value>
                <value>
                    <fullName>UKIE - Customer Review</fullName>
                </value>
                <value>
                    <fullName>UKIE - Warrior Recruitment</fullName>
                </value>
                <value>
                    <fullName>UKIE - Subscription Renewal - G6</fullName>
                </value>
                <value>
                    <fullName>CA - Subscription Upsell - G6</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Marketing Interaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Marketing Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BclsMarketingInteractionCATest.cls
@isTest()
public class BclsMarketingInteractionCATest {
@isTest
    static void testHourlyEmailScheduledJob() {
        //insert TestDataBuilder.testURLExpiryVal();

        List<Account> accountList= new List<Account>();
        Date ninetyDate= date.today().adddays(-95);
        Account testAccount = TestUtils.testCAConsumerAccount();
        testAccount.PersonEmail='jane.smith@sundog.net';
        testAccount.Email_Opt_In_Method__c = 'Via Email';
        testAccount.G6_Transmitter_Ship_Date__c=ninetyDate;
        
            
        insert testAccount;
        
        Test.startTest();
        String jobId = System.schedule('testScheduled', '0 0 0 3 9 ? 2052', new SclsMarketingInteractionCASchedule());
        
        BclsMarketingInteractionCABatch sbatch = new BclsMarketingInteractionCABatch();
        Id batchInstanceId = Database.executeBatch(sbatch, 1);
        
        Test.stopTest();
        
        List<marketing_interaction__c> m= [SELECT id, Account__c FROM marketing_interaction__c WHERE account__c = :testAccount.Id 
                                           AND Communication_Type__c='CA - Subscription Upsell - G6'];
        
        System.assertEquals(1, m.size());
        
    }
        
        
}