src/objects/Marketing_Interaction__c.object
<CustomObject>
    <description>Object used to trigger journeys in Marketing Cloud.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Marketing Interactions</relationshipLabel>
        <relationshipName>Marketing_Interactions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Communication_Type__c</fullName>
        <label>Communication Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CA - Customer Onboarding</fullName>
                </value>
                <value>
                    <fullName>CA - Product Onboarding - G5</fullName>
                </value>
                <value>
                    <fullName>CA - Reorder Reminder - G5</fullName>
                </value>
                <value>
                    <fullName>CA - Product Onboarding - G6</fullName>
                </value>
                <value>
                    <fullName>CA - Reorder Reminder - G6 Starter Kit</fullName>
                </value>
                <value>
                    <fullName>UKIE - Customer Onboarding - G6</fullName>
                </value>
                <value>
                    <fullName>UKIE - Customer Review</fullName>
                </value>
                <value>
                    <fullName>UKIE - Warrior Recruitment</fullName>
                </value>
                <value>
                    <fullName>UKIE - Subscription Renewal - G6</fullName>
                </value>
                <value>
                    <fullName>CA - Subscription Upsell - G6</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Marketing Interaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Marketing Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SSIP_Rule__c.object
<CustomObject>
    <description>Object stores all SSIP rule for the customers.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Master detail relationship to the account.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SSIP Rule</relationshipLabel>
        <relationshipName>SSIP_Rule</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Price book, which will filter out only SSIP Pricebooks</description>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>SSIP Rule</relationshipLabel>
        <relationshipName>SSIP_Rule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>SSIP Rule</relationshipLabel>
        <relationshipName>SSIP_Rule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Date when the contract can be renewed</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Date should be greater than or equal to today&apos;s date.</inlineHelpText>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&apos;Active&apos;</defaultValue>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SSIP Rule</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SSIP Rule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BclsMarketingInteractionGBIETest.cls
@isTest()
public class BclsMarketingInteractionGBIETest {
@isTest
    static void testHourlyEmailScheduledJob() {
        //insert TestDataBuilder.testURLExpiryVal();

        List<Account> accountList= new List<Account>();
        Date tenDate= date.today().adddays(10);
        Account testAccount = TestUtils.testGBConsumerAccount();
        testAccount.PersonEmail='jane.smith@sundog.net';
        testAccount.Email_Opt_In_Method__c = 'Via Email';
        
            
        insert testAccount;

         //Create Pricebook
        Map<String, Id> customPricebookMap = ClsTestDataFactory.createCustomPricebook(new List <String>{'UK G6 SUBSCRIPTION 12MOS'});
        String customPricebookId = customPricebookMap.get('UK G6 SUBSCRIPTION 12MOS');
        
        //Create Products
        Map<String, Id> products = ClsTestDataFactory.createProducts(new List<String> {'MTRNTG612MOS'});

        //Create Pricebook EntryPair
        Map<Id, Decimal> productIdToPriceMap = new Map<Id, Decimal>();
        productIdToPriceMap.put(products.get('MTRNTG612MOS'), 125.00);
        Map<Id, Id> productIdToPbeId = ClsTestDataFactory.createCustomPricebookEntries(productIdToPriceMap, customPricebookId);

        SSIP_Rule__c ssip = new SSIP_Rule__c();
        ssip.Account__c=testAccount.Id;
        ssip.Renewal_Date__c=tenDate;
        ssip.Price_Book__c = customPricebookId;
        ssip.product__c=products.get('MTRNTG612MOS');
        ssip.Status__c='Active';
        insert ssip;
        
        Test.startTest();
        String jobId = System.schedule('testScheduled', '0 0 0 3 9 ? 2052', new SclsMarketingInteractionGBIEScheduled());
        
        BclsMarketingInteractionGBIEBatch sbatch = new BclsMarketingInteractionGBIEBatch();
        Id batchInstanceId = Database.executeBatch(sbatch, 1);
        
        Test.stopTest();
        
        List<marketing_interaction__c> m= [SELECT id, Account__c FROM marketing_interaction__c WHERE account__c = :testAccount.Id 
                                           AND Communication_Type__c='UKIE - Subscription Renewal - G6'];
        
        System.assertEquals(1, m.size());
        
    }
        
        
}