src/objects/Platform_Event_Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <description>What was the Action when this error occurred.</description>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Publish</fullName>
                </value>
                <value>
                    <fullName>Consume</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Class_And_Method__c</fullName>
        <description>Class and method that is writing the Error.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Class and method that is writing the Error.</inlineHelpText>
        <label>Class And Method</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Handling_Status__c</fullName>
        <label>Error Handling Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Ignored</fullName>
                </value>
                <value>
                    <fullName>Assigned to Source System</fullName>
                </value>
                <value>
                    <fullName>Fixing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>Short error message. Typically from the program making this entry.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Error message from the program that caught the exception.</inlineHelpText>
        <label>Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EventSource__c</fullName>
        <description>Source of the Event. In Publish scenario, it is SELF.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>SELF or some external system that created the source event.</inlineHelpText>
        <label>EventSource</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_String__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Event String</label>
        <length>100000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>The name of the event that was being processed when this error occurred.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Name of the Event when this error happened.</inlineHelpText>
        <label>Object</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Error__c</fullName>
        <description>Full exception error message.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Full exception error message.</inlineHelpText>
        <label>Event</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ExternalID__c</fullName>
        <description>The ID in the System that Published the Event. Would be null in Publish Action.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Nulll if Publishing or ID in the consuming event.</inlineHelpText>
        <label>ExternalID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <description>Error severity.</description>
        <label>Severity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fatal Error - Bailing out</fullName>
                </value>
                <value>
                    <fullName>Recoverable Error - Published/Consumed</fullName>
                </value>
                <value>
                    <fullName>Error Ignored</fullName>
                </value>
                <value>
                    <fullName>Informational</fullName>
                </value>
                <value>
                    <fullName>Success Log</fullName>
                </value>
                <value>
                    <fullName>Error-In</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Platform Event Error Log</label>
    <nameField>
        <displayFormat>PEEL-{0000000}</displayFormat>
        <label>Error</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Platform Event Error Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ErrorUtility.cls
public class ErrorUtility {
    public static String LogError(String action, String classNMethodName, String errorMsg, String eventType, String eventSource, String exceptionError, String externalID, String severity){
      	//if (severity != 'Success Log') {
            try{
                insert new Platform_Event_Error_Log__c(Error_Handling_Status__c = 'New', Action__c = action, Class_And_Method__c = classNMethodName,
                                                       Error_Message__c = exceptionError.left(255), Event__c = eventType, EventSource__c = eventSource,
                                                       Exception_Error__c = errorMsg, ExternalID__c = externalID, Severity__c = severity);
                return 'Successfully!';
            }catch(Exception ex){
                return 'Error! ' + ex.getMessage();
            }
        //} else return 'Ignored';
    }
    public static String LogErrorWithEvent(String action, String classNMethodName, String errorMsg, String eventType, String eventSource, String exceptionError, String externalID, String severity, String event){
      	 //if (severity != 'Success Log') {
            try{
     
                insert new Platform_Event_Error_Log__c(Error_Handling_Status__c = 'New', Action__c = action, Class_And_Method__c = classNMethodName,
                                                       Error_Message__c = exceptionError.left(255), Event__c = eventType, EventSource__c = eventSource,
                                                       Exception_Error__c = errorMsg, ExternalID__c = externalID, Severity__c = severity, Event_String__c = event);
                return 'Successfully!';
            }catch(Exception ex){
                return 'Error! ' + ex.getMessage();
            }
      // } else return 'Ignored';
    }
    
    public static Platform_Event_Error_Log__c prepareErroLog(String action, String classNMethodName, String errorMsg, String eventType, String eventSource, String exceptionError, String externalID, String severity, String event){
        return new Platform_Event_Error_Log__c(Error_Handling_Status__c = 'New', Action__c = action, Class_And_Method__c = classNMethodName,
                                               Error_Message__c = exceptionError.left(255), Event__c = eventType, EventSource__c = eventSource,
                                               Exception_Error__c = errorMsg, ExternalID__c = externalID, Severity__c = severity, Event_String__c = event);
    }
}