src/objects/Record_Updater__c.object
<CustomObject>
    <description>To be used for updating any Object&apos;s individual field. Logic can be implemented in batch jobs to pull multiple fields for a given record and updated at once.</description>
    <fields>
        <fullName>Acted_On__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If the Record&apos;s action was completed. This is to be used to find out which actions already took place.</description>
        <label>Acted On</label>
        <type>Checkbox</type>
    </fields>
    <label>Record Updater</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Record Updater</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BClsRecordUpdaterPurger.cls
global class BClsRecordUpdaterPurger implements Database.Batchable<Sobject> {
	global Database.QueryLocator start(Database.BatchableContext BC){
        //((STATUS__c = 'OPEN') OR (STATUS__c = 'IN ERROR' AND TRY_TO_CREATE_OREDER__c = TRUE))
        String query = 'Select Id from Record_Updater__c where  Acted_On__c = true';
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<Record_Updater__c> scope){
        delete scope;
    }
    global void finish(Database.BatchableContext BC){
        
    }
}