src/objects/Related_Account__c.object
<CustomObject>
    <description>Jagan 04/25/2017 - Object holds many to many relationship between Accounts.</description>
    <fields>
        <fullName>Child_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field holds the child account (Prescriber) information</description>
        <label>Child Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>contains</operation>
                <value>Prescriber, Facility, Pharmacy</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Parent Accounts</relationshipLabel>
        <relationshipName>Related_Child_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Child_Relation_Type__c</fullName>
        <description>Record type corresponding to the Child Account in the relationship.</description>
        <formula>MID(Child_Account__r.RecordType.Name, 4, LEN(Child_Account__r.RecordType.Name))</formula>
        <label>Child Relation Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field holds the parent account information</description>
        <label>Parent Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>contains</operation>
                <value>Facility, Hospital, Payor, Pharmacy</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Child Accounts</relationshipLabel>
        <relationshipName>Related_Parent_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Relation_Type__c</fullName>
        <description>Record type corresponding to the Parent Account in the relationship.</description>
        <formula>MID(Parent_Account__r.RecordType.Name, 4, LEN(Parent_Account__r.RecordType.Name))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Relation Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Tracks the primary association</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Related Account</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClsRelatedAccountTriggerHandlerHelper.cls
/****************************************************************************************************************
@Author        : Jagan Periyakaruppan
@Date Created    : 5/01/2017
@Description    : Class used in as a helper class for ClsRelatedAccountTriggerHandler
****************************************************************************************************************/
public class ClsRelatedAccountTriggerHandlerHelper{
    
    public static Map<Id, List<Related_Account__c>> GetPrimaryRelatedAccountsTiedToAccount(List<Id> accountIdsToProcess, List<Related_Account__c> primaryRelatedAccounts, String parentRelationType, String childRelationType)
    {
        
        Map<Id, List<Related_Account__c>> accntIdPrimaryRelatedAccountMap = new Map<Id, List<Related_Account__c>>();//Map holds the List of primary related accounts tied to an account
        
        //Create a map between account id and list of primary related accounts
		for(Related_Account__c relAccnt : [SELECT Parent_Account__c, Child_Account__c, Primary_Flag__c FROM Related_Account__c WHERE Primary_Flag__c = true AND Child_Account__c IN : accountIdsToProcess AND Id NOT IN : primaryRelatedAccounts AND Parent_Relation_Type__c =: parentRelationType AND Child_Relation_Type__c =: childRelationType])	
        {
            system.debug('----Entering the process of GetPrimaryRelatedAccountsTiedToAccount');
            system.debug('----Related Account Id is ' + relAccnt.Id);
			//Remove the primary flag
			relAccnt.Primary_Flag__c = false;
			//Map the account id to its possible primary related accounts, which are to be reset
			if(accntIdPrimaryRelatedAccountMap.containsKey(relAccnt.Child_Account__c)) 
			{
				List<Related_Account__c> relAccntList = accntIdPrimaryRelatedAccountMap.get(relAccnt.Child_Account__c);
				relAccntList.add(relAccnt);
				accntIdPrimaryRelatedAccountMap.put(relAccnt.Child_Account__c, relAccntList);
			}
			else
			{
				accntIdPrimaryRelatedAccountMap.put(relAccnt.Child_Account__c, new List<Related_Account__c> {relAccnt});
			}
        }
        system.debug('----Ending the process of GetPrimaryRelatedAccountsTiedToAccount');
		return(accntIdPrimaryRelatedAccountMap);
    }
}