src/objects/SSIP_Rule__c.object
<CustomObject>
    <description>Object stores all SSIP rule for the customers.</description>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Date when the contract can be renewed</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Date should be greater than or equal to today&apos;s date.</inlineHelpText>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Rule_End_Date__c</fullName>
        <description>Date when the rule will end.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Date should be greater than or equal to today&apos;s date. Setting this date will delete any open schedules past this date.</inlineHelpText>
        <label>Rule End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&apos;Active&apos;</defaultValue>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SSIP Rule</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SSIP Rule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BClsSSIPRuleDeactivate.cls
global class BClsSSIPRuleDeactivate implements Database.Batchable<Sobject>{
	private final Date sdt;
    private final Date edt;
    public BClsSSIPRuleDeactivate(){
        this.sdt = Date.today();
        this.edt = Date.today();
    }
    public BClsSSIPRuleDeactivate(Date sdt, Date edt){
        this.sdt = sdt;
        this.edt = edt == null ? sdt : edt;
    }
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator('SELECT Id, Status__c, Renewal_date__c, Rule_End_Date__c FROM SSIP_Rule__c WHERE Status__c = \'Active\' AND ((Rule_End_Date__c >=:sdt AND Rule_End_Date__c <=: edt) or ( renewal_date__c >= :sdt AND Renewal_Date__c <= :edt))');
    }
    global void execute(Database.BatchableContext BC, List<SSIP_Rule__c> scope){
        for(SSIP_Rule__c ssipRule : scope){
            if (ssipRule.Rule_End_Date__c >= sdt && ssipRule.Rule_End_Date__c <= edt)   ssipRule.Status__c = 'Inactive';
            else if (ssipRule.Renewal_date__c >= sdt && ssipRule.Renewal_date__c <= edt)   ssipRule.Renewal_date__c = ssipRule.Renewal_date__c + 360;
        }
        update scope;
    }
    global void finish(Database.BatchableContext BC){
        
    }
}