src/objects/Zip_to_Terr__c.object
<CustomObject>
    <description>Jagan 04/2/2017 - Created this object to hold zip to terr alignment information for all countries.</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>District</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Region</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Territory</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Zip to Terr</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip to Terrs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Liechtenstein</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <customValue>
        <fullName>Ireland</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Chile</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Spain</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong</fullName>
    </customValue>
    <customValue>
        <fullName>Hungary</fullName>
    </customValue>
    <customValue>
        <fullName>Israel</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Jordan</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <customValue>
        <fullName>Korea</fullName>
    </customValue>
    <customValue>
        <fullName>Kuwait</fullName>
    </customValue>
    <customValue>
        <fullName>Lebanon</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>Norway</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>Oman</fullName>
    </customValue>
    <customValue>
        <fullName>Poland</fullName>
    </customValue>
    <description>Global picklist will be used in various places</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

src/classes/ClsLeadTerritoryTriggerHandler.cls
/*******************************************************************************************************************
@Author        : Navneet
@Date Created    : 19/12/2019
@Description    : Trigger invokes handler class to process territory
********************************************************************************************************************/    
 
public class ClsLeadTerritoryTriggerHandler {
    
    static Map<ID,Schema.RecordTypeInfo> recordTypesMap = ClsApexUtil.getRecordTypeId('Lead');
    
    //Method invoked on Account insert
    public static void OnBeforeInsert(List<Lead> LeadsToProcess, String country){
        String batch;
        if(LeadsToProcess.size()>0){
            ZiptoAlignUpdate(LeadsToProcess,batch, country); //Finds the zip to align
            LeadTerritoryUpdate(LeadsToProcess,batch, country); //Leads territory fields are updated
        }
    }
    
    //Method invoked on Account before update
    public static void OnBeforeUpdate(List<Lead> Leads,Map <Id,Lead> LeadsOldMap, String country){
        List<Lead> leadList = New List<Lead>();
        String batch;
        for(Lead le: Leads) {   
            Lead OldLead = LeadsOldMap.get(le.ID);
            System.debug('**CurrentPost'+le.PostalCode+'**Old'+OldLead.PostalCode);
            if(le.PostalCode != OldLead.PostalCode){
                   leadList.add(le); 
               }
        }
        if(leadList.size()>0){
            ZiptoAlignUpdate(leadList,batch, country);
            LeadTerritoryUpdate(leadList,batch, country);
        }
    }   

    //This Method finds the zip to align the lead    
    public static void ZiptoAlignUpdate(List<Lead> leadsToProcess,String batch, String country){
        system.debug('-----Leads to process - ' + leadsToProcess.size());
        List<Lead> leadList = new List<Lead>();
       
        Integer Ziplength = 0 ;
		switch on country {
			when 'DE' {
				Ziplength = 5;
			}
			when 'CA' {
				Ziplength = 3;
			}
			when 'CH' {
				Ziplength = 4;
			}
			when 'AT' {
				Ziplength = 4;
			}
		}

        system.debug('-country - ' + country);
        system.debug('-Ziplength - ' + Ziplength);
        for(Lead le: leadsToProcess) {
			String zipToProcess ;
			
			zipToProcess =   le.PostalCode ;
			
            //Do not proceed if Zip is null
			if(!String.isBlank(zipToProcess))
			{
				   if(country == 'GB' || country == 'IE')
					   {
						   le.Zip_To_Align__c = zipToProcess.substringBefore(' ');
						   leadList.add(le);
					   }
					   else
					   if(zipToProcess.length() >= Ziplength && zipToProcess.substring(0,Ziplength) != null){  
						   le.Zip_To_Align__c = zipToProcess.substring(0,Ziplength);
						   leadList.add(le);
						 }
				   
					system.debug('-----Zip for account id for processing  - ' + le.Id);   
					
			}
            
        } 
        //Perform DML Operation
        try{
            if((leadList.size()>0) && batch != null){             
                update leadList;
            }
        }catch(DMLException ex){
            system.debug('***ERROR UPDATE*** ' + ex.getMessage());
        }
    }
    //This method will update the territory alignment field on the Lead (Territory, Region and District)
    public static void LeadTerritoryUpdate(List<Lead> leadsToProcess,String batch, String country){
        set<string> zipcodes = new set<string>();  
        List<Lead> leadList = new List<Lead>(); 
        map<string,string> zipToTerMap = new map<string,string>();  
        map<string,string> zipToTerRegionMap = new map<string,string>();  
        map<string,string> zipToTerDistrictMap = new map<string,string>();  
        String countryName ; 
        Integer Ziplength = 0 ;
		switch on country {
			when 'DE' {
				Ziplength = 5;
				countryName = 'Germany';
			}
			when 'CA' {
				Ziplength = 3;
				countryName = 'Canada';
			}
			when 'CH' {
				Ziplength = 4;
				countryName = 'Switzerland';
			}
			when 'AT' {
				Ziplength = 4;
				countryName = 'Austria';
			}
			when 'GB' {
				countryName = 'United Kingdom';
			}
			when 'IE' {
				countryName = 'Ireland';
			}
		}
        system.debug('-country - ' + country);		
        system.debug('-Ziplength - ' + Ziplength);
        
         for (Lead le: leadsToProcess) {
			 system.debug('-le.Zip_To_Align__c - ' + le.Zip_To_Align__c);
            if(!String.isBlank(le.Zip_To_Align__c)){
				if((country == 'GB' || country == 'IE' ) && le.Zip_To_Align__c != null)
				{
					zipcodes.add(le.Zip_To_Align__c.substringBefore(' '));
					zipcodes.add(le.Zip_To_Align__c);
				}
				else		
                if(le.Zip_To_Align__c.length() >= Ziplength ){
                    zipcodes.add(le.Zip_To_Align__c.substring(0,Ziplength)); 
                }
            }
         }      
         system.debug('-zipcodes - ' + zipcodes);
        if(zipcodes.size()>0){
            //Query the Zip_to_Terr object to get the zipcode, Territory,District and Region values and put them in a map
            for(Zip_to_Terr__c zipToTerr : [Select name, Territory__c,District__c,Country__c,Region__c,State__c from Zip_to_Terr__c WHERE Country__c = :countryName and Name IN :zipcodes]){
                zipToTerMap.put (zipToTerr.name, zipToTerr.Territory__c);
                zipToTerRegionMap.put(zipToTerr.name,zipToTerr.Region__c);
                zipToTerDistrictMap.put(zipToTerr.name,zipToTerr.District__c); 
            }
            //Map the Territory, Region, District as per the zip to align field on the account
            for(Lead le: leadsToProcess) {
				String zipToAlign;	
                if(le.Zip_To_Align__c != null){
                    if(!zipToTerMap.isEmpty())
					{
						if(country == 'GB' || country == 'IE')
							zipToAlign = le.Zip_To_Align__c.substringBefore(' ');
						else
						if(le.Zip_To_Align__c.length() >= Ziplength && le.Zip_To_Align__c.substring(0,Ziplength) != null)  
					    zipToAlign = le.Zip_To_Align__c.substring(0,Ziplength);
						String territory = zipToTerMap.get(zipToAlign);
						String region = zipToTerRegionMap.get(zipToAlign);
						String district = zipToTerDistrictMap.get(zipToAlign);
						if(territory != null) {
							le.Territory__c = territory;
							le.Region__c = region;
							le.District__c = district; 
							leadList.add(le);
						}							
					}
				}
            }
        }          
		try{
			if((leadList.size()>0) && batch != null){             
				update leadList;
			}
		}catch(DMLException ex){
			system.debug('***ERROR UPDATE*** ' + ex.getMessage());
		}           
    }
}