src/objects/Zip_to_Terr__c.object
<CustomObject>
    <description>Jagan 04/2/2017 - Created this object to hold zip to terr alignment information for all countries.</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>District</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Region</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Territory</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Zip to Terr</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip to Terrs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Liechtenstein</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <customValue>
        <fullName>Ireland</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Chile</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Spain</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong</fullName>
    </customValue>
    <customValue>
        <fullName>Hungary</fullName>
    </customValue>
    <customValue>
        <fullName>Israel</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Jordan</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <customValue>
        <fullName>Korea</fullName>
    </customValue>
    <customValue>
        <fullName>Kuwait</fullName>
    </customValue>
    <customValue>
        <fullName>Lebanon</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>Norway</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>Oman</fullName>
    </customValue>
    <customValue>
        <fullName>Poland</fullName>
    </customValue>
    <description>Global picklist will be used in various places</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

src/classes/ClsLeadObjectTest.cls
@isTest
public class ClsLeadObjectTest {
	
    @isTest
    private static void testLeadObject() {
      	Id leadRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName LIKE 'CA_%' AND SobjectType = 'Lead'].Id ;
        insert new Lead(Status = 'New', RecordTypeId = leadRecordTypeId, FirstName = 'Canada', LastName='Lead');
        System.assertNotEquals(Null, Lead.Id);
    }
    
   @isTest
    private static void testLeadObjectIE() {
      	Id leadRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName LIKE 'IE_%' AND SobjectType = 'Lead'].Id ;
        insert new Zip_to_Terr__c (name = 'P36', Territory__c = 'IE020101', District__c = 'IE020100', Country__c='Ireland', Region__c='IE020000');
        Lead Le =  new Lead(Status = 'New', RecordTypeId = leadRecordTypeId, FirstName = 'Ireland', LastName='Lead', PostalCode='P36', Street='test',  City='test', Country='Ireland');
        insert Le;
      //  Le.PostalCode = 'P37';
      //  update Le ;        
        System.assertNotEquals(Null, Lead.Id);
    }
    
    @isTest
    private static void testLeadObjectCA() {
      	Id leadRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName LIKE 'CA_%' AND SobjectType = 'Lead'].Id ;
        insert new Zip_to_Terr__c (name = 'P38', Territory__c = 'CA020101', District__c = 'CA020100', Country__c='Canada', Region__c='CA020000');
        Lead Le =  new Lead(Status = 'New', RecordTypeId = leadRecordTypeId, FirstName = 'Canada', LastName='Lead', PostalCode='P38', Street='test',  City='test', Country='Canada');
        insert Le;
              
        System.assertNotEquals(Null, Lead.Id);
    }
    
    @isTest
    private static void testLeadObjectGB() {
      	Id leadRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName LIKE 'GB_%' AND SobjectType = 'Lead'].Id ;
        insert new Zip_to_Terr__c (name = 'P39', Territory__c = 'GB020101', District__c = 'GB020100', Country__c='United Kingdom', Region__c='GB020000');
        Lead Le =  new Lead(Status = 'New', RecordTypeId = leadRecordTypeId, FirstName = 'United Kingdom', LastName='Lead', PostalCode='P39', Street='test',  City='test', Country='United Kingdom');
        insert Le;
              
        System.assertNotEquals(Null, Lead.Id);
    }
     @isTest
    private static void testLeadObjectDE() {
        List<Lead> lstLead = new List<Lead>();
        List<Lead> lstLeadNew = new List<Lead>();
        
        Map<Id,Lead> mapNewLead = new Map<Id,Lead>();
        Map<Id,Lead> mapOldLead = new Map<Id,Lead>();
      	Id leadRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName LIKE 'DE_%' AND SobjectType = 'Lead'].Id ;
        insert new Zip_to_Terr__c (name = 'P44', Territory__c = 'DE020101', District__c = 'DE020100', Country__c='Germany', Region__c='DE020000');
        Lead Le =  new Lead(Status = 'New', RecordTypeId = leadRecordTypeId, FirstName = 'Germany', LastName='Lead', PostalCode='P39', Street='test',  City='test', Country='Germany');
        insert Le;
        mapOldLead.put(Le.Id,le);
        lstLead.add(le);
        String leadCountry = Le.Country ;
        ClsLeadTerritoryTriggerHandler.OnBeforeInsert(lstLead, leadCountry);
              
        //System.assertNotEquals(Null, Lead.Id);
    }
    
    //ClsLeadTerritoryTriggerHandler
    @isTest
    private static void testCountryHandlerMethods() {
        List<Lead> lstLead = new List<Lead>();
        List<Lead> lstLeadNew = new List<Lead>();
        
        Map<Id,Lead> mapNewLead = new Map<Id,Lead>();
        Map<Id,Lead> mapOldLead = new Map<Id,Lead>();
      	Id leadRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName LIKE 'GB_%' AND SobjectType = 'Lead'].Id ;
        insert new Zip_to_Terr__c (name = 'P39', Territory__c = 'GB020101', District__c = 'GB020100', Country__c='United Kingdom', Region__c='GB020000');
        Lead Le =  new Lead(Status = 'New', RecordTypeId = leadRecordTypeId, FirstName = 'United Kingdom', LastName='Lead', PostalCode='P39', Street='test',  City='test', Country='United Kingdom');
        insert Le;
        mapOldLead.put(Le.Id,le);
        lstLead.add(le);
        String leadCountry = Le.Country ;
        ClsLeadTerritoryTriggerHandler.OnBeforeInsert(lstLead, leadCountry);
        le.FirstName = 'UK';
        le.PostalCode = 'P40';
        update le;
        lstLeadNew.add(le);
        mapNewLead.put(le.Id,le);
        ClsLeadTerritoryTriggerHandler.OnBeforeUpdate(lstLead, mapOldLead, leadCountry);
        //OnBeforeUpdate
       
    }
    
    
}